- .github/ISSUE_TEMPLATE.md
Update ISSUE_TEMPLATE.md to align with the style agreed upon across all
Material Components teams.
> docs(github): Update issue template

- README.md
Suggested changes to the main Readme for the repo
> [Documentation] Update README.md

- .eslintrc.yaml
> chore: Add parser options to ESLint config.

- packages/mdc-button/mdc-button.scss
- packages/mdc-card/mdc-card.scss
- packages/mdc-checkbox/_keyframes.scss
- packages/mdc-checkbox/mdc-checkbox.scss
- packages/mdc-elevation/_mixins.scss
- packages/mdc-icon-toggle/mdc-icon-toggle.scss
- packages/mdc-list/mdc-list.scss
- packages/mdc-ripple/_mixins.scss
- packages/mdc-select/mdc-select.scss
- packages/mdc-snackbar/mdc-snackbar.scss
- packages/mdc-textfield/mdc-textfield.scss
For context: this PR ensures newline consistency, adding necessary newlines and removing extraneous ones.
@traviskaufman PTAL!
> style(scss): Preemptively fixing styling issues for updated stylelint.

- packages/mdc-menu/simple/foundation.js
- test/unit/mdc-menu/simple.foundation.test.js
> fix(menu): Cancel running animations on destroy.

- webpack.config.js
> chore(build): Add license header to top of built files

- package.json
- scripts/cp-pkgs.js
- scripts/determine-pkg-versions.js
- scripts/lib/get-updated-pkgs.js
- Fix all lint issues in the scripts/ dir
- Ensure `lint:js` npm script lints the scripts/ dir
> fix(scripts): Fix lint issues

- packages/material-components-web/package.json
- packages/mdc-auto-init/README.md
- packages/mdc-auto-init/package.json
> docs: Fix install instructions for mdc-auto-init

- docs/integrating-into-frameworks.md
> docs(integrating-into-frameworks): Remove broken link reference

- docs/getting-started.md
- Remove the need for NodeJS/NPM to be installed locally. Use
[unpkg](https://unpkg.com/#/) instead.
- Remove outdated "coming soon" blurbs.
- Correct minor typos and grammatical errors.
> docs(getting-started): Add post-release amendments and updates

- docs/getting-started.md
css file imported instead of js in the section "Adding in JavaScript for dynamic components"
> Error import js

- .github/ISSUE_TEMPLATE.md
> docs(issue-template): Add components request policy, codepen repro links

- demos/fab.html
- packages/mdc-fab/README.md
- packages/mdc-fab/mdc-fab.scss
> fix(fab): Mdc web/fix misaligned icons mobile safari

- README.md
> docs(readme): Add Getting Started Guide to Useful Links section

- docs/authoring-components.md
- Add link to Codepen example using the C/A/F model
- Fix errors in example code
[ci skip]
> docs(authoring-components): Add post-release changes

- .gitignore
- packages/mdc-animation/README.md
- packages/mdc-animation/index.js
- packages/mdc-animation/package.json
- test/unit/mdc-animation/mdc-animation.test.js
#17 
Added index.js to mdc-animation to serve as a utility library for MDC Web. For now I don't know if the lone function in there should be part of a publicly documented API as it probably won't be used by developers. In the future we may want to implement something though if it becomes more like the Sass portion of mdc-animation.
> Mdc web/impl event name query

- packages/mdc-drawer/temporary/foundation.js
- test/unit/mdc-drawer/temporary.foundation.test.js
> fix(drawer): Remove `numbers` import from temporary drawer.

- CONTRIBUTING.md
> docs(contributing): Add build step for demo site deployment

- packages/mdc-drawer/_mixins.scss
- packages/mdc-list/mdc-list.scss
- packages/mdc-ripple/_mixins.scss
- packages/mdc-rtl/_mixins.scss
- packages/mdc-select/mdc-select.scss
- packages/mdc-textfield/mdc-textfield.scss
- packages/mdc-theme/_functions.scss
- packages/mdc-theme/_mixins.scss
- packages/mdc-typography/_mixins.scss
Remove all of the no longer needed // stylelint-disable / // stylelint-enable dollar-variable-pattern comments. 
Fixes #90.
> chore(stylelint): Enable dollar-variable-pattern

- demos/select.html
- packages/mdc-select/README.md
- packages/mdc-select/mdc-select.scss
> feat(select): Add multi-select styles to select component

- packages/mdc-select/README.md
- Remove status checkboxes
- Move "Multi Select" section up into a more prominent position within
usage
[ci skip]
> docs(select): Update README to reflect current state of component

- packages/mdc-select/README.md
> docs(select): Add backticks around HTML block

- packages/mdc-button/mdc-button.scss
- packages/mdc-fab/mdc-fab.scss
Resolves #110 
Note: this PR should be **rebased and merged** rather than squashed and merged
> button/fab: Show active button press feedback on iOS

- demos/textfield.html
- packages/mdc-textfield/README.md
- packages/mdc-textfield/foundation.js
- packages/mdc-textfield/index.js
- packages/mdc-textfield/mdc-textfield.scss
- test/unit/mdc-textfield/foundation.test.js
- test/unit/mdc-textfield/mdc-textfield.test.js
> fix(textfield): Labels on single-line text fields support native browser autocomplete

- demos/checkbox.html
- packages/mdc-checkbox/_variables.scss
- packages/mdc-checkbox/index.js
- packages/mdc-checkbox/mdc-checkbox.scss
- packages/mdc-checkbox/package.json
- packages/mdc-radio/mdc-radio.scss
- packages/mdc-ripple/_keyframes.scss
- packages/mdc-ripple/_mixins.scss
- packages/mdc-ripple/_variables.scss
- packages/mdc-ripple/mdc-ripple.scss
- test/unit/mdc-checkbox/mdc-checkbox.test.js
> feat(checkbox): Add ripples to checkboxes

- packages/mdc-drawer/temporary/mdc-temporary-drawer.scss
> fix(drawer): Add z-index to temporary drawer

- packages/mdc-card/mdc-card.scss
> fix(card): Add bottom margin for 3x media in horizontal blocks

- packages/mdc-menu/README.md
> docs(menu): Add foundation API methods to README

- README.md
- demos/README.md
> docs(demos): Adds readme to demos folder

- .stylelintrc.yaml
- demos/index.html
- demos/layout-grid.html
- package.json
- packages/material-components-web/material-components-web.scss
- packages/material-components-web/package.json
- packages/mdc-layout-grid/README.md
- packages/mdc-layout-grid/_mixins.scss
- packages/mdc-layout-grid/_variables.scss
- packages/mdc-layout-grid/mdc-layout-grid.scss
- packages/mdc-layout-grid/package.json
- webpack.config.js
Implements #170.
@traviskaufman PTAL, as you volunteered for the review :)
> feat(layout-grid): Add initial implementation of the layout grid.

- demos/ripple.html
- packages/mdc-ripple/_keyframes.scss
- packages/mdc-ripple/_mixins.scss
- packages/mdc-ripple/constants.js
- packages/mdc-ripple/foundation.js
- test/unit/mdc-ripple/foundation-activation.test.js
- test/unit/mdc-ripple/foundation-deactivation.test.js
- test/unit/mdc-ripple/foundation.test.js
> feat(ripple): Implement new ripple sizing requirements

- packages/mdc-textfield/foundation.js
If you prefer issues over pullreqs that fix such small things please let me know.
> fix(textfield) Remove unused parameter from comment

- lerna.json
- package.json
> chore(lerna): update lerna to latest beta

- packages/mdc-button/mdc-button.scss
> feat(button): Add user-select: none; to button

- README.md
> docs(readme): Clarify browser support

- docs/migrating-from-mdl.md
> docs: Add MDL migration guide.

- demos/drawer/permanent-drawer-above-toolbar.html
> docs(drawer) Removing extra </div> on drawer example

- packages/mdc-typography/_variables.scss
> feat(typography): Add !default to variables

- packages/mdc-toolbar/mdc-toolbar.scss
> fix(toolbar): Add z-index to fixed toolbars

- packages/mdc-textfield/README.md
> docs(textfield) Update README.md

- demos/toolbar/fixed-top-toolbar.html
- packages/mdc-toolbar/README.md
- packages/mdc-toolbar/mdc-toolbar.scss
> fix(toolbar): Correct class name for mdc-toolbar-fixed-adjust

- docs/developer.md
Turning developer.md into an introduction for developers interested in creating MDC components, some of the content I removed from the overview will be added into the general Readme.md
> Updates to developer.md

- packages/mdc-form-field/mdc-form-field.scss
fix [#371](https://github.com/material-components/material-components-web/issues/371)
> fix(text-field): Make component entirely clickable

- packages/mdc-snackbar/constants.js
- test/unit/mdc-base/component.test.js
- test/unit/mdc-checkbox/mdc-checkbox.test.js
- test/unit/mdc-drawer/util.test.js
- test/unit/mdc-form-field/foundation.test.js
- test/unit/mdc-radio/mdc-radio.test.js
- test/unit/mdc-snackbar/mdc-snackbar.test.js
A few tweaks to tests to increase coverage a bit.
Related to #319.
> test(infrastructure): More test coverage

- CONTRIBUTING.md
- scripts/pre-release.sh
- Update scripts/pre-release.sh with correct publish command
- Update CONTRIBUTING.md releasing section with guidance on what to do
when a release goes awry.
[ci skip]
> chore(infrastructure): Update release scripts and docs

- demos/button.html
- demos/ripple.html
Fix typos for button and ripple demos
> docs(ripple): Fix typos on demos

- framework-examples/vue/src/v-mdc-snackbar/Snackbar.vue
> fix(framework-examples): Fix VueJS snackbar example

- framework-examples/react/package.json
> chore(framework-examples): Update dependencies

- framework-examples/vue/src/App.vue
- framework-examples/vue/src/v-mdc-checkbox/Checkbox.vue
- framework-examples/vue/src/v-mdc-drawer/TemporaryDrawer.vue
- framework-examples/vue/src/v-mdc-icon-toggle/IconToggle.vue
- framework-examples/vue/src/v-mdc-snackbar/Snackbar.vue
> fix(framework-examples): Fix VueJS lifecycle beforeDestroy hooks

- package.json
- test/unit/mdc-icon-toggle/mdc-icon-toggle.test.js
Closes #438
https://greenkeeper.io/
> chore(package): update testdouble to version 2.1.1

- docs/getting-started.md
the issue is closed now and merged to master, so the note should not be necessary anymore
please correct me if i'm wrong!
> docs(getting-started): remove link to issue #20

- CONTRIBUTING.md
> docs: Add PR background guidelines to CONTRIBUTING.md

- demos/drawer/permanent-drawer-above-toolbar.html
- demos/drawer/permanent-drawer-below-toolbar.html
- demos/drawer/temporary-drawer.html
Align the docs with recent breaking changes (#448)
of the toolbar component.
Resolves #470
> docs(drawer): Add .mdc-toolbar__row element

- demos/select.html
- packages/mdc-select/README.md
> docs(select): Fix DOM structure for disabled placeholder option

- packages/mdc-checkbox/mdc-checkbox.scss
- packages/mdc-radio/mdc-radio.scss
> fix(checkbox): Prevent checkboxes and radios from changing size with multiline label

- packages/mdc-icon-toggle/constants.js
- packages/mdc-icon-toggle/foundation.js
- packages/mdc-menu/simple/constants.js
- packages/mdc-radio/constants.js
- packages/mdc-radio/foundation.js
- packages/mdc-select/constants.js
- packages/mdc-select/foundation.js
- packages/mdc-textfield/constants.js
- packages/mdc-textfield/foundation.js
- packages/mdc-textfield/index.js
Solve #387 
In preparing for closure annotation.
> chore: Move const definition from foundation to separate constants.js file

- packages/material-components-web/index.js
> fix(auto-init): Register MDCPersistentDrawer

- packages/mdc-toolbar/mdc-toolbar.scss
> fix(toolbar): Prevent cut-offs of the toolbar section content

- packages/mdc-drawer/_mixins.scss
> fix(drawer): Remove -16px left positioning for interactive list items

- packages/mdc-animation/index.js
Also improves the branch coverage of our animation tests
> refactor(animation): Refactor switch statement to be simpler

- README.md
Same as on [material-motion](https://github.com/material-motion/material-motion-js/)
https://github.com/material-components/material-components-android/pull/35 and https://github.com/material-components/material-components-ios/pull/1405
> docs(readme): added badges

- package.json
- webpack.config.js
> chore(package): update postcss-loader to version 2.0.3

- docs/README.md
Just a small update to the copy for the documentation section.
> Update documentation readme.md

- docs/docsite-index.md
> docs: Update docsite-index.md

- docs/authoring-components.md
Missed one in the authorship doc.
> docs: One last broken link.

- packages/mdc-button/README.md
- packages/mdc-card/README.md
- packages/mdc-checkbox/README.md
- packages/mdc-dialog/README.md
- packages/mdc-elevation/README.md
- packages/mdc-fab/README.md
- packages/mdc-grid-list/README.md
- packages/mdc-icon-toggle/README.md
- packages/mdc-layout-grid/README.md
- packages/mdc-list/README.md
- packages/mdc-menu/README.md
- packages/mdc-radio/README.md
- packages/mdc-select/README.md
- packages/mdc-snackbar/README.md
- packages/mdc-switch/README.md
- packages/mdc-textfield/README.md
- packages/mdc-theme/README.md
- packages/mdc-toolbar/README.md
Doing a bit of post-launch code cleanup.
> docs: Adds BEM style classes to the screenshot demo links.

- packages/mdc-animation/README.md
- packages/mdc-tabs/tab-bar/foundation.js
> fix(tab-bar): Use proper import for animation

- docs/migrating-from-mdl.md
> docs: Update equivalence table

- packages/mdc-radio/mdc-radio.scss
> fix(checkbox): Fix radio button stretching in IE11

- demos/checkbox.html
> docs(checkbox): Fix third example of checkbox on demo page

- CONTRIBUTING.md
was going thorough this file, the saucelab wiki page seems to have been deleted and replaced
> fix link for Sauce Connect proxy

- packages/mdc-menu/simple/mdc-simple-menu.scss
> fix(menu): add 8px top and bottom padding

- package.json
- packages/mdc-base/component.js
- packages/mdc-base/foundation.js
Resolves #331: Annotate mdc-base for closure
> feat(base): Annotate mdc-base for closure

- demos/switch.html
> docs(demos): remove conflicting id on demo switch page

- demos/radio.html
Previously, the first set of radios would change when clicking the labels of the disabled radios.
https://material-components-web.appspot.com/radio.html
> fix(demos): Fix non-unique ids in radio demo

- package.json
- packages/mdc-base/component.js
- packages/mdc-menu/simple/adapter.js
- packages/mdc-menu/simple/constants.js
- packages/mdc-menu/simple/foundation.js
- packages/mdc-menu/simple/index.js
- packages/mdc-menu/util.js
Added new annotations to mdc-menu. Corrected a couple of annotations in base.
> feat(menu,base): annotate mdc-menu for closure compiler (#339)

- demos/fab.html
> fix(fab): FAB z-index is wrong

- framework-examples/vue/package-lock.json
- framework-examples/vue/package.json
- framework-examples/vue/src/App.vue
- framework-examples/vue/src/v-mdc-checkbox/Checkbox.vue
- framework-examples/vue/src/v-mdc-slider/Slider.vue
Add Continuous slider component to the Vue framework examples.
> Framework examples add Slider.vue

- packages/mdc-toolbar/mdc-toolbar.scss
Increased fixed toolbar's z-index from 1 to 4.
Fixes #834
> fix(toolbar): Fix z-index of fixed toolbars

- package.json
- test/unit/mdc-animation/mdc-animation.test.js
- test/unit/mdc-base/component.test.js
* changed mdc-animation tests to no longer mock 'createElement'
* changed mdc-base tests to no longer mock 'rootElementAtTimeOfCall'
> chore(package): update testdouble to version 3.2.0

- packages/mdc-fab/README.md
> docs(fab): Change value of position for fixed fab

- packages/mdc-list/mdc-list.scss
Fixes and closes #904 @amsheehan
> fix(list): List end detail has a wrong padding

- packages/mdc-card/mdc-card.scss
> fix(card): Text in a card should use text-primary-on-light

- packages/mdc-menu/README.md
> Correct the document error

- demos/fab.html
- packages/mdc-fab/README.md
> fix(fab): Floating FAB has a wrong distance from screen

- packages/mdc-layout-grid/_mixins.scss
- packages/mdc-layout-grid/mdc-layout-grid.scss
Added a flexible definition for media queries, thus making the grid only
dependent on the definition of grid variables.
> feat(layout-grid): variable grid layout definitions

- packages/mdc-grid-list/mdc-grid-list.scss
- packages/mdc-toolbar/mdc-toolbar.scss
- packages/mdc-typography/_mixins.scss
> refactor(typography): Create mixin for ellipsis

- packages/mdc-drawer/persistent/mdc-persistent-drawer.scss
- packages/mdc-drawer/slidable/_variables.scss
- packages/mdc-drawer/temporary/mdc-temporary-drawer.scss
https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior
> refactor(drawer): Rename transition vars to match spec

- packages/mdc-ripple/_mixins.scss
- packages/mdc-theme/_mixins.scss
This lets us compile our Sass files into Closure Stylesheets.
> chore: Add @alternate annotation

- package.json
- packages/mdc-base/index.js
- packages/mdc-base/selection-control.js
- packages/mdc-checkbox/adapter.js
- packages/mdc-checkbox/foundation.js
- packages/mdc-checkbox/index.js
- packages/mdc-radio/adapter.js
- packages/mdc-radio/foundation.js
- packages/mdc-radio/index.js
> refactor(radio): Annotate mdc-radio for closure

- packages/mdc-drawer/slidable/_variables.scss
Pending designer review.
Diffbase: PR #975
Fixes #646
> fix(drawer): Align close animation to spec

- packages/material-components-web/index.js
- scripts/check-pkg-for-release.js
> fix(form-field) Register MDCFormField in auto-init

- docs/getting-started.md
Edge now supports [CSS Custom Properties](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/csscustompropertiesakacssvariables/)
> Edge CSS Custom Properties Support

- packages/mdc-menu/README.md
> docs(menu): Updates menu screenshot width to accommodate new image.

- packages/mdc-slider/README.md
> docs(slider): Add link to demo page

- packages/mdc-auto-init/README.md
> fix(auto-init): Calling auto-init before the main mdc package doesn't initialize auto-init

- package-lock.json
Refs #1043.  (If the CONTRIBUTING idea I floated there sounds good, I'll include that here too.)
> chore(package): Repair package-lock.json to be in sync with recent updates

- packages/mdc-typography/README.md
- packages/mdc-typography/_mixins.scss
- packages/mdc-typography/_variables.scss
> feat(typography): Add button style to typography

- packages/mdc-dialog/mdc-dialog.scss
- packages/mdc-drawer/permanent/mdc-permanent-drawer.scss
- packages/mdc-drawer/persistent/mdc-persistent-drawer.scss
- packages/mdc-layout-grid/mdc-layout-grid.scss
- packages/mdc-theme/mdc-theme.scss
- packages/mdc-toolbar/mdc-toolbar.scss
> fix: Make CSS custom properties compatible with sass-spec 3.5

- demos/grid-list.html
- packages/mdc-grid-list/mdc-grid-list.scss
> fix(grid-list): Gracefully degrade tile width.

- package.json
To help us debug why the build is taking so long
> feat(infrastructure): Display webpack-dev-server build progress

- demos/button.html
- packages/mdc-button/README.md
- packages/mdc-button/_mixins.scss
- packages/mdc-button/mdc-button.scss
Closes #986 
Also fixed theme color `accent` -> `secondary`
> feat(button): implement unelevated button

- demos/fab.html
- packages/mdc-fab/README.md
- packages/mdc-fab/_mixins.scss
- packages/mdc-fab/mdc-fab.scss
BREAKING CHANGE: Removes styles for disabled FABs, as FABs were not designed to be disabled.
Tangentially related to #1143.
> feat(fab): Remove disabled styles

- packages/mdc-layout-grid/README.md
> docs(layout-grid): Update the margin recommendation.

- packages/mdc-fab/_mixins.scss
- packages/mdc-fab/mdc-fab.scss
FAB is always setting the tap-highlight to the same color
> refactor(fab): Remove ability to customize tap-highlight

- packages/mdc-ripple/mdc-ripple.scss
- packages/mdc-ripple/util.js
- test/unit/mdc-ripple/helpers.js
> fix(ripple): Don't create dynamic stylesheet for Edge feature-detect

- demos/textfield.html
- package-lock.json
- packages/mdc-textfield/README.md
- packages/mdc-textfield/constants.js
- packages/mdc-textfield/foundation.js
- packages/mdc-textfield/index.js
- packages/mdc-textfield/mdc-textfield.scss
- packages/mdc-theme/_variables.scss
- test/unit/mdc-textfield/foundation.test.js
- test/unit/mdc-textfield/mdc-textfield.test.js
Reverts material-components/material-components-web#1170
> Revert "feat(textfield): Add modified textfield css and tests"

- packages/mdc-button/_mixins.scss
> Refactor(button): Reorder the mixins to put public mixins before private ones

- packages/mdc-fab/README.md
fix a small typo introduced with  deb887a #1252
> fix class of Absolutely Positioned FAB

- packages/mdc-card/mdc-card.scss
- packages/mdc-select/mdc-select.scss
Fixes #1286.
I'm calling this a refactor rather than a fix because it's fixing regressions from a style commit that haven't actually appeared in a release yet.
> refactor: Fix regressions due to reordering @includes in #1265

- packages/mdc-button/README.md
- packages/mdc-button/_mixins.scss
- packages/mdc-button/mdc-button.scss
Also refactoring the README to match our tabular format. And cleaned up imports
> refactor(button): Remove stroke-style mixin until we have more guidance

- docs/codelabs/building-beautiful-sites/docsite/1-setup.md
- docs/codelabs/building-beautiful-sites/docsite/2-explore.md
- docs/codelabs/building-beautiful-sites/docsite/3-toolbar.md
- docs/codelabs/building-beautiful-sites/docsite/4-navigation.md
- docs/codelabs/building-beautiful-sites/docsite/5-layout.md
- docs/codelabs/building-beautiful-sites/docsite/introduction.md
> Codelab: change next step links to use production url format

- docs/codelabs/building-beautiful-sites/docsite/1-setup.md
- docs/codelabs/building-beautiful-sites/docsite/2-explore.md
- docs/codelabs/building-beautiful-sites/docsite/3-toolbar.md
- docs/codelabs/building-beautiful-sites/docsite/4-navigation.md
- docs/codelabs/building-beautiful-sites/docsite/5-layout.md
- docs/codelabs/building-beautiful-sites/docsite/6-wrapping-up.md
- docs/codelabs/building-beautiful-sites/docsite/introduction.md
- docs/codelabs/codelabs-index.md
Change the codelab route to /components/web/codelabs/beautiful-sites-simplified and add a codelabs index
@willlarche  @shyndman
> Codelab: change route

- packages/mdc-button/README.md
> docs(button): Add icon button usage in README

- demos/toolbar/default-flexible-toolbar.html
- demos/toolbar/default-toolbar.html
- demos/toolbar/fixed-toolbar.html
- demos/toolbar/index.html
- demos/toolbar/waterfall-flexible-toolbar.html
- demos/toolbar/waterfall-toolbar-fix-last-row.html
- demos/toolbar/waterfall-toolbar.html
This is also for aria and alt correctness
> docs(toolbar): Change non-menu toolbar to use bookmark instead

- package-lock.json
- package.json
> chore(package): remove raw-loader from dev dependencies

- packages/mdc-tabs/README.md
> docs(tabs): Fix invalid code example

- package.json
- packages/mdc-textfield/adapter.js
- packages/mdc-textfield/foundation.js
- packages/mdc-textfield/index.js
I missed this change with my previous PR #1386 for annotating Textfield for Closure.
> feat(textfield): Add textfield to the Closure whitelist.

- packages/mdc-menu/simple/mdc-simple-menu.scss
> fix(menu): Add pointer-events: none to avoid blocking click events

- packages/mdc-dialog/README.md
Resolves #1442 by clarifying docs.
> docs(dialog): Update README wording RE scrollable dialogs

- packages/mdc-textfield/constants.js
- packages/mdc-textfield/foundation.js
- packages/mdc-textfield/index.js
Needed for Closure Compiler compatibility.
> refactor(textfield): Add @license tags to mdc-textfield JS files

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- docs/code/README.md
- docs/code/architecture.md
- packages/mdc-base/README.md
> docs: Fix remaining broken links to developer docs

- package-lock.json
- package.json
- scripts/rewrite-decl-statements-for-closure-test.js
h/t @touficbatache for flagging this in #1487
> chore: Update eslint to 4.10 and fix lint error

- packages/mdc-menu/simple/mdc-simple-menu.scss
> fix(menu): Menu opening animation shows scrollbar

- package-lock.json
- package.json
> chore: Update standard-changelog to the latest version

- demos/checkbox.html
- packages/mdc-checkbox/README.md
> fix(checkbox): JavaScript console warning in IE

- packages/mdc-snackbar/mdc-snackbar.scss
> fix(snackbar): Snackbar should have padding between text & button (#1510)

- packages/mdc-menu/README.md
- packages/mdc-menu/simple/adapter.js
- packages/mdc-menu/simple/constants.js
- packages/mdc-menu/simple/foundation.js
- packages/mdc-menu/simple/index.js
- test/unit/mdc-menu/mdc-simple-menu.test.js
- test/unit/mdc-menu/simple.foundation.test.js
> feat(menu): Fix menu to only fire one event per interaction

- demos/list.html
> Fix spelling mistake in list demo

- demos/checkbox.scss
- packages/mdc-checkbox/mdc-checkbox.scss
> feat(checkbox): Use new mdc-states mixin for checkbox styles

- demos/radio.scss
- packages/mdc-radio/mdc-radio.scss
> feat(radio): Use new mdc-states mixin for radio styles

- packages/mdc-tabs/tab/mdc-tab.scss
> feat(tabs): Use new mdc-states mixin for tab styles

- packages/mdc-textfield/index.js
> chore(text-field): Export subcomponents from root index.js

- demos/theme/index.html
This wasn't updated when we merged #1097.
> docs: Update select DOM in theme demo page

- packages/mdc-textfield/mdc-text-field.scss
fixes: https://github.com/material-components/material-components-web/issues/1626
> fix(textfield): safari input has rounded corners

- packages/mdc-form-field/README.md
> docs(form-field): Clarify README a bit and remove redundant paragraph

- packages/mdc-checkbox/adapter.js
- packages/mdc-form-field/adapter.js
- packages/mdc-icon-toggle/adapter.js
- packages/mdc-menu/simple/adapter.js
- packages/mdc-radio/adapter.js
- packages/mdc-ripple/adapter.js
Updating architecture doc links adapter.js files
> docs: updated architecture doc links

- packages/mdc-list/mdc-list.scss
> fix(list): Move divider color style so it takes precedence

- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/mdc-text-field.scss
> refactor(text-field): split disabled state from scss file to mixins

- packages/mdc-drag-drop/drag-collection/index.js
refs #1795 
branched from #1859
> feat(card): auto scroll for drag and drop

- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/mdc-text-field.scss
> refactor(text-field): replaced text-field invalid css with mixin

- packages/mdc-select/README.md
> docs(select): Fix typo.

- webpack.config.js
- The `MDC_GENERATE_DEMO_THEMES` env var is no longer needed after #1886
- Avoid creating Webpack entries for demo Sass files that are import-only (i.e., their filename starts with an underscore)
- Rename local variable for clarity
> chore(demos): Remove env var and ignore import-only Sass files

- .stylelintrc.yaml
'Fu*r*thermore' was misspelled.
> Fix sepling mistake.

- docs/team/README.md
> docs: Remove broken link from team README

- demos/ready.js
- Remove blank lines
- Remove unneeded eslint-disable comment (the linter ignores demo files)
> style(demos): Rename vars in ready.js

- demos/text-field.html
- packages/mdc-textfield/README.md
- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/mdc-text-field.scss
BREAKING CHANGE: Remove css-only version of text-field.
> feat(text-field): Remove css only options. Update docs. Update demo

- packages/mdc-select/mdc-select.scss
> fix(select): Fix background-color that changed during first mixin PR

- demos/menu.html
- packages/mdc-menu/README.md
Clean up readme for menu component.
> chore(menu): Update readme

- packages/mdc-textfield/mdc-text-field.scss
> fix(text-field): Indent Outlined Helper Text

- scripts/webpack/copyright-banner-plugin.js
- scripts/webpack/plugin-factory.js
- test/build/goldens/build-config-dev-env.golden.json
- test/build/goldens/build-config-no-env.golden.json
- test/build/goldens/build-config-prod-env.golden.json
- webpack.config.js
> chore: Extract plugins from webpack.config.js into scripts/webpack

- scripts/build/environment.js
- webpack.config.js
> chore: Refactor environment JS into scripts/build/

- packages/mdc-card/mdc-card.scss
- packages/mdc-card/package.json
> fix(card): Remove unused dep/import and add missing dep

- packages/mdc-switch/mdc-switch.scss
fixes https://github.com/material-components/material-components-web/pull/2155/
Comment on PR https://github.com/material-components/material-components-web/pull/2155/files#r167947171
> fix(switch): change all border-radius values to 50% from hardcoded pixel values

- demos/toolbar/custom-toolbar.html
- demos/toolbar/default-flexible-toolbar.html
- demos/toolbar/default-toolbar.html
- demos/toolbar/fixed-toolbar.html
- demos/toolbar/menu-toolbar.html
- demos/toolbar/waterfall-flexible-toolbar-custom-style.html
- demos/toolbar/waterfall-flexible-toolbar.html
- demos/toolbar/waterfall-toolbar-fix-last-row.html
- demos/toolbar/waterfall-toolbar.html
Adds more text to each toolbar demo so we can get scrolling at all viewport sizes without having to constantly resize our browser.
> chore(toolbar): Add more text to each toolbar demo

- packages/mdc-menu/mdc-menu.scss
> fix(menu): use mdc-theme-prop to support css variables on background

- test/unit/mdc-line-ripple/mdc-line-ripple-foundation.test.js
Add missing tests for line-ripple.
> test(line-ripple): Update tests

- packages/mdc-ripple/_variables.scss
Turns out the values I implemented were outdated.
> fix(ripple): Fix selected opacity levels

- packages/mdc-top-app-bar/_mixins.scss
- packages/mdc-top-app-bar/_variables.scss
- packages/mdc-top-app-bar/constants.js
- packages/mdc-top-app-bar/foundation.js
- packages/mdc-top-app-bar/index.js
- packages/mdc-top-app-bar/mdc-top-app-bar.scss
Updates all copyright notices for top app bar files.
> chore(top-app-bar): Update copyright notices

- packages/mdc-line-ripple/foundation.js
- packages/mdc-line-ripple/mdc-line-ripple.scss
Update copyright notices inconsistent with the package.
> chore(line-ripple): Update copyright notices

- packages/mdc-slider/constants.js
- packages/mdc-slider/foundation.js
- packages/mdc-slider/index.js
Add missing `@license` annotations from two files.
> chore(slider): Add @license annotation to js files

- packages/mdc-select/label/README.md
> docs(select): Fix front matter for label sub-component

- demos/button.html
- demos/checkbox.html
- packages/mdc-button/README.md
- packages/mdc-button/_mixins.scss
- packages/mdc-button/_variables.scss
- packages/mdc-button/mdc-button.scss
> refactor(button): Remove compact variant

- packages/mdc-card/mdc-card.scss
> fix(card): Center background image

- demos/theme/index.html
Update `select` missed by recent refactor in theme demo.
> fix(select): Update theme select demo

- packages/mdc-image-list/README.md
This updates the width value relative to image that was added to site generator repo.
> docs(image-list): Update image width

- demos/index.html
Since we've added this to the catalog site index, it makes sense to add it to the demos index as well.
h/t eskimoji on discord for the reminder.
> docs: Add Top App Bar to index.html

- packages/mdc-button/_mixins.scss
Add an `@alternate` tag to the line-height for button
> chore(button): Add alternate tag

- packages/mdc-top-app-bar/README.md
Removes a line that should have been removed with the default scroll PR.
> docs(top-app-bar): Update readme

- demos/fab.html
- demos/fab.scss
- packages/mdc-fab/README.md
- packages/mdc-fab/_mixins.scss
- packages/mdc-fab/mdc-fab.scss
> feat(fab): Add support for svg icons

- demos/tab-indicator.html
- packages/mdc-tab-indicator/README.md
- packages/mdc-tab-indicator/_mixins.scss
- packages/mdc-tab-indicator/adapter.js
- packages/mdc-tab-indicator/constants.js
- packages/mdc-tab-indicator/foundation.js
- packages/mdc-tab-indicator/index.js
- packages/mdc-tab-indicator/mdc-tab-indicator.scss
- packages/mdc-tab-indicator/sliding-foundation.js
- test/unit/mdc-tab-indicator/foundation.test.js
- test/unit/mdc-tab-indicator/mdc-tab-indicator.test.js
- test/unit/mdc-tab-indicator/sliding-foundation.test.js
Update tab indicator to use absolute positioning of the tab indicator.
Update tab indicator surface mixin to use relative positioning.
> fix(tab-indicator): Use absolute positioning

- packages/mdc-auto-init/README.md
> docs(auto-init): Clarify "component's class name"

- packages/mdc-textfield/README.md
> docs(text-field): Clarify supported input types in README

- demos/theme/index.html
- demos/theme/theme-shrine.scss
Adds custom font styles for Shrine demo.
> feat(theme): Add typography styles to shrine demo

- packages/mdc-textfield/helper-text/mdc-text-field-helper-text.scss
Add `caption` type to helper-text.
> fix(text-field): Update helper text to use correct typography

- demos/select.scss
- packages/mdc-select/README.md
- packages/mdc-select/_mixins.scss
- packages/mdc-select/_variables.scss
- packages/mdc-select/mdc-select.scss
Update the colors to match the latest guidance. 
Added variables to match text field colors/opacity values. 
Removed opacity parameter from mixins.
> fix(select): Update colors to match latest guidance.

- demos/chips.html
- demos/chips.scss
- packages/mdc-chips/README.md
- packages/mdc-chips/chip-set/mdc-chip-set.scss
Design decision: change name from "entry" to "input" for chips which enable user input by converting text into chips.
> fix(chips): Rename all entry chips to input chips

- packages/mdc-radio/_variables.scss
- packages/mdc-radio/mdc-radio.scss
Update colors to use new on-surface theme color.
> fix(radio): Update colors to latest guidance

- packages/mdc-checkbox/_variables.scss
- packages/mdc-checkbox/package.json
Update checkbox colors to use the new colors on-primary and on-surface.
> fix(checkbox): Update to match new colors

- .travis.yml
- package.json
- scripts/site-generator-test.sh
Since we're doing quite a few README updates recently, it makes sense to flag any obvious errors in CI.
> chore(infrastructure): Allow testing site generator execution

- packages/mdc-grid-list/README.md
- packages/mdc-image-list/README.md
- packages/mdc-ripple/README.md
- packages/mdc-shape/README.md
- packages/mdc-toolbar/README.md
- packages/mdc-top-app-bar/README.md
Following on the tails of #2677.
> docs: Update more links to use new short links

- packages/mdc-floating-label/_mixins.scss
> fix(floating-label): Import RTL in mixin since it is being used.

- packages/mdc-textfield/README.md
- packages/mdc-textfield/foundation.js
> fix(text-field): Made handleValidationAttributeMutation method public.

- docs/getting-started.md
> docs(getting started): Add autoprefixer instructions

- docs/open_source/release.md
- scripts/pre-release.sh
Also remove a redundant dependency-test run from script
> docs: Update docs for pre-releases

- packages/mdc-icon-button/README.md
- packages/mdc-icon-toggle/README.md
Fixes #2895.
Also caught a bunch of trailing spaces in the process.
> docs(icon-button): Update demo and guidelines links

- docs/open_source/release-process.md
- docs/open_source/releases-and-branches.md
This documentation assumes that #2881 and #2897 are merged.
> docs: Update/improve release docs for different types of releases

- test/screenshot/bin/run-screenshot-test.js
- test/screenshot/bin/run-update-goldens.js
- test/screenshot/bin/run-upload-assets.js
Env vars:
```bash
```
Test:
```bash
```
> chore(infrastructure): Handle uncaught `Controller` errors

- packages/mdc-top-app-bar/README.md
> docs(top-app-bar): Update docs to include information for fixed-adjust classes

- packages/mdc-icon-button/README.md
- packages/mdc-icon-toggle/README.md
> docs(icon-button): Update catalog links for images in site

- packages/mdc-chips/README.md
- packages/mdc-chips/chip-set/foundation.js
- packages/mdc-chips/chip/foundation.js
Required to call handlers within a framework like React.
> fix(chips): Make event handlers on Chip public

- docs/code/architecture.md
> docs: Clarify Vanilla Component in architecture.md

- package.json
> add webpack-cli

- test/screenshot/commands/test.js
- test/screenshot/lib/cli.js
- test/screenshot/lib/cloud-storage.js
- test/screenshot/lib/constants.js
- test/screenshot/lib/controller.js
- test/screenshot/lib/report-builder.js
- test/screenshot/lib/report-writer.js
- test/screenshot/lib/selenium-api.js
```bash
npm run screenshot:test -- --offline --retries=0
```
> chore(infrastructure): Enable `--offline` Selenium tests

- packages/mdc-shape/README.md
> docs(shape): Add explicit mdc-shape import to readme

- test/screenshot/commands/travis.sh
- test/screenshot/lib/cbt-api.js
- test/screenshot/lib/duration.js
- test/screenshot/lib/logger.js
- test/screenshot/lib/selenium-api.js
- Tests that have N=0 diffs will be marked "pass" in the CBT UI
- Tests that have N>0 diffs will be marked as "fail" in the CBT UI
- Fixes collapsible fold sections in Travis job logs
- Adds timing information to fold sections in Travis job logs
>  chore(infrastructure): Mark CBT Selenium tests as pass/fail

- test/screenshot/.gitignore
- test/screenshot/report/_metadata.hbs
- Also delete obsolete `.gitignore` file
> chore(infrastructure): Link to GitHub tag for MDC version number

- test/screenshot/diffing.json
- test/screenshot/infra/commands/build.js
- test/screenshot/infra/lib/cli.js
- test/screenshot/infra/lib/externs.js
- test/screenshot/infra/lib/selenium-api.js
Also:
- Adds `max_auto_retry_changed_pixel_fraction` property to `diffing.json`
- Fixes `@typedef` syntax in `externs.js`
> chore(infrastructure): Display '0' values in CLI `--help`

- .travis.yml
- test/screenshot/infra/commands/test.js
- test/screenshot/infra/lib/github-api.js
- test/screenshot/infra/lib/selenium-api.js
- Every 5 seconds, updates GitHub PR status check description with the test progress
> chore(infrastructure): Post test progress to GitHub PR

- packages/mdc-fab/README.md
> docs(fab): Added variants section to FAB readme

- packages/mdc-tab-scroller/mdc-tab-scroller.scss
- packages/mdc-tab-scroller/package.json
- packages/mdc-tab/README.md
- packages/mdc-tab/_mixins.scss
> feat(tab): Add mixin for parent positioning; Use mixin in tab scroller

- .travis.yml
- karma.conf.js
Fixes #2815
https://travis-ci.org/material-components/material-components-web/jobs/407944719
TODO(acdvorak): For internal PRs, consider running this as a smoke test _before_ running the full suite on Sauce Labs. This would let us fail faster and avoid consuming more SL resources than necessary.
> chore(infrastructure): Run unit tests for external PRs (Chrome only)

- docs/open_source/release-process.md
Simplifies/fixes a few things noticed during last release.
> docs: Release process clarification tweaks

- test/screenshot/infra/lib/diff-base-parser.js
- test/screenshot/infra/lib/git-repo.js
- test/screenshot/infra/lib/stacktrace.js
- https://travis-ci.org/material-components/material-components-web/jobs/408248312
- https://travis-ci.org/material-components/material-components-web/jobs/408229973
- https://travis-ci.org/material-components/material-components-web/jobs/408266376
> chore(infrastructure): Add stack traces for failing master merges

- karma.conf.js
Fix local tests. I previously added the object to the wrong key.
> chore(infrastructure): Fix local tests

- test/screenshot/infra/commands/travis.sh
- test/screenshot/infra/lib/git-repo.js
- test/screenshot/infra/lib/stacktrace.js
Also:
- Fixes typo in `getStackTrace()`
> chore(infrastructure): Throw more descriptive errors in GitRepo class

- test/screenshot/README.md
Requested in https://github.com/material-components/material-components-web/pull/3287#discussion_r207306952
> chore(infrastructure): Update example in screenshot README

- docs/getting-started.md
> docs: Clarify where Sass importer code is added

- package-lock.json
- package.json
- `@google-cloud/storage` is no longer needed after #2932
- `json-loader` is not used anywhere, and is not needed in Webpack >= 2
> chore(infrastructure): Remove unused devDependencies from package.json

- packages/mdc-notched-outline/mdc-notched-outline.scss
- packages/mdc-notched-outline/package.json
- test/screenshot/golden.json
- test/screenshot/spec/mdc-textfield/issues/3332.html
> fix(notched-outline): Add alignment

- packages/mdc-notched-outline/README.md
Add installation instructions to mdc-notched-outline package README
> Add install instructions to notched-outline README

- packages/mdc-menu-surface/mdc-menu-surface.scss
> fix(menu-surface): Remove overflow hidden during menu-surface animation.

- README.md
> docs: Add npm version badge and note about 0.x

- packages/mdc-chips/chip/index.js
- test/unit/mdc-chips/mdc-chip-set.test.js
- test/unit/mdc-chips/mdc-chip.foundation.test.js
- test/unit/mdc-chips/mdc-chip.test.js
This should help avoid feature branches falling below 95% branch coverage.
Total on master:
Total on branch:
> chore(chips): Improve test coverage

- closure_externs.js
- packages/mdc-drawer/index.js
- packages/mdc-drawer/util.js
- test/unit/mdc-drawer/mdc-drawer.test.js
First of all, thanks so much @trimox for spotting this in #3422 before we even released!
This builds off of #3422 to fix closure tests, and also fix unit tests to reference mocks where needed.
> fix(drawer): Fix exports and closure tests

- packages/mdc-select/README.md
> docs: Update select mixins in readme

- packages/mdc-menu-surface/mdc-menu-surface.scss
> fix(menu-surface): Fix interpolation in calc

- packages/mdc-menu/mdc-menu.scss
> fix(menu): Update styles to match guidance

- test/screenshot/golden.json
- test/screenshot/spec/fixture.scss
- test/screenshot/spec/mdc-drawer/classes/dismissible.html
- test/screenshot/spec/mdc-drawer/classes/modal.html
- test/screenshot/spec/mdc-drawer/classes/permanent.html
- test/screenshot/spec/mdc-drawer/fixture.scss
- test/screenshot/spec/mdc-drawer/mixins/fill-color-accessible.html
- test/screenshot/spec/mdc-drawer/mixins/fill-color.html
This PR also:
* Fixes some invalid HTML in drawer test pages
* Adds longer body text to drawer test pages (to show overflow scrolling behavior)
> chore(infrastructure): Add grid pattern to fullscreen test page bg

- packages/mdc-textfield/_variables.scss
- packages/mdc-theme/_variables.scss
fixes: #3468 
Adds error/on-error theme support. 
The text field component has been updated to use the error color from the theme.
> feat(theme): Add error and on-error support

- packages/mdc-list/index.js
- packages/mdc-menu/index.js
- test/unit/mdc-menu/mdc-menu.test.js
Fixes an issue highlighted by the menu/drawer PR's that the get method for accessing the list elements was incorrectly added as a private method.
> fix(list): Change private getter method to public

- demos/dialog.html
- demos/drawer/dismissible-drawer.html
- demos/drawer/modal-drawer.html
- demos/drawer/permanent-drawer.html
- demos/list.html
- demos/menu-surface.html
- demos/menu.html
- packages/mdc-dialog/README.md
- packages/mdc-drawer/README.md
- packages/mdc-list/README.md
- packages/mdc-list/mdc-list.scss
- packages/mdc-menu/README.md
- packages/mdc-theme/_color-palette.scss
- test/screenshot/spec/mdc-drawer/classes/dismissible.html
- test/screenshot/spec/mdc-drawer/classes/modal.html
- test/screenshot/spec/mdc-drawer/classes/permanent.html
> fix(list): Update single line list to ellipsis

- packages/mdc-menu/foundation.js
- test/unit/mdc-menu/menu.foundation.test.js
> fix(menu): Prevent endless loop from unexpected markup

- test/screenshot/infra/lib/report-builder.js
* Skips browsers that don't have any runnable screenshots:
- If the user specifies a `--url` pattern on the CLI, and all test page URLs matched by that pattern are disabled in a specific browser, that browser is no longer started.
In `diffing.json`, we currently disable all `textarea` pages in Edge due to excessive flakiness.
If you pass `--url=textarea` to `screenshot:test`, it should not start Edge:
```bash
npm run screenshot:test -- --url=mdc-textfield/classes/textarea
```
```
ACTIVE: desktop_windows_chrome@latest, desktop_windows_firefox@latest, desktop_windows_edge@latest, desktop_windows_ie@11
QUEUED: (none)
STARTING: desktop_windows_chrome@latest...
STARTING: desktop_windows_firefox@latest...
STARTING: desktop_windows_edge@latest...
STARTING: desktop_windows_ie@11...
STARTED: IE 11 …
```
> chore(infrastructure): Skip browsers excluded by URL patterns

- test/screenshot/golden.json
- test/screenshot/spec/mdc-icon-button/classes/baseline-icon-button-toggle.html
- test/screenshot/spec/mdc-icon-button/classes/baseline.html
- test/screenshot/spec/mdc-icon-button/fixture.js
This should enable testing #3521.
> test(icon-button): Add focus to baseline screenshot test pages

- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/_variables.scss
- test/screenshot/golden.json
> fix(text-field): Fix outlined disabled text color to match filled variant

- packages/mdc-ripple/_mixins.scss
fixes: #3551 
Per our discussion, we may not accept this change but I wanted to see the diffs and have a solution in place in case we did.
> fix(ripple): Change default color from black to on-surface

- packages/mdc-menu/_variables.scss
- packages/mdc-menu/mdc-menu.scss
Removes max-width from the menu.
> fix(menu): Remove max-width

- packages/mdc-dialog/_variables.scss
- packages/mdc-dialog/mdc-dialog.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-dialog/classes/baseline-alert-above-drawer.html
Fixes #3596.
Also adds a screenshot test page.
Before:
After:
> fix(dialog): Increase z-index above Drawer

- .travis.yml
- demos/select.html
- packages/mdc-select/_mixins.scss
- packages/mdc-select/_variables.scss
- packages/mdc-select/foundation.js
- packages/mdc-select/mdc-select.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-select/classes/baseline.html
- test/screenshot/spec/mdc-select/classes/disabled.html
- test/screenshot/spec/mdc-select/issues/3230-3496.html
- test/screenshot/spec/mdc-select/mixins/bottom-line-color.html
- test/screenshot/spec/mdc-select/mixins/container-fill-color.html
- test/screenshot/spec/mdc-select/mixins/corner-radius.html
- test/screenshot/spec/mdc-select/mixins/ink-color.html
- test/screenshot/spec/mdc-select/mixins/label-color.html
- test/screenshot/spec/mdc-select/mixins/outline-color.html
Separates the dropdown arrow into it's own element and adds the ability for the dropdown arrow to rotate when the menu is opened.
> feat(select): Rotate dropdown arrow

- demos/tab-bar.html
- demos/tab-indicator.html
- demos/tab.html
- packages/mdc-tab-bar/README.md
- packages/mdc-tab-indicator/README.md
- packages/mdc-tab/README.md
- packages/mdc-tab/mdc-tab.scss
- test/unit/mdc-tab/mdc-tab.test.js
> docs(tab): Update docs RE icons and aria-hidden

- docs/getting-started.md
> docs: Add build section to getting-started.md

- packages/mdc-drawer/README.md
- packages/mdc-drawer/adapter.js
- packages/mdc-drawer/dismissible/foundation.js
- packages/mdc-drawer/index.js
- test/unit/mdc-drawer/dismissible.foundation.test.js
- test/unit/mdc-drawer/mdc-drawer.test.js
> fix(drawer): Use rAF/setTimeout for opening class

- packages/mdc-checkbox/README.md
These were missed in #3408.
h/t @azakus
> docs(checkbox): Clean up removed foundation APIs

- packages/mdc-floating-label/mdc-floating-label.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-textfield/issues/3332.html
> fix(floating-label): Enforce text alignment

- docs/open_source/release-process.md
- scripts/pre-release.sh
> chore(infrastructure): Check for 2FA before publishing to npm

- packages/mdc-shape/README.md
- packages/mdc-shape/_variables.scss
BREAKING CHANGE: Renamed shape global variables from `$mdc-shape-*-surface-radius` to `$mdc-shape-*-component-radius`
> fix(shape): Rename surface term with component.

- packages/mdc-floating-label/_mixins.scss
- packages/mdc-layout-grid/_mixins.scss
- packages/mdc-linear-progress/_mixins.scss
- packages/mdc-select/_mixins.scss
Fixes #2239 and avoids unwanted diffs in #3752.
> fix: Future-proof Sass usage

- test/screenshot/infra/lib/status-notifier.js
> chore(infrastructure): Mark diffs as failures in GitHub status checks

- packages/mdc-typography/_mixins.scss
Add the alternate tag to the typography baseline top mixin
> fix(typography): Add alternate tag for line-height

- packages/mdc-floating-label/mdc-floating-label.scss
Add the alternate tag for line-height to appease closure stylesheets
> fix(floating-label): Add alternate tag

- packages/mdc-drawer/README.md
> docs(drawer): Clarify wording RE scrim element

- packages/mdc-textfield/README.md
- packages/mdc-textfield/index.js
- test/unit/mdc-textfield/mdc-text-field.test.js
> feat(text-field): Add focus API to component

- docs/importing-js.md
> docs: Add instantiation examples to importing docs

- packages/mdc-card/mdc-card.scss
Card is medium sized component.
> fix(card): Corrected baseline shape value of card small => medium

- packages/mdc-list/_mixins.scss
- packages/mdc-list/mdc-list.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-dialog/fixture.scss
> fix(list): Fix font size and placement for avatar graphic

- package.json
- packages/mdc-snackbar/_mixins.scss
- packages/mdc-snackbar/adapter.js
- packages/mdc-snackbar/constants.js
- packages/mdc-snackbar/foundation.js
- packages/mdc-snackbar/index.js
- packages/mdc-snackbar/mdc-snackbar.scss
- packages/mdc-snackbar/package.json
- test/screenshot/spec/mdc-snackbar/fixture.js
- test/unit/mdc-snackbar/foundation.test.js
- test/unit/mdc-snackbar/mdc-snackbar.test.js
> feat(snackbar): Update JavaScript API to match guidelines

- packages/mdc-chips/README.md
> docs: Fixed chipsets docs - moved selectedChipIds to properties table

- packages/mdc-card/mdc-card.scss
- test/screenshot/golden.json
> fix(card): Update elevation to match spec

- packages/mdc-select/index.js
> fix(select): Add missing exports

- packages/mdc-layout-grid/README.md
> docs(layout-grid): Add styles to usage

- packages/mdc-notched-outline/index.js
h/t @trimox in https://github.com/material-components/material-components-web/pull/4145#issuecomment-444661966
> docs(notched-outline): Remove remaining mention of SVG

- packages/mdc-menu-surface/mdc-menu-surface.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-menu/issues/4025.html
- test/screenshot/spec/mdc-menu/issues/fixture.scss
> fix(menu-surface): Raise z-index over MDC Dialog

- packages/mdc-card/README.md
> docs(card): Improve readme and update format

- packages/mdc-elevation/README.md
> docs(elevation): Add html/styles sections for new format

- packages/mdc-dialog/package-lock.json
- packages/mdc-dialog/package.json
- packages/mdc-drawer/package-lock.json
- packages/mdc-drawer/package.json
> fix(drawer): Upgrade focus-trap version in drawer & dialog

- scripts/cp-pkgs.js
Fix for missing source-map files in npm releases
Fixes #2942
> fix(package): Add source-map files to npm releases

- test/screenshot/golden.json
- test/screenshot/spec/mdc-textfield/issues/4170.html
> chore(infrastructure): Redact flaky Text Field labels in Edge screenshot

- ROADMAP.md
> docs: Update roadmap

- package-lock.json
- package.json
- test/screenshot/golden.json
- test/screenshot/infra/lib/selenium-api.js
- test/screenshot/spec/mdc-menu/classes/menu-selection-group.html
> chore(infrastructure): Dynamic screenshot test viewport size

- packages/material-components-web/index.js
- packages/mdc-dom/index.js
- packages/mdc-dom/index.ts
- packages/mdc-dom/ponyfill.ts
- scripts/webpack/js-bundle-factory.js
- test/unit/mdc-dom/ponyfill.test.js
> feat(dom): Convert JS to TypeScript

- packages/mdc-button/_mixins.scss
- packages/mdc-elevation/_mixins.scss
- test/scss/feature-targeting.scss
>  feat(elevation): add feature targeting for styles

- packages/mdc-button/_mixins.scss
- packages/mdc-checkbox/_mixins.scss
- packages/mdc-radio/_mixins.scss
- packages/mdc-ripple/_mixins.scss
- test/scss/feature-targeting.scss
>  feat(ripple): add feature targeting to remaining public mixins

- test/screenshot/browser.json
- test/screenshot/golden.json
Supersedes #4322, after encountering multiple rounds of flakes and discussing with the team.
> chore: Stop running screenshot tests in Edge

- packages/mdc-notched-outline/mdc-notched-outline.scss
- packages/mdc-textfield/_functions.scss
- packages/mdc-textfield/mdc-text-field.scss
> fix(text-field): Fix textfield placeholder & outline stroke animation

- packages/mdc-chips/README.md
> docs(chips): Update code example that demos chip removal

- packages/mdc-menu-surface/_mixins.scss
The opening animation is no longer present the first time the menu opens, as seen on the MDC docs site, as well as causing issues in my React wrapper.
https://material-components.github.io/material-components-web-catalog/#/component/menu
> fix(MenuSurface): Corrects open animation issue

- packages/mdc-line-ripple/README.md
- packages/mdc-line-ripple/adapter.ts
- packages/mdc-line-ripple/constants.ts
- packages/mdc-line-ripple/foundation.ts
- packages/mdc-line-ripple/index.ts
- scripts/webpack/js-bundle-factory.js
> feat(line-ripple): Convert JS to TypeScript

- packages/mdc-button/_mixins.scss
- packages/mdc-card/_mixins.scss
- packages/mdc-list/_mixins.scss
- packages/mdc-menu-surface/_mixins.scss
- packages/mdc-shape/_mixins.scss
- test/scss/feature-targeting.scss
> feat(shape): add feature targeting to public mixins

- packages/mdc-textfield/mdc-text-field.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-textfield/classes/baseline-fullwidth.html
> fix(text-field): Fix placeholder styles for text field fullwidth variant.

- packages/mdc-textfield/README.md
"Helper text" -> "Character counter"
> docs(text-field): Fix typo

- packages/mdc-card/package.json
- packages/mdc-checkbox/package.json
- packages/mdc-elevation/package.json
- packages/mdc-list/_mixins.scss
- packages/mdc-list/package.json
- packages/mdc-menu-surface/package.json
- packages/mdc-menu/package.json
- packages/mdc-radio/package.json
- packages/mdc-shape/package.json
- packages/mdc-switch/package.json
- packages/mdc-typography/package.json
> chore: Add missing dependency feature-targeting

- .travis.yml
- packages/mdc-auto-init/index.ts
- packages/mdc-base/component.ts
- packages/mdc-menu-surface/foundation.ts
- test/screenshot/golden.json
- test/screenshot/spec/mdc-menu/classes/bottom-anchored.html
- test/screenshot/spec/mdc-menu/fixture.scss
Changes that didn't make it into #4451:
- Remove `feat/typescript` branch from `.travis.yml`
- Replace `any` with `unknown` in all TS files
- Add screenshot test for menu anchored in bottom-right corner
- Remove unnecessary ternary
> chore: Update .travis.yml and replace any with unknown

- README.md
- docs/open_source/release-process.md
- docs/open_source/releases-and-branches.md
Shout-outs to @yasmineevjen for pointing out the stale note in the README and setting me off on a hunt for other similar instances.
> docs: Update versioning docs/references

- packages/mdc-top-app-bar/README.md
> docs(top-app-bar): Remove alt attributes from anchor tags

- packages/mdc-drawer/component.ts
- test/unit/mdc-drawer/mdc-drawer.test.js
> feat(drawer): Make list instance publicly accessible

- packages/mdc-menu/_mixins.scss
- packages/mdc-menu/_variables.scss
Fixes #4238 as it pertains to Menu.
> fix(menu): Use on-surface color for graphic/meta content

- packages/mdc-menu/_mixins.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-menu/classes/menu-selection-group-only.html
> fix(menu): Fix selection group list item spacing

- packages/material-components-web/README.md
Updated the MCW package README destructuring format by removing spaces around symbol and brace as per the readme-standards.md
Fixes #4550
> docs: Update MCW package README Destructuring Format

- packages/mdc-textfield/foundation.ts
- test/unit/mdc-textfield/foundation.test.js
Set the character counter value in the `setValue` method
> fix(text-field): Set character counter in setValue

- scripts/webpack/copyright-banner-plugin.js
- scripts/webpack/js-bundle-factory.js
- scripts/webpack/plugin-factory.js
**File size comparison**
Name | Before | After
-- | -- | --
material-components-web.js | 840K | 708K
material-components-web.min.js | 464K | 296K
**File size comparison (w/ gzip compression)**
Name | Before | After
-- | -- | --
material-components-web.js | 96.64KB | 72.68KB
material-components-web.min.js | 53.01KB | 48.18KB
Fixes #4220
> chore: Remove repeated license comments from minified source code

- docs/integrating-into-frameworks.md
> docs: Update plunker link in integrating-into-frameworks doc

- packages/mdc-textfield/constants.ts
There are some classes which is defined in README.md.
But there is no definition in constant.ts.
So I added it!
> fix(text-field): add classes constant

- packages/mdc-checkbox/_mixins.scss
> fix(checkbox): Fixed disabled checkbox styles for Edge browser

- packages/mdc-chips/chip-set/constants.ts
- packages/mdc-chips/chip/constants.ts
related to https://github.com/material-components/material-components-web-react/issues/827
>  feat(chips): add chips classes constant

- packages/mdc-icon-button/constants.ts
related to https://github.com/material-components/material-components-web-react/issues/827
Maybe we need to notify breaking change that cssClasses.ICON_BUTTON_ON changes to cssClasses.ON.
> feat(drawer): update icon-button cssClasses constant

- packages/mdc-drawer/constants.ts
related to https://github.com/material-components/material-components-web-react/issues/827
> feat(drawer): update drawer cssClasses constant

- packages/mdc-line-ripple/constants.ts
- packages/mdc-linear-progress/constants.ts
- packages/mdc-list/constants.ts
- packages/mdc-notched-outline/constants.ts
- packages/mdc-radio/constants.ts
- packages/mdc-select/constants.ts
- packages/mdc-snackbar/constants.ts
- packages/mdc-switch/constants.ts
- packages/mdc-tab-bar/constants.ts
- packages/mdc-tab-indicator/constants.ts
- packages/mdc-tab-scroller/constants.ts
- packages/mdc-tab/constants.ts
- packages/mdc-top-app-bar/constants.ts
related to https://github.com/material-components/material-components-web-react/issues/827
Working complete!
> feat: Updated constant files with supported cssClasses

- packages/mdc-data-table/_mixins.scss
- packages/mdc-data-table/_variables.scss
- test/screenshot/golden.json
> feat(data-table): Set 48dp touch dimension for row checkbox in data table

- test/screenshot/golden.json
Appears to be an update to Firefox.
> fix(infrastructure): Fix failing screenshot tests

- scripts/check-pkg-for-release.js
related https://github.com/material-components/material-components-web/issues/4738
> fix: Remove references of icon-toggle in check-pkg-for-release script

- ROADMAP.md
Removed the reference to a file that no longer exists.
> The overall roadmap has been deleted.

- lerna.json
Reverted MDC Web version number change happened in PR #4750
> chore: Revert the MDC Web version number in lerna.json

- test/screenshot/golden.json
continues https://github.com/material-components/material-components-web/pull/4824
> chore: Updated golden screenshot after Win Chrome browser update

- packages/mdc-textfield/_mixins.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-textfield/classes/invalid-disabled.html
- test/screenshot/spec/mdc-textfield/fixture.js
> fix(text-field): Fix asterisk color of text field when input is invalid and disabled 

- packages/mdc-data-table/README.md
- test/screenshot/spec/mdc-data-table/classes/baseline-checkbox.html
- test/screenshot/spec/mdc-data-table/classes/baseline.html
- test/screenshot/spec/mdc-data-table/mixins/fill-color.html
> fix(data-table): Updated examples with aria tags

- packages/mdc-drawer/component.ts
- packages/mdc-icon-button/constants.ts
- packages/mdc-icon-button/foundation.ts
- packages/mdc-linear-progress/constants.ts
- packages/mdc-linear-progress/foundation.ts
- packages/mdc-list/component.ts
- packages/mdc-list/constants.ts
- packages/mdc-list/foundation.ts
- packages/mdc-top-app-bar/component.ts
- packages/mdc-top-app-bar/constants.ts
- packages/mdc-top-app-bar/fixed/foundation.ts
- packages/mdc-top-app-bar/short/foundation.ts
- test/unit/mdc-drawer/mdc-drawer.test.js
- test/unit/mdc-icon-button/foundation.test.js
- test/unit/mdc-linear-progress/foundation.test.js
- test/unit/mdc-list/foundation.test.js
- test/unit/mdc-list/mdc-list.test.js
- test/unit/mdc-select/mdc-select-enhanced.test.js
- test/unit/mdc-top-app-bar/fixed.foundation.test.js
- test/unit/mdc-top-app-bar/mdc-top-app-bar.test.js
- test/unit/mdc-top-app-bar/short.foundation.test.js
related to https://github.com/material-components/material-components-web-react/issues/827 & #4761
> fix: delete deprecated & refactor constant

- .github/semantic.yml
See https://github.com/probot/semantic-pull-requests
> chore: Added config file for semantic PR bot

- package-lock.json
- package.json
related: https://github.com/material-components/material-components-web/issues/4842
> chore: remove webpack-dev-server from package.json

- scripts/check-pkg-for-release.js
fixes `npm run test:dependency`
> fix(infrastructure): update check-pkg-for-release.js

- package-lock.json
- packages/mdc-data-table/_mixins.scss
- packages/mdc-data-table/component.ts
- packages/mdc-data-table/foundation.ts
- packages/mdc-data-table/package-lock.json
- packages/mdc-data-table/package.json
- test/screenshot/golden.json
- test/screenshot/spec/mdc-data-table/classes/baseline-checkbox.html
- test/unit/mdc-data-table/mdc-data-table.test.js
* Added `.destroy()` method to data table component.
* Remove overriding touch dimension of row checkbox.
* Removed testing with mocks in data table component test.
Refs #4591
> feat(data-table): Added .destroy() method to data-table component

- packages/mdc-data-table/README.md
- packages/mdc-data-table/_mixins.scss
- test/scss/_feature-targeting-test.scss
> feat(data-table): Update all mixins to add feature targeting

- packages/mdc-data-table/README.md
> docs(data-table): Added demo link to data table README

- packages/mdc-data-table/README.md
> docs(data-table): Updated data table README example for checked class

- packages/mdc-chips/README.md
- packages/mdc-chips/_mixins.scss
Added remainder of the changes that were needed to move ripple element to be internal to the chip.
> refactor(chip): ripple inner element fixup

- packages/mdc-data-table/README.md
- packages/mdc-data-table/_mixins.scss
- packages/mdc-data-table/foundation.ts
- test/screenshot/golden.json
- test/screenshot/spec/mdc-data-table/classes/baseline-checkbox.html
- test/screenshot/spec/mdc-data-table/classes/baseline.html
* Header cell title is now aligned along with numeric data cell.
* Fixed few minor RTL bugs related to numeric cells.
* Fixed minor checkbox issue where it flash when it changes from indeterminate to unchecked.
Fixes #4914
> fix(data-table): Fixed alignment of header cell title for numeric data

- packages/mdc-radio/README.md
- packages/mdc-radio/_mixins.scss
- test/screenshot/spec/mdc-radio/classes/baseline.html
- test/screenshot/spec/mdc-radio/mixins/mixins.html
BREAKING CHANGE: Ripple has been moved to a child element. See readme for updates.
> feat(radio): Move ripple to child element

- packages/mdc-linear-progress/mdc-linear-progress.scss
> fix(linear-progress): stop animation when closed

- packages/mdc-data-table/_mixins.scss
- test/screenshot/golden.json
- test/screenshot/spec/mdc-data-table/classes/baseline-full-width.html
- test/screenshot/spec/mdc-data-table/classes/baseline-with-buttons.html
- test/screenshot/spec/mdc-data-table/fixture.scss
* Smooth scroll for iOS browser
* Make `<table>` full-width of its container in Firefox / iOS
* Show ellipsis on text overflow in table cell
* Set `table-layout: fixed` for table layout with custom width.
> fix(data-table): Minor fixes for data table layout

- .travis.yml
- karma.conf.js
- package.json
* Updated node_js version from v8 to v10 on travis.
* Replaced dots reporter with progress for karma runner.
* Set webpack verbose level to minimal to reduce noise.
> chore: Updated node_js version from v8 => v10 on travis

- docs/importing-js.md
Still getting issues saying that the components are too hard to get started with. I know when I started I didn't know that `Global` meant for use with the CDN version. So hopefully this helps a little bit.
(Part of the feedback from #5143)
> docs: Update Importing JS README to include CDN

- packages/mdc-tab-scroller/_mixins.scss
- packages/mdc-tab-scroller/_variables.scss
> feat(tab-scroller): Variable for scroll transition time

- packages/mdc-linear-progress/foundation.ts
- test/unit/mdc-linear-progress/foundation.test.js
> fix(linear-progress): Restore buffer after determinate is toggled.

- packages/mdc-tab-scroller/README.md
- packages/mdc-tab-scroller/_mixins.scss
> feat(tab-scroller): Mixin for scroll transition

- .github/workflows/lint.yml
- .travis.yml
- scripts/travis-env-vars.sh
Moved MDC Lint CI from Travis to shiny new GitHub Action. All other tests will eventually be moved to GitHub Action.
> chore: New GitHub Action for MDC Lint

- scripts/canary-release.sh
See https://github.com/lerna/lerna/tree/master/commands/version#--exact for explanation.
Fixes #5181
> chore: Update dependencies to be exact in canary release

- docs/framework-wrappers.md
- packages/mdc-menu-surface/foundation.ts
- packages/mdc-menu-surface/types.ts
Allow any type during TS migration.
> refactor(menu-surface): Allow any type during migration

- packages/mdc-density/README.md
See [Preview](https://github.com/material-components/material-components-web/blob/6aee042e15b53f3bd3908281889dd8b6c13435e7/packages/mdc-density/README.md) here.
> docs(density): Updated density docs to add more info

- packages/mdc-fab/_mixins.scss
Fix for bug introduced in PR #4997
> fix(fab): Add overflow: hidden; to ripple target to fix bounded ripple.

- packages/mdc-menu-surface/foundation.ts
- packages/mdc-menu-surface/types.ts
Reverts material-components/material-components-web#5201
No longer necesssary per internal convo
> refactor(menu-surface): Revert "refactor(menu-surface): Allow any type during migration"

- packages/mdc-density/README.md
See [Preview](https://github.com/material-components/material-components-web/blob/119ac4062323fca7b0a44e28b56300bda4446170/packages/mdc-density/README.md) here.
> docs(density): Add sass mixin links to density page

- packages/mdc-list/README.md
> docs(list): update list README to remove getListItemIndex

- packages/mdc-fab/package.json
> fix(fab): Add missing dep to fab package.json.

- packages/mdc-touch-target/README.md
> chore(touchtarget): Fixed typo in README.md

- packages/mdc-layout-grid/mdc-layout-grid.scss
- packages/mdc-select/README.md
- packages/mdc-select/foundation.ts
- packages/mdc-textfield/_mixins.scss
- test/unit/mdc-select/foundation.test.js
Reverts material-components/material-components-web#5255
> revert: fix(select): Do not fire change event on programmatic change

- packages/mdc-fab/_mixins.scss
- packages/mdc-menu/_mixins.scss
> chore: Project import generated by Copybara.

- packages/mdc-menu-surface/README.md
> docs(menu-surface): Update docs to latest API

- packages/mdc-switch/README.md
- packages/mdc-switch/_mixins.scss
- test/screenshot/spec/mdc-switch/classes/baseline.html
- test/screenshot/spec/mdc-switch/mixins/density.html
- test/screenshot/spec/mdc-switch/mixins/thumb-color.html
- test/screenshot/spec/mdc-switch/mixins/track-color.html
Move switch native control out of thumb element and into track element.
BREAKING CHANGE: Switch DOM structure has changed. See switch README for details
> feat(switch): Restructure DOM

- packages/mdc-switch/_mixins.scss
Reverts material-components/material-components-web#5281
> feat(switch): Rollback #5281

- test/unit/mdc-data-table/mdc-data-table.test.js
Makes it a bit easier to use the karma debug page and see what's failing/run a single test.
> test(data-table): don't clear karma html page when debugging

- packages/mdc-chips/chip/test/foundation.test.ts
> chore: Remove white-space changes from chip foundation test

- packages/mdc-button/_mixins.scss
- packages/mdc-card/_mixins.scss
- packages/mdc-checkbox/_mixins.scss
- packages/mdc-chips/_mixins.scss
- packages/mdc-dialog/_mixins.scss
- packages/mdc-fab/_mixins.scss
- packages/mdc-icon-button/_mixins.scss
- packages/mdc-list/_mixins.scss
- packages/mdc-menu/_mixins.scss
- packages/mdc-radio/_mixins.scss
- packages/mdc-switch/_mixins.scss
- packages/mdc-tab/_mixins.scss
Adding `// COPYBARA_COMMENT_THIS_LINE` marker for Copybara transform to comment any line in Sass files.
> chore: Add copybara comment lines for transforms

- packages/mdc-checkbox/test/component.test.ts
- packages/mdc-chips/chip-set/test/component.test.ts
- packages/mdc-chips/chip/test/component.test.ts
- packages/mdc-list/test/component.test.ts
- packages/mdc-tab-bar/test/component.test.ts
- packages/mdc-tab-scroller/test/component.test.ts
- packages/mdc-tab/test/component.test.ts
> test(infra): Use createMockFoundation helper.

- .stylelintrc.yaml
- packages/mdc-checkbox/_variables.scss
- packages/mdc-drawer/_mixins.scss
- packages/mdc-grid-list/_mixins.scss
- packages/mdc-icon-button/_mixins.scss
- packages/mdc-layout-grid/_mixins.scss
- packages/mdc-select/_mixins.scss
- packages/mdc-slider/_mixins.scss
- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/_variables.scss
- test/screenshot/spec/fixture.scss
Also updated Sass files to fix lint errors.
cl/288965884
> chore: Stylelint rules to keep it in sync with internal

- packages/mdc-floating-label/component.ts
- packages/mdc-textfield/_mixins.scss
- packages/mdc-textfield/component.ts
> fix(textfield): prevent placeholder styles from collapsing with minifiers

- package-lock.json
Updated package-lock.json file to sync with package.json updates in https://github.com/material-components/material-components-web/pull/5453
> chore: Updated package-lock.json file after npm i

- karma.conf.js
- packages/mdc-auto-init/test/mdc-auto-init.test.ts
- packages/mdc-button/test/mdc-button.scss.test.ts
- testing/featuretargeting/index.ts
> chore: Import indentation changes

- packages/mdc-slider/foundation.ts
- packages/mdc-slider/test/foundation-general-events.test.ts
- packages/mdc-slider/test/foundation-pointer-events.test.ts
> fix(slider): Fix for slider on an absolute positioned parent element

- packages/mdc-switch/component.ts
> fix(switch): fix strict generic checks

- packages/mdc-data-table/README.md
> Fix data table docs.

- packages/mdc-textfield/_mixins.scss
> fix(textfield): outlined trailing icon's position

- testing/helpers/foundation.ts
> test: Helper to get foundation methods, including superclasses

- packages/mdc-card/README.md
- packages/mdc-dialog/README.md
- packages/mdc-snackbar/README.md
> docs(card): update action buttons to v4

- packages/mdc-dom/README.md
- packages/mdc-dom/announce.ts
- packages/mdc-dom/test/announce.test.ts
Provide an announcer utility for verbalizing messages to screen readers via aria-live regions
> feat(dom): Create announcer utility

- packages/mdc-select/mdc-select.scss
- packages/mdc-textfield/mdc-text-field.scss
> chore: Add copybara comment lines for transformation

- packages/mdc-textfield/_mixins.scss
> fix(textfield): use correct disabled colors for IE11 high contrast

- packages/mdc-progress-indicator/package.json
> fix(progress-indicator): Remove unnecessary fields from package.json

- packages/mdc-button/_mixins.scss
Testing Copybara GitHub to Piper setup.
> docs: Add SassDoc to button mixin

- .github/workflows/release.yml
- lerna.json
Also updated `lerna.json` to trigger release GitHub action.
> chore: Fix release script

- packages/mdc-layout-grid/_variables.scss
Fix for #4433 with Github actions now running checks (old #4901)
> fix(layout-grid): Desktop view with small window showing 8 columns instead of 4

- packages/mdc-base/_mixins.scss
- packages/mdc-typography/_functions.scss
Refactor @use position after comments on Sass files.
> refactor: @use position

- package-lock.json
- package.json
Fix NPM dependencies vulnerabilities.
> build(deps): bump lerna version to 3.20.2 after npm audit fix

- packages/mdc-switch/_mixins.scss
> feat(switch): support customizable track border color

- packages/mdc-slider/_mixins.scss
- packages/mdc-slider/test/foundation-general-events.test.ts
- packages/mdc-slider/test/foundation.test.ts
style(slider): Use shorter relative path in test.
> style(slider): Use shorter relative path in test.

- .stylelintrc.yaml
Imported sasslint rules to be in sync with internal version.
> chore: import sasslint rules

- CODE_OF_CONDUCT.md
See [preview](https://github.com/material-components/material-components-web/blob/334926f5c92245daab6f5546f547929f18f22a79/CODE_OF_CONDUCT.md).
> chore: Add Code of Conduct document

- testing/dom/events.ts
test(infra): Add createMouseEvent helper function.
> test(infra): Add createMouseEvent helper function.

- packages/mdc-chips/chip-set/foundation.ts
- packages/mdc-chips/chip-set/test/component.test.ts
- packages/mdc-chips/chip-set/test/foundation.test.ts
Fixed crash when the only chip item is removed.
Fixes #6160
> fix(chip-set): crash when only item is removed

- README.md
> docs(textfield): update homepage README to use modules

- packages/mdc-segmented-button/segment/component.ts
- packages/mdc-segmented-button/segmented-button/component.ts
Add method outlines for segment and segmented-button components
> feat(segmented-button): Add component outlines

- packages/material-components-web/material-components-web.scss
- packages/mdc-slider/component.ts
- packages/mdc-slider/foundation.ts
- packages/mdc-slider/package.json
chore(slider): Add slider package.json, fix slider build errors.
> chore(slider): Add slider package.json, fix slider build errors.

- testing/helpers/setup.ts
test: Add ES polyfills to external tests, so we can use methods like Array#from, Object#assign, etc.
> test: Add ES polyfills to external tests, so we can use methods like Array#from, Object#assign, etc.

- packages/mdc-slider/test/component.test.ts
- packages/mdc-slider/test/feature-targeting-any.test.scss
- packages/mdc-slider/test/foundation.test.ts
- packages/mdc-slider/test/mdc-slider.scss.test.ts
> test(slider): Export tests.

- packages/mdc-segmented-button/package.json
- packages/mdc-segmented-button/segment/adapter.ts
- packages/mdc-segmented-button/segment/component.ts
- packages/mdc-segmented-button/segment/constants.ts
- packages/mdc-segmented-button/segment/foundation.ts
- packages/mdc-segmented-button/segment/test/component.test.ts
- packages/mdc-segmented-button/segment/test/constants.ts
- packages/mdc-segmented-button/segment/test/foundation.test.ts
- packages/mdc-segmented-button/segmented-button/adapter.ts
- packages/mdc-segmented-button/segmented-button/component.ts
- packages/mdc-segmented-button/segmented-button/constants.ts
- packages/mdc-segmented-button/segmented-button/foundation.ts
- packages/mdc-segmented-button/segmented-button/index.ts
- packages/mdc-segmented-button/segmented-button/test/component.test.ts
- packages/mdc-segmented-button/segmented-button/test/constants.ts
- packages/mdc-segmented-button/segmented-button/test/foundation.test.ts
Implement functionality of segment and segmented-button components
> feat(segmented-button): Implement components

- packages/mdc-textfield/character-counter/README.md
`mdc-text-field-character-disabled-counter-color($color)` => `mdc-text-field-disabled-character-counter-color($color)`
> docs(textfield): fix class name

- packages/mdc-segmented-button/README.md
Add README documentation for segmented-button
> docs(segmented-button): Add README.md

- packages/mdc-data-table/component.ts
- packages/mdc-data-table/test/component.test.ts
fix(data-table): Check if data table has checkboxes on destroy
Fix #6385
> fix(data-table): Check if data table has checkboxes on destroy

- packages/mdc-segmented-button/segmented-button/component.ts
Unselect extra initial selected segments if singleSelect and select first segment if none already selected.
> feat(segmented-button): Add select validations for singleSelect

- packages/mdc-dialog/foundation.ts
- packages/mdc-dialog/test/foundation.test.ts
Fixes #6429.
If this isn't the right solution, please do let me know and ill update or abandon.
> fix(dialog): support deep textareas

- package-lock.json
- package.json
- tsconfig-base.json
- tsconfig-node.json
this in preparation for cl/329609444
> build: add google-recommended resizeObserver types

- packages/mdc-segmented-button/README.md
This file was reverted in Copybara sync.
> docs: Add README docs for segmented button

- scripts/check-pkg-for-release.js
- scripts/webpack/js-bundle-factory.js
> build: Bundle Segmented Button JS

- .github/workflows/test.yml
GitHub Action test to check if PR title follows [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format.
> build: Add Action to check conventional commit

- packages/mdc-button/README.md
> docs(button): replace <div /> with <span />

- packages/mdc-list/foundation.ts
> fix: Execute getListItemCount() only once

- CONTRIBUTING.md
> chore: remove demo links

- scripts/webpack/css-bundle-factory.js
> fix(switch): distribute correct css

- packages/material-components-web/package.json
- packages/mdc-focus-ring/_focus-ring.scss
- packages/mdc-focus-ring/package.json
chore: Export focusring package.
> chore: Export focusring package.

- karma.conf.js
It's more flaky than it's worth...
> chore: remove IE11 from SauceLabs test suite
