material-components/material-components-web

demos/icon-toggle.html

---
Minor cleanups and fixes as well
[ci skip]

chore(demos): Add additional icon toggle examples

---

framework-examples/react/package.json
framework-examples/react/src/Checkbox.js
framework-examples/react/src/FormField.js
framework-examples/react/webpack.config.js

- Fix import statements
- Add NPM packages as dependencies
- Remove reliance on sass loader and all sass-related features. Use
built CSS instead
- Clean up package.json
Resolves #107
[ci skip]

fix(framework-examples): Fix React example

---

.stylelintrc.yaml
package.json
packages/mdc-select/mdc-select.scss

- Set max-width of component to 100% - the size of the padding added to
accomodate the drop-down arrow
- Truncate overflowing selected text, similar to a normal <select>
element
- Adds "ignore: local" for scss/dollar-variable-pattern to stylelint
config so local Sass vars don't have to be prefixed
- Disallows the legacy "md-" prefix that was allowed in our stylelint
config
[Delivers #136281135]
Resolves #112

fix(select): Prevent overflow on smaller screens

---

packages/mdc-menu/README.md

There was a small error in the JS snippet

Fix typo in mdc-menu

---

CONTRIBUTING.md

Addresses the lack of documentation on how to find an issue to work on as a member of the MDC Web community.

docs(community-guidelines): how to find work as a member of the community

---

scripts/determine-pkg-versions.js

determine-pkg-versions was erroring because it was assumes the `name`
key in each component's package.json to be `mdc-*`, rather than
`@material/*`. This commit fixes that issue.
Additionally, it allows _all_ commit types to constitute at least a
patch version bump. For example, a docs change, chore, or non-breaking
refactor to a component could all be considered worthy of a patch
version update. This ensures that our latest and greatest code and docs
are available on npm whenever we release.
[ci skip]

fix(scripts): Update determine-pkg-versions to use new pkg names

---

packages/mdc-typography/README.md

docs(typography): Fix `mdc-typography` mixin name in docs.

---

packages/mdc-ripple/README.md

docs(mdc-ripple): clarify language under JS implementation instructions

---

packages/mdc-ripple/README.md

The docs said that the ripple attaches an `mdc-ripple` class to the
element, when what it actually attaches is `mdc-ripple-upgraded`.
[ci skip]

docs(ripple): Fix instructions for adding ripple sass/css

---

webpack.config.js

This fixes browser compatibility issues *(caused by ES moudle syntax)* by letting `@material/animation/dist/mdc.animation` be used instead of `@material/animation`.
If this gets merged, please release a new minor version of the `@material/animation` package.

chore(build): Transpile JS source of mdc-animation

---

demos/button.html
demos/fab.html
packages/mdc-button/README.md
packages/mdc-button/mdc-button.scss
packages/mdc-button/package.json
packages/mdc-fab/README.md
packages/mdc-fab/mdc-fab.scss
packages/mdc-fab/package.json

- Add ink ripple support to standard buttons
- Add ink ripple support to FABs
Note: This PR should be **rebased and merged**, not squashed and merged. This is because it contains two separate commits for FABs and Buttons.

Feat: Add ripples to buttons and FABs

---

.gitattributes
demos/list.html
packages/mdc-list/README.md
packages/mdc-list/mdc-list.scss
packages/mdc-list/package.json

- Ensure mdc-list-item looks correct when applied to an anchor tag
- Add ripple support to mdc-list-item
- Ensure that list items with ripples show the ripple across the list
elemeng
- Tech debt: add gitattributes telling github not to include anything in
demos/, docs/, or framework-examples/ when computing source code
language statistics
Part of #20

feat(list): Add interactivity and ink ripple support to mdc-list-item

---

.gitattributes
packages/mdc-icon-toggle/README.md

`setDisabled` was named `toggle`.
Also fix `.gitattributes` file to properly track language statistics for
this repo.
Resolves #200
[ci skip]

docs(icon-toggle): Fix mis-named adapter API method in README

---

.travis.yml

- Clean up legacy notifications config
This is a temporary workaround for our CI until #143 and its subsequent
tasks are completed.

chore(infrastructure): Disable SauceLabs temporarily on TravisCI

---

packages/mdc-auto-init/README.md

Changes a markdown code highlighting in the documentation of the auto-init component from `js` to `html`.

fix(auto-init): Change markdown code highlighting

---

packages/mdc-drawer/README.md

Simply removes superfluous closing anchor tags in the documentation of the drawer component.

fix(demos): Remove superfluous anchor tags for drawer demo

---

docs/authoring-components.md

docs(authoring-components): Link to MDC-Web Codepen prototyping template

---

packages/mdc-checkbox/index.js
test/unit/mdc-checkbox/mdc-checkbox.test.js

Fixes issue where wrong event type was being used within
`getCorrectEventName` in `register`/`deregisterAnimationEndHandler`
adapter methods in vanilla component. Discovered while working on #205.

fix(checkbox): Use correct animation end event type in adapter

---

demos/index.html
demos/switch.html
packages/material-components-web/material-components-web.scss
packages/material-components-web/package.json
packages/mdc-snackbar/package.json
packages/mdc-switch/README.md
packages/mdc-switch/_mixins.scss
packages/mdc-switch/_variables.scss
packages/mdc-switch/mdc-switch.scss
packages/mdc-switch/package.json
webpack.config.js

feat(switch): Implement css switch component

---

package.json

Switches from ghooks to husky. Fixes #229.
- Removed the `ghooks` config section from `package.json`.
- Added a `commitmsg` script entry to `package.json`.
- Uninstalled `ghooks`.
- Installed `husky`.
- The `husky` installation automatically converts the existing git hooks from `ghooks` hooks to their `husky` equivalents.

chore(hooks): Upgrade from ghooks to husky

---

packages/mdc-checkbox/index.js
test/unit/mdc-checkbox/mdc-checkbox.test.js

Fixes an issue where the ripple was not activated on keyDown within the
checkbox component.

fix(checkbox): Ensure ripple is activated on keydown

---

docs/authoring-components.md

In our code example, the vanilla and conceptually modified component implementation both have the attribute named `toggle` instead of `toggle_`. 
The previous one is causing a bug that the button is not toggle its color since `this.toggle_ ` always return `undefined`. The latter one, which is not a runnable code snippet, is a continuation of this previous code snippet, and thus it is better to get them aligned.

docs(authoring-components): Fixed bugs in example code (#239)

---

demos/select.html

Missing space before the label attribute was causing the browser to complain

Fix missing whitespace in section demo

---

docs/authoring-components.md

I updated authoring component's new component checklist for the following points:
- Modify dependency in `js-component` instead of `js-all`
- Add dependency in `css` module
- Add dependency in `package.json`

docs(authoring-component): Update checklist when adding new component.

---

CHANGELOG.md

- Fixes the comparison links between versions. (Depends on #271)
- Removed the `fab` breaking change from `0.3.0` as it was already mentioned with `0.2.0`
- Tweaked the code highlighting markdown for the `fab` breaking change example, as my markdown editor (VS Code) doesn't like that style in its preview window.

docs(changelog): Fix format and remove dupe'd item

---

CONTRIBUTING.md
docs/authoring-components.md

- Update CONTRIBUTING.md to revamp releasing section with more thorough
and up-to-date information on how to properly release MDC-Web.
- Update authoring components guide to outline exactly what a new
component's package.json should look like for a successful release.

docs: Update release notes and authoring new components for release

---

packages/mdc-icon-toggle/package.json

The `icon-toggle` package.json file has the `main` property set twice with identical values. This removes one of them.

fix(icon-toggle): Remove duplicate "main"

---

packages/mdc-ripple/README.md
packages/mdc-ripple/foundation.js
packages/mdc-ripple/index.js
test/unit/mdc-ripple/foundation-activation.test.js
test/unit/mdc-ripple/foundation-deactivation.test.js
test/unit/mdc-ripple/mdc-ripple.test.js

feat(ripple): Add programmatic ripple activation/deactivation.

---

packages/mdc-base/component.js
test/unit/mdc-base/component.test.js

fix(base): Ensure this.root_ is available within getDefaultFoundation()

---

package.json
packages/mdc-select/mdc-select.scss
webpack.config.js

- Fix `@include` directive for disabled styles that was used within the
context of a multiple selector, which was emitting incorrect styles.
- Fix our webpack config to emit our stylesheets correctly, while also
removing LoaderOptions which is apparently deprecated
- (tech debt) Update stylelint-scss and postcss-loader
- (tech debt) Remove prod dependency on stylelint-scss which shouldn't
have been there in the first place
Fixes #276

fix(select): Ensure disabled styles render correctly

---

packages/mdc-checkbox/constants.js
packages/mdc-checkbox/foundation.js
packages/mdc-checkbox/mdc-checkbox.scss
test/unit/mdc-checkbox/foundation.test.js

- Adds a mdc-checkbox--upgraded mod class which is attached by the
foundation when a JS checkbox is used.
- Disables all transitions when the animation classes are used. Fixes an
issue in Safari where the the paint/compositing looked janky/broken
due to animations and transitions conflicting with one another.
- (tech debt) Removed template strings from cssClasses object. This will
be required in order for our internal infra to work correctly.
Fixes #205

fix(checkbox): Disable transitions when using mdc-checkbox-anim* classes

---

demos/checkbox.html
demos/radio.html
packages/material-components-web/index.js
packages/mdc-checkbox/index.js
packages/mdc-form-field/README.md
packages/mdc-form-field/constants.js
packages/mdc-form-field/foundation.js
packages/mdc-form-field/index.js
packages/mdc-form-field/package.json
packages/mdc-radio/index.js
test/unit/mdc-form-field/foundation.test.js
test/unit/mdc-form-field/mdc-form-field.test.js
webpack.config.js

This PR creates MDCFormField, which manages the runtime relationship
between an input element and its label, enabling label events to
trigger input ripples. Implements #9.

feat(form-field): Make form field labels trigger input ripples.

---

packages/mdc-menu/README.md
packages/mdc-menu/simple/foundation.js
packages/mdc-menu/simple/index.js
test/unit/mdc-menu/simple.foundation.test.js
test/unit/mdc-menu/util.test.js

BREAKING CHANGE: adapters have to implement the new `getAccurateTime`
method.
Removes flakiness from tests as a side-effect.

feat(menu): Move current time retrieval to adapter.

---

.travis.yml
karma.conf.js
test/unit/mdc-form-field/mdc-form-field.test.js

This PR re-enables Sauce Labs for a number of configurations. Certain configurations are currently presenting issues and are disabled while the causes are investigated. If possible, they will be added later.
In the meantime, this will reenable cross-browser testing.

chore(infrastructure): Re-enable SauceLabs

---

demos/select.html
packages/mdc-select/README.md
packages/mdc-select/foundation.js
packages/mdc-select/index.js
test/unit/helpers/foundation.js
test/unit/mdc-select/foundation.test.js
test/unit/mdc-select/mdc-select.test.js

- Add `value` property to JS component to retrieve the value of the
currently selected option
- Add `getValue()` method to foundation in order to drive `value`
property in component.
- Add `getValueForOptionAtIndex` foundation method.
- Enhance `verifyDefaultAdapter` foundation test helper by making it so
that when checking for correct adapter methods, the method names don't
have to be in the same order as they are defined on the object.
BREAKING CHANGE: **New adapter method:** `getValueForOptionAtIndex(index: string) => string`
should return the "value" of the option at the given index. Please add
this method to your adapter implementations.
Resolves #232

feat(select): Add value retrieval mechanisms to JS API

---

packages/mdc-textfield/foundation.js
test/unit/mdc-textfield/foundation.test.js

Also change cssClasses getter to use static strings rather than
templates, which will be required for future internal interop.
Fixes #300

fix(textfield): Adjust labels when initializing pre-filled textfields

---

framework-examples/vue/src/v-mdc-checkbox/Checkbox.vue
framework-examples/vue/src/v-mdc-snackbar/Snackbar.vue

In vuejs 2.2 parsing raise template error if html element has no matching end tag

fix template syntax error

---

packages/mdc-ripple/_keyframes.scss
packages/mdc-ripple/_mixins.scss

From #361:
While running it through `postcss-custom-properties`  I fixed all warnings except for the `Custom property ignored: not scoped to the top-level :root element` ones. 
Passing `warnings: false` to `postcss-custom-properties` suppresses that specific warning though, resulting in a warning free build.

fix(ripple): Provide fallbacks for all custom properties

---

demos/select.html

Made "Dark Theme" checkbox selectable by clicking it's label in "select.html" demo

docs(select): Fix 'for' attribute of a label in demo

---

demos/checkbox.html

The "Make Indeterminate" button in the JS checkbox demo is currently not
working because the "indeterminate" property is being set on the
checkbox _root_ element, rather than the native instance. This commit
fixes that.
Skipping TravisCI as this is a change to the demo only.
[ci skip]

docs(checkbox): Fix indeterminate button in JS checkbox demo

---

packages/mdc-checkbox/mdc-checkbox.scss
packages/mdc-checkbox/package.json

Fixes #375
--
Note that I removed `mdc-checkbox-outer-box` because it was only being used on the background element.

fix(checkbox): Ensure correct positioning in RTL context

---

lerna.json
scripts/lib/get-updated-pkgs.js

This removing the deprecated message when we run `lerna publish`.

fix(infrastructure): Update publishConfig.ignore to commands.publish ignore.

---

scripts/check-pkg-for-release.js
scripts/pre-release.sh

It seems that every time we try to release, _something_ goes wrong. This
commit adds sanity checks to our pre-release scripts to try and
minimize surprises:
- Ensures that you are logged in on npm as a material org member
- Ensures that you have SSH access to GitHub (note that checking if you
can push to MDC-Web is more involved, and requires API auth. This
should be a simple enough check)
- Ensures that you have gcloud configured properly to deploy our demo site
- Ensures that all new packages have the correct publishConfig specified
in their package.json files.

chore(infrastructure): Add sanity checks to pre-release scripts

---

packages/mdc-button/mdc-button.scss
packages/mdc-fab/mdc-fab.scss

**_NOTE: THIS PR SHOULD BE REBASED AND MERGED, NOT SQUASHED_**
- Fixes interfering tap highlights for buttons and FABs with ripples on mobile safari.
- Fixes `::before` styling in FAB which was clobbering the ripple's graceful degradation styles.
See commits for more info.

Fix buttons and FABs for gracefully degraded ripples

---

test/unit/mdc-drawer/util.test.js
test/unit/mdc-menu/simple.foundation.test.js

These particular tests seem to fluctuate on CodeCov between being
covered and not being covered, which can lead to false negatives and
strange reporting on PRs that do not touch these files. This commit adds
tests that explicitly cover these cases.

chore: Fix codecov flakes

---

packages/mdc-ripple/_keyframes.scss
packages/mdc-ripple/_mixins.scss
packages/mdc-ripple/constants.js
packages/mdc-ripple/foundation.js
packages/mdc-ripple/package.json
packages/mdc-ripple/util.js
test/unit/mdc-checkbox/mdc-checkbox.test.js
test/unit/mdc-ripple/foundation-activation.test.js
test/unit/mdc-ripple/foundation-deactivation.test.js
test/unit/mdc-ripple/foundation-general-events.test.js
test/unit/mdc-ripple/foundation.test.js
test/unit/mdc-ripple/helpers.js
test/unit/mdc-ripple/util.test.js

Background
===
When the ripple was originally designed from a motion perspective,
bounded and unbounded activation/deactivation used two different
animation styles, distinct from one another.
The UX updates to the ripple remove this distinction of bounded vs.
unbounded solely with regard to how the ripple animates in and out.
There is still a distinction between bounded vs. unbounded, but we no
longer have to account for this when animating the ripple. Thus, there
are no API changes; only UX changes.
Changes
===
- Implement UX changes for "tap" + "tap and hold" interactions
- Remove all references of "bounded" vs. "unbounded" from
activation/deactivation code
Resolves #190

feat(ripple): Implement subset of improved interaction response guidelines

---

demos/toolbar/default-toolbar.html
demos/toolbar/fixed-top-toolbar.html
packages/mdc-toolbar/README.md
packages/mdc-toolbar/mdc-toolbar.scss

Background
===
When toolbar was originally implemented, it was design to be a single
row toolbar. However, it turns out that we need one higher level
wrapper to group the current toolbar and future tabs. We carefully
balanced between introducing a new "appbar" concept v.s. extending the
functionality of existing toolbar to support multiple row, we decided
to go for the latter without introducing a new component.
Changes
===
- Implement multiple row toolbar
- Updated README and demo
BREAKING CHANGE: All existing toolbar need to add `<div class="mdc-toolbar__row">`
to properly align its contents.

feat(toolbar): Improve toolbar to support multiple row.

---

packages/mdc-select/README.md

- Re-arrange API docs to match the order that adapter functions are
declared within `defaultAdapter`.
Noticed after responding to #437
[ci skip]

docs(select): Add notifyChange adapter API docs

---

packages/mdc-theme/README.md

docs(theme): Clarify the use of mdc-theme-dark mixins/classes

---

packages/mdc-select/mdc-select.scss

Some elements were showing up over the select menu's pop out. e.g.
radio-buttons. To demonstrate the problem, I copied demos/radio.html:72-94 into
demos/select.html just after line 74. This puts a radio button right
where the select menu pops up. When running the demo without the fix,
you can see the radio button over the select menu. With the z-index fix,
the menu appropriately pops up over the radio-button.
Fixes [Issue 432](https://github.com/material-components/material-components-web/issues/432)

fix(select): Fixing bug with select menu z-index

---

packages/mdc-list/mdc-list.scss

Resolves #463, Update interactive list's with ripple-upgrade to be narrower. Padding of list items is 16 + 16 = 32px, so width of list items should be container's width - 32px.

fix(list): Update interactive list's with ripple-upgrade to be narrower

---

demos/list.html
packages/mdc-list/README.md

As far as I can make out from the CSS, there is no `mdc-list-item__text__primary` defined and I assume this should simply be `mdc-list-item__text`. The second line should have the class `mdc-list-item__text__secondary`

docs(list): fix error in two line list item example in Readme

---

demos/dialog.html
karma.conf.js
packages/mdc-dialog/README.md
packages/mdc-dialog/constants.js
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
packages/mdc-dialog/package.json
packages/mdc-dialog/util.js
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-dialog/mdc-dialog.test.js
test/unit/mdc-dialog/util.test.js

- Remove all focus trapping logic within the dialog foundation,
replacing it with adapter methods set up to handle focus trapping.
- Add [focus-trap](https://npmjs.com/focus-trap) as a dependency and use
it for implementing the adapter methods at the component level
- Add a util method for easily creating properly configured focus-trap
instances that framework components can use when implementing their
adapters.
- Remove use of aria-hidden and replace with visibility styles so that
tab-focusing works correctly when dialog is hidden.
- [techdebt] Remove all unnecessary adapter API methods and dead code
- [techdebt] Make grammatical corrections in README
- [techdebt] Remove unneeded passive event listener logic for dialog handlers
- [demos] Fix ripples incorrectly appearing in buttons …

fix(dialog): Handle focus trapping correctly

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

The MDC-Web Core Team has recently introduced the concept of
"Engineering Outlines" into our process of developing component. These
function as more lightweight versions of "design documents", where we
can get a good sense of how an engineer plans on approaching a component
from an implementation perspective. We've found this practice extremely
useful for us, and have decided to require it as part of developing new
components. This PR adds information on eng outlines being a requirement, as well as where to find the template for them, in our CONTRIBUTING
and issue template docs.

docs: Add eng outline doc info to CONTRIBUTING, Issue Template

---

docs/authoring-components.md
docs/closure-compiler.md
package.json

- Add `docs/closure-compiler.md`, detailing our motivation for using
closure compiler, our conventions, a full example skeleton of a
closurized MDC-Web component, and common closure idioms that may not
be as familiar to those who haven't worked with closure before.
- Update `authoring-components.md` to include information regarding
closure compatibility.
- Amend `authoring-components.md` to specify that
cssClasses/strings/numbers constants must be specified in a
`constants.js` file. While not directly related to closure, we
reference this a lot in our documentation. Thus, it was deemed
appropriate to add as part of this commit.
- Add `closureWhitelist` config key to `package.json`, since it's
referenced in these docs. This will be used for eventual build testing
as we annotate all of our …

docs: Add closure walkthrough + conventions guide

---

package.json

Previously only the invalidate subject line would print, so if you'd written a big meaty comment that failed to validate you'd have to rewrite it.

fix(infrastructure): Print the entire invalid git commit message.

---

packages/mdc-toolbar/README.md
packages/mdc-toolbar/mdc-toolbar.scss

Hey,
I tried to fix the toolbar problem with adding a `flex: 0;` style to the `.mdc-toolbar__section--align-end` class as mentioned in the issue #508.
I added a class `mdc-toolbar__section--shrink-to-fit` that fixes the problem as well as some essential css code. Thanks to @yeelan0319.

Fixed "Title jumps to the next line, out of the toolbar #508"

---

scripts/determine-pkg-versions.js

The reason for version bumping shown in `pre-release.sh` have the following case which it cannot handle properly.
When package version for a component is bumped for its dependency being updated, however, it happens to have one and only one commit msg for `docs(some-component): xxxx`. In the summary table, it will show the reason for this version bump is cased by the documentation update. However, the actual reason this package is selected is because lerna correctly detects its dependency update. 
This used to cause some confusion when we release `0.7.0`.

fix(infrastructure): correct reason why component is shown in summary table.

---

packages/mdc-checkbox/mdc-checkbox.scss
packages/mdc-radio/mdc-radio.scss
packages/mdc-toolbar/mdc-toolbar.scss

Fixing radio box alignment when parent's alignment is not set to left.
Also fixing style linting issues across checkbox, toolbar, and radio
Fixes #486

fix(radio): Center align radio box

---

.eslintrc.yaml
.gitignore
.travis.yml
CONTRIBUTING.md
closure_externs.js
docs/closure-compiler.md
package.json
packages/mdc-animation/index.js
packages/mdc-drawer/slidable/foundation.js
packages/mdc-form-field/foundation.js
packages/mdc-menu/simple/foundation.js
scripts/closure-test.sh
scripts/rewrite-import-statements-for-closure-test.js
test/unit/mdc-animation/mdc-animation.test.js
test/unit/mdc-drawer/slidable.foundation.test.js
test/unit/mdc-menu/simple.foundation.test.js

**This PR should be _Rebased and Merged_, not squashed and merged**
---
- Add scripts/closure-test.sh script to perform compilation tests on all
of our closurized packages.
- Add scripts/rewrite-import-statements-for-closure-test.js to rewrite
all package import statements to be compatible with closure
- Add closure_externs.js file to support third-party module loading by
closure
- Add documentation regarding closure externs to closure-compiler.md
- Update TravisCI configuration to run closure build tests in parallel
with our existing CI scripts.
- Add ignore vars pattern to ESLint unused var config
- Fix all uncaught unused var errors (why they weren't caught before is
quite confusing...)
Resolves #327
NOTE: Tested rewrite import statements logic by hacking
closurization into `mdc-base` …

Closure Test Infrastructure + mdc-animation annotations

---

.stylelintrc.yaml
package.json
packages/mdc-drawer/persistent/mdc-persistent-drawer.scss
packages/mdc-toolbar/mdc-toolbar.scss

* Updated stylelint-order to 0.4.3 latest
* Fixed any files which cause the new lint rule to fail
* Replaced the rule with the above plugin, using the properties-order array to preserve the order of our current properties.
Resolves:
https://github.com/material-components/material-components-web/issues/559

style: Replace stylelint `order/declaration-block-properties-order` rule with `order/properties-order` and update scss to match

---

webpack.config.js

Changes introduced in the most recent version of WDS hardened CORS
access to resources. This however breaks our development model when
using proxies like ngrok to test across devices. Because all of our
assets are publicly available, and our WDS usage is purely transient,
I believe it's safe to disable this.

fix(infrastructure): Disable webpack-dev-server host checking

---

packages/mdc-button/README.md

Just a minor fix for the package links in the MDC button package documentation.

Fix incorrect paths to packages in button documentation

---

packages/mdc-toolbar/README.md

Supposedly this [commit](https://github.com/material-components/material-components-web/commit/c8f70a64661b7c2f1aa31c188506bf0fb9dc8bd5) should have fixed it, but it didn't.

docs(toolbar) Fixed Demo URL 404.

---

packages/mdc-tabs/README.md

The readme of tabs component incorrectly states @material/tab-bar as NPM component name, but it is not available. It is registered under the name @material/tabs.
EDIT: also fixes Dark Mode support class name reference.

docs(tabs): fixes package name in installation command

---

packages/mdc-card/mdc-card.scss

This PR adds a 2px border radius to the card component and sets overflow: hidden; to prevent a contained image from bleeding out over the border.
I did wonder if the 2px border value should be a SCSS variable.
This fixes issue #647

fix(card): Add rounded corners to card component

---

demos/index.html
demos/typography.html

Remove unnecessary CSS rule in Typography and move header into the section block.
Remove unnecessary comment in the index.

Fix misaligned title in Typography Demo

---

packages/mdc-drawer/temporary/mdc-temporary-drawer.scss

This fixes #551, in which closed temporary drawers appear in the middle of the screen when RTL because they still use the `transform` value for LTR.
That was happening because `.mdc-temporary-drawer__drawer` was passed as `$root-selector` to the `mdc-rtl` mixin wrapping the RTL drawer styles, which resulted in this style snippet:
```css
[dir="rtl"] .mdc-temporary-drawer__drawer .mdc-temporary-drawer__drawer,
.mdc-temporary-drawer__drawer[dir="rtl"] .mdc-temporary-drawer__drawer {
-webkit-transform: translateX(107%);
transform: translateX(107%);
-webkit-transform: translateX(calc(100% + 20px));
transform: translateX(calc(100% + 20px));
}
```
That obviously never matches as it's looking for `.mdc-temporary-drawer__drawer` nested inside itself. This drops the `$root-selector` parameter, …

fix(drawer): fix RTL closed position of temporary drawer

---

packages/mdc-ripple/index.js
packages/mdc-ripple/util.js
test/unit/mdc-ripple/util.test.js

perf(ripple): Use passive event listeners on adapter instantiation

---

package.json
scripts/check-imports.js

Will hopefully prevent issues like #650 from occurring in the future.
This doesn't cover SCSS, but at least it narrows the surface area
where mistakes can be made. This also in no way replaces vigilance
while reviewing PRs.
---
_Note to reviewers_: I tested this manually be creating true negatives for all `import` cases (absolute imports, module imports not specified as dep, relative imports outside package root)

chore(infrastructure): Add check imports script as a pretest

---

packages/mdc-dialog/mdc-dialog.scss

This should fix #661 
This is my first PR so let me know if something else is needed. Thanks in advance.

fix(dialog): MDC Dialog does not have 8dp padding between side-by-side buttons

---

.eslintrc.yaml
packages/mdc-checkbox/foundation.js
packages/mdc-drawer/util.js
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-menu/simple.foundation.test.js
test/unit/mdc-ripple/foundation-activation.test.js
test/unit/mdc-ripple/foundation-deactivation.test.js
test/unit/mdc-ripple/foundation.test.js
test/unit/mdc-tabs/mdc-tab-foundation.test.js

It turns out that ESLint has not been enforcing consistent indentation
within our codebase. This PR adds an explicit indentation check to our
ESLint config to ensure that we are using two spaces to indent, and
fixes any files that deviate from this.

style: Add indentation check to ESLint config

---

packages/mdc-list/mdc-list.scss

fix(list): Interactive list items in RTL get pushed to the left

---

packages/mdc-select/README.md

fixes #778
The wrong class name was in the documentation example for Multi Select.

docs(select) Replace mdl-list class with mdc-list in documentation (#778)

---

demos/toolbar/index.html

I was going to try to help with with #598, but it seems that @amsheehan already took care of all the work with #764 :)
This just closes out the last action item instead, adding some docs for the demo page to let people know why their icons aren't showing up when they copy the example code.

docs(toolbar): Add warning that the icons used in the toolbar demos aren't loaded in by default.

---

demos/layout-grid.html
packages/mdc-layout-grid/README.md
packages/mdc-layout-grid/_mixins.scss
packages/mdc-layout-grid/_variables.scss
packages/mdc-layout-grid/mdc-layout-grid.scss

BREAKING CHANGE in css custom properties and sass variables.

feat(layout-grid): parameterize layout grid

---

packages/mdc-drawer/README.md
packages/mdc-drawer/slidable/foundation.js
packages/mdc-drawer/temporary/constants.js
packages/mdc-drawer/temporary/foundation.js
packages/mdc-drawer/temporary/index.js
packages/mdc-drawer/temporary/mdc-temporary-drawer.scss
test/unit/mdc-drawer/mdc-temporary-drawer.test.js
test/unit/mdc-drawer/temporary.foundation.test.js

BREAKING CHANGE: Adapter API for temporary drawers contains two new methods: `addBodyClass` and `removeBodyClass`.
Closes #777
cc @amsheehan

fix(drawer): Page content can be scrolled even if drawer is open

---

packages/mdc-menu/README.md
packages/mdc-menu/index.js

feat(menu): Export util methods from @material/menu

---

scripts/closure-test.sh
scripts/rewrite-decl-statements-for-closure-test.js

- Ensure that all JS src files are recursively picked up when sending
`--js` flag to closure compiler
- Ensure `export ... from ...` statements are covered when rewriting
declaration sources.

fix(infrastructure): Harden closure declaration source rewriting

---

demos/layout-grid.html
packages/mdc-layout-grid/README.md
packages/mdc-layout-grid/_mixins.scss
packages/mdc-layout-grid/_variables.scss
packages/mdc-layout-grid/mdc-layout-grid.scss

feat(layout-grid): Add fixed column width layout grid modifier.

---

packages/mdc-base/README.md
packages/mdc-checkbox/README.md
packages/mdc-list/README.md
packages/mdc-ripple/README.md
packages/mdc-rtl/README.md
packages/mdc-textfield/README.md
packages/mdc-toolbar/README.md

I found a few typos while reading through various parts of the docs.  Figured I'd fix them before I forgot where they were.

docs: Fix various typos

---

packages/mdc-ripple/README.md
packages/mdc-ripple/index.js

[The docs recommend](https://material.io/components/web/catalog/ripples/#using-the-foundation) using certain functions from util when implementing an adapter for the ripple foundation. It is not currently possible to `import { util } from '@material/ripple';`, even though this pattern is [established](https://github.com/material-components/material-components-web/blob/92aab2b2dffaa9d31ce99d68322dcce90dcffc0a/packages/mdc-toolbar/index.js#L23) in `mdc-toolbar`.

feat(ripple): export util from @material/ripple

---

packages/mdc-button/mdc-button.scss

Resolves #819, Raised buttons on dark theme should default to the
primary color, which means their text should be text-primary-on-primary

fix(button): Sets text on raised buttons on dark theme to text-primary-on-primary

---

packages/mdc-toolbar/mdc-toolbar.scss

Without the fix there is a gap when hitting `@media (max-width: 959px) and (orientation: landscape)`:
Because the row height is changed on that breakpoint: 
https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/mdc-toolbar.scss#L48

fix(toolbar): Adjusting sibling elements on mobile landscape

---

packages/mdc-base/component.js
packages/mdc-base/foundation.js

Fixes #767 
- Change `@private` to `@protected`
- Fix optional annotations
- Fix enumeration annotations

fix(base): Fix compiler warnings

---

package.json
packages/mdc-ripple/adapter.js
packages/mdc-ripple/foundation.js
packages/mdc-ripple/index.js
packages/mdc-ripple/util.js

feat(ripple): Annotate mdc-ripple for closure

---

packages/mdc-button/mdc-button.scss
packages/mdc-button/package.json

This is the same code as [the old pull request](https://github.com/material-components/material-components-web/pull/851), but I closed the old one because I needed to sync this up with master again

refactor(button): Remove button's dependency on typography, by specifying letter-spacing

---

packages/mdc-toolbar/mdc-toolbar.scss

fix(toolbar): Toolbar for Desktop should be 24px per guidelines

---

package.json
packages/mdc-checkbox/adapter.js
packages/mdc-checkbox/constants.js
packages/mdc-checkbox/foundation.js
packages/mdc-checkbox/index.js
packages/mdc-ripple/index.js

feat(checkbox): Annotate mdc-checkbox for closure

---

demos/layout-grid.html
packages/mdc-layout-grid/README.md
packages/mdc-layout-grid/mdc-layout-grid.scss

feat(layout-grid): Implement layout grid alignment.

---

package.json

We upgraded it with https://github.com/material-components/material-components-web/pull/905, but it caused tests to fail. (Unclear why these tests did no fail in TravisCI)

fix(infrastructure): Downgrade closure-compiler

---

packages/mdc-elevation/_mixins.scss

If you use https://www.sassmeister.com/ to test the Sass linter, you get this error
> Error: Invalid CSS after "...-penumbra-color": expected ";", was ","
I think the Sass linter doesn't understand variable interpolation + lists. This is a workaround to pass the linter.

fix(elevation): Update _mixins.scss so Sass linter passes

---

packages/mdc-animation/README.md
packages/mdc-animation/_functions.scss
packages/mdc-checkbox/mdc-checkbox.scss
packages/mdc-drawer/_mixins.scss
packages/mdc-linear-progress/mdc-linear-progress.scss
packages/mdc-radio/mdc-radio.scss
packages/mdc-select/mdc-select.scss
packages/mdc-snackbar/mdc-snackbar.scss

BREAKING CHANGE: We currently don't distinguish between "temporary" and "permanent" exits in mdc-animation. However, the timing function we're using is actually that of "permanent", so we should rename the function to reflect that. This will also allow us to add "temporary" exit in the future.
https://material.io/guidelines/motion/movement.html#movement-movement-in-out-of-screen-bounds

chore(animation): Rename `exit` to `exit-permanent` to match spec

---

packages/mdc-slider/README.md

Change the description of the MDC Slider Component API in package/mdc-slide
link:[https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider#methods](https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider#methods)

Correct the description of the method

---

packages/mdc-button/mdc-button.scss
packages/mdc-button/package.json

fix(button): Add mdc-typography-base to button

---

packages/mdc-slider/mdc-slider.scss

fix(mdc-slider): .mdc-slider__thumb-container should set #user-select property to none

---

packages/mdc-grid-list/mdc-grid-list.scss

fix(grid): .mdc-grid-tile__support-text does not cut off the text overflow.

---

packages/mdc-animation/README.md
packages/mdc-animation/_functions.scss
packages/mdc-animation/_mixins.scss
packages/mdc-animation/_variables.scss
packages/mdc-animation/mdc-animation.scss
packages/mdc-checkbox/mdc-checkbox.scss
packages/mdc-drawer/_mixins.scss
packages/mdc-linear-progress/mdc-linear-progress.scss
packages/mdc-radio/mdc-radio.scss
packages/mdc-select/mdc-select.scss

Update components that were incorrectly using the _permanent_ exit animation (acceleration curve) to use the _temporary_ exit animation (sharp curve) instead.

fix(animation): Update exit curves to match spec

---

packages/mdc-elevation/README.md

docs(elevation): Moving CSS Classes ahead of Sass mixins, 

---

packages/mdc-elevation/README.md

The markdown needs to work in our internal Google docs as well. The changes in markdown doesn't make any visual changes, it just makes it easier to copy/paste into our internal tool later.

docs(elevation): Update markdown

---

packages/mdc-theme/README.md

The markdown needs to work in our internal Google docs as well. The changes in markdown doesn't make any visual changes, it just makes it easier to copy/paste into our internal tool later.
However, shortening the tables makes the README easier to...well...read.

docs(theme): Shorten tables in README, and update markdown

---

packages/mdc-ripple/README.md
packages/mdc-ripple/util.js
test/unit/mdc-ripple/helpers.js
test/unit/mdc-ripple/util.test.js
test/unit/mdc-tabs/mdc-tab.test.js

This adds feature detection for buggy var() behavior in Edge WRT pseudo selectors, and will not upgrade ripples if the buggy behavior is found.
Because this adds quite a bit of logic (including DOM operations) to the function, this PR also changes the function to cache its result once a true or false result is obtained, much like we do for various other util functions.  This requires adding an optional force parameter to the function for tests to use.
This PR also updates tests and adds one to test the new case, and adds a section to the README.
Fixes #663.

fix(ripple): Feature-detect buggy Edge behavior for custom properties

---

packages/mdc-tabs/README.md

This PR fixes a small typo in the dynamic tab bar example in the readme of mdc-tabs. The package is incorrectly referred to as `mdc.tabBar` instead of `mdc.tabs`.

Fix typo in mdc-tabs readme example

---

CONTRIBUTING.md

Refs #1043.  Encouraging all committers to use npm 5 so the lockfile gets updated should hopefully avoid others running into the confusion I did due to version conflicts when I started working on it.

docs: Add note to CONTRIBUTING.md about using npm 5 to update package-lock

---

demos/demos.scss

This will allow `demos.scss` to be `@import`-ed by different themes, which will each specify their own color values.

chore(demos): Make theme color vars `!default`

---

packages/mdc-theme/_constants.scss
packages/mdc-theme/_functions.scss
packages/mdc-theme/_mixins.scss
packages/mdc-theme/_variables.scss

`//` comments don't appear in the CSS output.

Change theme's SCSS comment style from `/**` to `//`

---

package-lock.json
package.json

This is the same as https://github.com/material-components/material-components-web/pull/1058, but I made it the ^ version. I think we can rely on all minor updates to testdouble.
I will also close https://github.com/material-components/material-components-web/pull/849 in favor of this PR

chore: Update testdouble to the latest version

---

package.json
webpack.config.js

A new `GENERATE_SOURCE_MAPS=false` env var disables source map generation in dev mode, which cuts build and recompile times in half.
Invoked like so:
```bash
GENERATE_SOURCE_MAPS=false npm run dev
```

perf(infrastructure): Cut build time in half with opt-in env var

---

packages/mdc-button/mdc-button.scss

Build was accidentally broken in PR #1074 due to a non-obvious merge conflict.

fix(button): Reference `secondary` theme prop instead of `accent`

---

demos/button.html
packages/mdc-button/mdc-button.scss

Fixes #1167 by moving disabled styles back to the end of `mdc-button.scss`.
Also reorganizes test page to allow testing disabled state on all button types.

fix(button): Restore order of disabled styles

---

packages/mdc-ripple/foundation.js
packages/mdc-toolbar/mdc-toolbar.scss
test/unit/mdc-ripple/foundation.test.js

fix: Correct unbounded ripple diameter

---

demos/button.html

I did a silly thing earlier today when I updated the button demo page to test disabled buttons - I used a fat arrow directly in a demo page, which will break the page's JS in IE 11. This commit fixes the problem.

fix(demos): Fix button demo update from #1176 to work in IE 11

---

packages/mdc-ripple/foundation.js
packages/mdc-toolbar/mdc-toolbar.scss
test/unit/mdc-ripple/foundation.test.js

This reverts commit 0f1ca3598248c6df7fe456e198ce6519397b0247 and fixes #1184.
Unfortunately this commit caused a major regression for bounded ripples, such as those seen in the button and dialog demos.

fix(ripple): Revert #1098 to fix bounded ripples

---

demos/tabs.html

We were forgetting to call `layout` on the very first tab bar in the page in the logic for the RTL toggle, which causes it to appear to reflect the opposite of what it should in RTL mode.
Fixes #1189 in Tabs demo page.

fix(demos): Update first tab bar's layout when toggling RTL

---

demos/layout-grid.html

Closes #1037 
The purpose of this PR is to separately modify the padding/margin of layout grid in each section.
Even though the diff looks ugly, the changes are very simple:
1. It add two parent section `layout-grid-in-fluid-container` and `fixed-column-width-layout-grid` and indent the inner part correspondingly (which create this magic large diff)
2. It modify only css properties in the corresponding scope, such as `fluidContainerSection.style.setProperty`. 
This modify margin/padding in both section
This modify column width only in second section
This modify only the first section's margin/padding
And this modify the margin/padding/column width in the second section.

docs(layout-grid): Separate layout grid in fluid container and fixed column width in demo

---

demos/button.html
packages/mdc-button/README.md
packages/mdc-button/mdc-button.scss

feat(button): Implement stroked button

---

packages/mdc-fab/README.md

Missed removing the docs in #1209

docs(fab): Remove docs around tap-highlight

---

CONTRIBUTING.md

#Background
I was trying to share my WIP with our design team there is not a straightforward way for doing so, I thought it would be great if each of core team have a (their own) dev server, so I went ahead and created one. With this script, you should be able to run build and deploy to a remote server that you can share with designer, core-team. 
One side note, not sure if it make sense to make this internal or external. Let me know if we want to put this on appengine public instead so that we may further share our proof of concept with our communities?

docs(infrastructure): Update instruction to deploy to development server

---

packages/mdc-ripple/util.js
test/unit/mdc-ripple/util.test.js

This PR also fixes the unit test for the Edge feature detect, which I noticed was passing for the wrong reason when I added another unit test for this case 😶 
Fixes #1195.

fix(ripple): Avoid errors in feature-detect within hidden iframes in Firefox

---

demos/dialog.html
demos/linear-progress.html
demos/simple-menu.html

All other demo pages use `var`. Additionally, older browsers (notably IE < 11) don't support `const`, and we don't currently transpile our demo JS to ES5.

chore(demos): Use `var` instead of `const`

---

packages/mdc-fab/README.md
packages/mdc-fab/_mixins.scss
packages/mdc-fab/mdc-fab.scss

There's no good explanation for what `config` was other than 'a collection of background, foreground, and ripple colors. From an API perspective, there is no reason to group the three properties together. The logic has no dependency on each other, as you can see in the old `mdc-fab-theme` implementation.
Andy mentioned that `config`... 'gives clients the ability to create extensible themes that can be "inherited" by other themes (similar to Android)'. But when I talked to designers, it was difficult to see a use case where `config` would be used by any other component. If a client is already customizing the color of FABs container, ink, and ripple, they will also probably customize the color of a Menu's container, ink, and ripple with _slightly different_ colors.
I also updated the names, …

refactor(fab): Break theme mixin into three mixins, to decouple code

---

packages/mdc-checkbox/_keyframes.scss
packages/mdc-checkbox/mdc-checkbox.scss

This is the only place where we actually use mdc-animation mixins. I think referencing the animation variable directly is more clear.

refactor(switch): Reference animation timing function directly

---

demos/select.html
packages/mdc-select/README.md

The 'option' element doesn't have a 'default' attribute.
So, remove the attribute from examples to avoid promoting
non-conforming usage.

docs: remove invalid 'default' attribute from examples

---

packages/mdc-slider/foundation.js

resolves #1173 
Micro-change, but the "setStep"-function actually triggers a "setValue" which sets aria-valuenow to null since the value is still uninitialized at this time.
(Sorry, had to recreate my previous pr)

fix(slider): Change how step value is initialized (#1173)

---

packages/mdc-button/_mixins.scss
packages/mdc-button/mdc-button.scss

...since it is not customizable
This PR also updated the disabled color
1. rgba(black, .38) == text-disabled-on-light
2. Update filled disabled button text color to use text-disabled-on-light in both dark and light mode 
3. Update filled disabled button background color to 0.12 opacity 
Example from stickersheet

feat(button): Move disabled style into private base mixin 

---

demos/button.html
demos/demos.scss

I renamed `accent` to correctly using `secondary` in the new class selector.
In the next PR, I will remove the stale modifier.
I split `stroked` and `text` button in order to show how to completely customize the style of each button type, if that makes sense.

docs(button): Make call in stylesheet button.html to create primary and secondary example

---

demos/toolbar/index.html

Fixes a bug introduced in #1068, where a new example was added but the index passed to toggleRTL wasn't properly updated in the added example or the ones appearing after it.
This fixes the issue by removing the need to pass the correct index altogether, so this problem should not happen again.

docs(toolbar): Fix off-by-one error in toolbar demo RTL buttons

---

packages/mdc-auto-init/README.md
packages/mdc-auto-init/index.js
packages/mdc-auto-init/package.json
test/unit/mdc-auto-init/mdc-auto-init.test.js

FIx #954 
@yeelan0319 The dialog component is extending `MDCComponent` so it has direct access to `emit` method. I am not sure how to access the emit method properly in `mdcAutoInit` function. I tried to import `MDCComponent`, but I guess it is not good. 
Also I am not sure what the test should be.
Any help appreciated.

feat(auto-init): Fire event on mdcAutoInit complete

---

demos/button.html
demos/card.html
demos/checkbox.html
demos/linear-progress.html
demos/toolbar/index.html

I randomly noticed we had a few demo pages that had an extra 'o' in Components in the title. Good for a laugh but let's fix it 😂

docs: Fix typos of "Components"

---

demos/snackbar.html
packages/mdc-snackbar/README.md
packages/mdc-snackbar/mdc-snackbar.scss
packages/mdc-snackbar/package.json

BREAKING CHANGE: Removed the dependency of mdc-button from DOM structure of snackbar.
Dev server: 1292-dot-mdc-web-dev.xxxx.com
The rationale behind dropping button from snackbar is `action-button` is not technically a `MDC button` from the design perspective.
- It doesn’t have ripple
- It doesn’t have state
- It doesn’t have height and width restriction
- It doesn’t need to have icon etc..(after #1281 merged)
So to prevent future regression, we remove the dependency of button from snackbar by directly styling `action button`. The changes increase CSS file by 10 lines, but the actual size remained same 10KB.

fix(snackbar): Drop mdc-button from snackbar's dependency

---

demos/button.html
packages/mdc-button/README.md
packages/mdc-button/_mixins.scss
packages/mdc-button/mdc-button.scss

[Codepen Demo](https://codepen.io/yeelan0319/pen/pWzxYZ)
Dev server: 1281-dot-mdc-web-dev.xxxx.com

feat(button): Support icon in button

---

demos/theme/index.html

Previously, the Material Icons CSS had a higher specificity because it was imported after the theme page CSS. As a result, icons were sometimes displayed incorrectly.

chore(demos): Fix CSS specificity of Material Icons in theme demo

---

demos/theme/index.scss

Previously, the dialog was displayed on top of open drawers, which is not what we want.

chore(demos): Remove z-index from dialog on new theme demo page

---

demos/button.html
demos/button.scss
packages/mdc-button/README.md
packages/mdc-button/mdc-button.scss

Closes #1163 
This PR contains small things related to demos:
1. Fix baseline button corner radius from 4px to 2px, as required by guideline
2. Add demos how to customize stroke width and corn radius
3. Add `experimental` to `unelevated`, `stroke` and `custom` to specify their states
Deployed to https://1307-dot-mdc-web-dev.xxxx.com/

Docs(button): Fix button corner radius and add demos

---

packages/mdc-fab/_mixins.scss

Not sure how this was missed earlier, but FAB uses functions from mdc-animation, not variables. The missing functions didn't cause a Sass compile error - it just caused the function names to be left in verbatim, which caused browsers to toss out the transition rules entirely.

fix(fab): Import correct mdc-animation resource for functions

---

packages/mdc-fab/_mixins.scss

This makes FABs more consistent with Buttons which already have a hover/focus elevation.
The guideline does not explicitly call out hover/focus elevation but we have discussed the topic with designers, and it will definitely be called out more specifically in the future.

fix(fab): Add hover/focus elevation

---

demos/button.scss
packages/mdc-button/_mixins.scss
packages/mdc-button/_variables.scss
packages/mdc-button/mdc-button.scss

This PR is made to make customize button with mixins easier:
1. Expose `filled` and `unfilled` button ripple opacity value, so they could use those value if they only wish to adapt ripple color to custom ink color 
2. Allow theme-variable to be passed as `base-color` in `mdc-button-ripple`, so that `mdc-button-filled-accessible` will ensure ink color is always aligned with ripple color to prevent potential error.
*Note*: It worths considering move `tap-color` as well as `base-color` logic into ripple, but I suggest we do that separately when we refactor ripple. I added a todo here to indicate this is something that we should revisit.

refactor(button): Make ripple configure using variables

---

demos/common.scss
packages/mdc-button/mdc-button.scss

Fixes #1345.
I should point out a couple of caveats with this approach, which differs from the prior approach of providing --primary and --accent (now AKA secondary) as opt-in classes...
* By setting a hard default to primary, light-vs-dark considerations are dropped, and in general, contrast considerations will be left to the user when customizing theme if customizing via CSS variables.
* I'm a little concerned especially about flat buttons using primary for text/ink color, in cases where the primary color is relatively light.
* Current versions of Edge with (buggy) CSS variable support will have problems displaying this. I'm pondering looking into #1102 to see if this can be addressed.

fix(button): Default to primary color

---

demos/toolbar/menu-toolbar.html

Fix a small regression introduced by #1068 
Before
After

docs(toolbar): Fix Toolbar with Menu demo's icon padding

---

demos/dialog.html

Previously, clicking the "Show dialog" button would display a dialog behind the "Dark Theme" dialogs.

fix(demos): Remove z-index from non-modal dialogs

---

docs/code/architecture.md

Removes a paragraph that is exactly the same as the one before it minus a period.

docs: Remove redundant paragraph

---

packages/mdc-textfield/adapter.js
packages/mdc-textfield/constants.js
packages/mdc-textfield/foundation.js
packages/mdc-textfield/index.js

Annotates MDC Textfield for the Closure Compiler.
Resolves #345

feat(textfield): Annotate textfield for Closure Compiler.

---

scripts/check-pkg-for-release.js

Previously `npm run test:dependency` would not work on Linux.

chore: Fix cssom module reference to work on case-sensitive filesystems

---

docs/closure-compiler.md

Updates the Closure Compiler annotation doc:
1. Applies Closure style to the examples.
2. Updates the examples with the doc's own recommendations (e.g. export statements go at the end), particularly for the provided skeleton.

docs(base): Update Closure Compiler annotation doc

---

package-lock.json
package.json
packages/mdc-textfield/mdc-textfield.scss

Travis CI had been failing lint tests due to installing stylelint 8.2.0 because it's using npm 4 and not honoring our package-lock.
h/t @bwobrien for unintentionally reproducing this case on his system which made me realize what the cause was :)

chore: Update to stylelint 8.2.0 and address new lint errors

---

demos/ripple.html

Message was previously:
- Hidden behind the toolbar
- Not displayed in Edge, even though Edge doesn't support ripple
Before:
After:

fix(demos): Make unsupported ripple message visible and improve detection

---

packages/mdc-slider/foundation.js

Fixes #1429.
Note that our init/destroy tests generally don't nit-pick _which_ function gets called, which is why this went unnoticed. Addressing tests across all packages to be able to spot this would be a larger undertaking...

fix(slider): Deregister correct handlers on destroy

---

lerna.json

Resolves #1134 (or at least, makes it so it should no longer happen).
After several discussions on the team (and several instances of #1134 happening), we've decided to simply switch to fixed mode to avoid risking further issues like this, at least during the duration of the 0.x line. We'll likely discuss release management again in the future for 1.x and beyond.
This commit updates the version string so that lerna will prompt appropriately based on the current version when we next release.

chore: Switch lerna to fixed mode

---

packages/mdc-icon-toggle/index.js
test/unit/mdc-icon-toggle/mdc-icon-toggle.test.js

Add a getter for MDCRipple in icon toggle so it can be used through a public API
#1171

feat(icon-toggle): Add public API for MDCRipple in icon-toggle (#1171)

---

packages/mdc-ripple/README.md
packages/mdc-ripple/_mixins.scss

(This commit also re-orders the new private mixin below the new public ones.)
BREAKING CHANGE: The existing MDC Ripple Sass mixins mdc-ripple-base, mdc-ripple-fg, and mdc-ripple-bg have been removed, replaced by the new easier-to-use mixins mdc-ripple-surface, mdc-ripple-color, and mdc-ripple-radius.

feat(ripple): Remove old complex mixins

---

packages/mdc-form-field/README.md

There is no `MDCFormField` in `mdc.radio.` hierarchy.

Fix README.md for form_field

---

packages/mdc-toolbar/README.md

There are some minor conjugation and consistency issues in the mdc-toolbar modifier docs.

docs: Fix grammar for mdc-toolbar modifiers

---

packages/mdc-dialog/mdc-dialog.scss

Round 2 (with proper commit authoring this time!)
Fixes #1032 where the body copy color of the `.mdc-dialog--dark-theme` was not the appropriate color

fix(dialog): fixed dark-theme dialog copy color

---

packages/mdc-slider/mdc-slider.scss

The old behavior is not in the M1 or M2 specs. Even if it was, it's terrible for accessibility and is inconsistent with the continuous slider behavior.
Resolves #1427

fix(slider): Don't hide focus ring on discrete sliders

---

.stylelintrc.yaml
packages/mdc-button/_mixins.scss
packages/mdc-fab/_mixins.scss
packages/mdc-theme/README.md
packages/mdc-theme/_functions.scss
packages/mdc-theme/_variables.scss

The old mixin name is confusing. It's also cumbersome to use if you just want to get the tone of a color directly, and you don't care about the text color that pairs with it.

feat(theme): Add new tone mixins and deprecate old one

---

packages/mdc-textfield/README.md
packages/mdc-textfield/foundation.js

This is to allow integration into other web frameworks.

feat(textfield): Convert some foundation methods from private to public

---

docs/open_source/release.md
scripts/post-release.sh
scripts/pre-release.sh

This reinstates `scripts/post-release.sh` and moves changelog generation back to that, because standard-changelog operates based on the latest version it sees in package.json.
This also updates the command used to detect the latest version for tagging, since we're no longer using lerna in independent mode and so the old command we used no longer picks up the latest version.

chore: Fix changelog generation step in release process

---

packages/mdc-list/mdc-list.scss

fix(list): Lists have incorrect padding

---

docs/getting-started.md
docs/integrating-into-frameworks.md

Fix a missing word in the getting started guide: "effect" in "a fairly subtle effect". Fix a typo in the integrating frameworks guide: "on our main README" to "in our main README".

docs: Fix typos in getting started and integrating frameworks docs

---

packages/mdc-dialog/mdc-dialog.scss

This property seems unnecessary after testing on our demo pages

chore(dialog): Remove height property from scroll-lock class

---

packages/mdc-drawer/temporary/mdc-temporary-drawer.scss

This property seems unnecessary after testing on our demo pages

chore(drawer): Remove height property from scroll-lock class

---

packages/mdc-slider/foundation.js
test/unit/mdc-slider/foundation-keyboard-events.test.js

fix(slider): Properly handle arrow keys events in IE

---

packages/mdc-list/mdc-list.scss

#1523 made the bottom padding match the top padding in lists, but dense lists already had an override for top padding only. This adds an override for bottom padding to match.

fix(list): Make bottom padding match top for dense lists

---

packages/mdc-ripple/README.md

Resolves #734 by documenting incorrect mobile Safari behavior and how to get around it.

docs(ripple): Document mobile Safari :active caveat

---

packages/mdc-textfield/README.md
packages/mdc-textfield/adapter.js
packages/mdc-textfield/constants.js
packages/mdc-textfield/foundation.js
packages/mdc-textfield/helper-text/README.md
packages/mdc-textfield/helper-text/adapter.js
packages/mdc-textfield/helper-text/constants.js
packages/mdc-textfield/helper-text/foundation.js
packages/mdc-textfield/helper-text/index.js
packages/mdc-textfield/helper-text/mdc-text-field-helper-text.scss
packages/mdc-textfield/index.js
packages/mdc-textfield/mdc-text-field.scss
test/unit/mdc-textfield/foundation.test.js
test/unit/mdc-textfield/mdc-text-field-bottom-line-foundation.test.js
test/unit/mdc-textfield/mdc-text-field-helper-text-foundation.test.js
test/unit/mdc-textfield/mdc-text-field-helper-text.test.js
test/unit/mdc-textfield/mdc-text-field.test.js

This PR splits out helper text logic into another subdirectory, similar to PR#1585 for bottom line. The goal is to increase readability and reduce merge conflicts.

chore(text-field): Split out helper text as a subelement

---

packages/mdc-theme/_mixins.scss
packages/mdc-theme/_variables.scss

The `mdc-theme-prop` mixin and `mdc-theme-prop-value` function now treat `currentColor` as if it were a color and emit/return it directly.

feat(theme): Support currentColor in mdc-theme-prop*

---

demos/index.html
demos/list.html
packages/mdc-list/README.md
packages/mdc-list/mdc-list.scss

BREAKING CHANGE: The `mdc-list-item__text__secondary` class was renamed to `mdc-list-item__secondary-text` to adhere to BEM conventions.

chore(list): Rename CSS class to follow BEM

---

packages/mdc-icon-toggle/foundation.js
test/unit/mdc-icon-toggle/mdc-icon-toggle.test.js

fix(icon-toggle): Don't nuke tabindex if initializing disabled to false

---

demos/icon-toggle.html
demos/icon-toggle.scss
packages/mdc-icon-toggle/mdc-icon-toggle.scss

Also simplifies styling of the demo page a bit, in addition to applying opacities based on the examples in the [guidelines](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons).
Note that this does nothing in terms of the `--primary` or `--secondary` modifiers since I expect that's part of a separate theming-related task.

feat(icon-toggle): Use new mdc-states mixin for icon-toggle styles

---

demos/button.scss
demos/common.scss
demos/theme/index.scss
packages/mdc-button/_mixins.scss
packages/mdc-button/_variables.scss
packages/mdc-button/mdc-button.scss

BREAKING CHANGE: The $mdc-*-button-ripple-opacity variables have been removed, as these values are now available via the state opacity maps in mdc-ripple.

feat(button): Use new mdc-states mixin for button styles

---

demos/simple-menu.html

- Use mdc-typography to make text look nicer
- Fix invalid markup
- Reformat markup
- Add a space between radio buttons and their label text
- Use light colored text in dark mode

chore(demos): Make simple-menu demo less ugly

---

demos/simple-menu.html

This was supposed to be part of PR #1659, but I was dumb and forgot to `git push` before merging the PR into master. D'oh!

chore(demos): Remove white gap from simple-menu demo in dark mode

---

packages/mdc-ripple/README.md

Missed these updates when we decided to rename the basic states mixin.

docs(ripple): Update mdc-states-color -> mdc-states

---

packages/mdc-theme/README.md
packages/mdc-theme/_variables.scss

New mixin: `mdc-theme-accessible-ink-color($fill-color, $text-style: primary)`

feat(theme): Add accessible-ink-color function

---

packages/mdc-toolbar/README.md

- Remove table column alignment spaces to match our style convention in other READMEs
- Remove leading/trailing pipe characters on tables
- Remove duplicate blank lines

docs(toolbar): Reformat README

---

packages/mdc-theme/_variables.scss

Due to an unfortunate bug in `scss-parser`, the inline comments in the property-values map were being prepended to the following lines in the build process to transform for Bazel, effectively commenting out any line that appeared directly after an inline comment in the map. While that bug is still present, replacing the inline comments with multiline comments reduces the impact of the bug.
For future reference, comments in a map should be multiline comments until we find a real solution to this.

fix(theme): replace inline comments in map with multiline comments

---

packages/mdc-select/mdc-select.scss

This resolves the Chrome-specific select menu glitch I discovered while testing #1737 (see screenshot in https://github.com/material-components/material-components-web/pull/1737#issuecomment-351105800).

fix(select): Work around glitch with new list styles in Chrome

---

packages/mdc-linear-progress/README.md
packages/mdc-linear-progress/foundation.js

Fixes #1680
@bonniezhou I made a PR like you suggested in #1680.
One question: The current `setStyle` implementation returns the value. See https://github.com/material-components/material-components-web/blob/master/packages/mdc-linear-progress/index.js#L58 Is that intended? If not I can update my PR. Thanks!

docs: Update documentation for `setStyle` in `linear-progress`.

---

packages/mdc-select/mdc-select.scss

See https://github.com/material-components/material-components-web/pull/1737#issuecomment-351742347 for what this addresses, and see the comment in the added code as to why I'm resorting to this approach.
I could probably arguably do this specifically only for Firefox with a supports clause instead, but I don't think this is doing us any favors in other browsers either because of how generally flaky they are with allowing native selects to be styled.

fix(select): Disable ripple/state pseudos for native multiselect

---

docs/migrating-from-mdl.md

Please update the list of available components within the MDL migration guide to ensure interested parties for migration know the available component coverage.
See: https://github.com/material-components/material-components-web/issues/1444 (The Migration guide is out of date)

docs: Update list of already available components

---

demos/text-field.html
packages/mdc-textfield/README.md
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/adapter.js
packages/mdc-textfield/constants.js
packages/mdc-textfield/foundation.js
packages/mdc-textfield/index.js
packages/mdc-textfield/label/README.md
packages/mdc-textfield/label/adapter.js
packages/mdc-textfield/label/foundation.js
packages/mdc-textfield/label/index.js
packages/mdc-textfield/mdc-text-field.scss
packages/mdc-textfield/outline/README.md
packages/mdc-textfield/outline/adapter.js
packages/mdc-textfield/outline/constants.js
packages/mdc-textfield/outline/foundation.js
packages/mdc-textfield/outline/index.js
packages/mdc-textfield/outline/mdc-text-field-outline.scss
test/unit/mdc-textfield/foundation.test.js
test/unit/mdc-textfield/mdc-text-field-label-foundation.test.js
test/unit/mdc-textfield/mdc-text-field-label.test.js
test/unit/mdc-textfield/mdc-text-field-outline.foundation.test.js
test/unit/mdc-textfield/mdc-text-field-outline.test.js
test/unit/mdc-textfield/mdc-text-field.test.js

Add an outline subcomponent and wire it into the parent component for the outlined variation of MDC Text Field. It uses an SVG path when the text field is focused and a div border when it's idle.
The demo of outlined text field includes:
- disabled
- RTL
- usage with helper text
These will come in later PRs:
- ripple
- leading/trailing icons
- dense variant
- CSS-only variation

feat(text-field): Add outline subelement and demo for outlined text field

---

packages/mdc-ripple/README.md
packages/mdc-ripple/_mixins.scss
packages/mdc-ripple/constants.js
packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation-activation.test.js
test/unit/mdc-ripple/foundation-deactivation.test.js

This removes the pre-states mdc-ripple-color mixin which is no longer used
by any components. It also removes logic for the active-fill modifier class
which is no longer a thing with new states styles, and removes the logic
that suppressed focus styles on press/release, since states are designed to
more closely match actual browser behavior.
This is essentially the cleanup for #1556 now that everything has been converted.
BREAKING CHANGE: The mdc-ripple-color mixin is removed; use the mdc-states-* mixins instead.

feat(ripple): Remove old mixin and obsolete JS logic

---

docs/importing-js.md
packages/mdc-textfield/README.md
packages/mdc-textfield/bottom-line/README.md
packages/mdc-textfield/helper-text/README.md
packages/mdc-textfield/icon/README.md
packages/mdc-textfield/label/README.md

I've cleaned up each README of each subelement follow the structure of
* Intro (simple one line from spec)
* HTML Structure
* Usage within `mdc-text-field`
* CSS Classes
* `MDCTextFieldFoo` API documentation
* `MDCTextFieldFooAdapter` API documentation
* `MDCTextFieldFooFoundation` API documentation
I've also cleaned up the main text field README to follow a very similar structure. There are a lot of 
> _NOTE_
in packages/textfield/README.md...which is concerning...but it represents how complicated the HTML structure is.
The idea, going forward, is that any breaking change to `MDCTextField` or its sub elements will require a change to these READMEs.
CHANGELOG only allows for a very short description of a breaking change. The idea is to have READMEs be the more detailed documentation for …

chore(textfield): Update README to follow best practices

---

demos/snackbar.html
packages/mdc-snackbar/README.md
packages/mdc-snackbar/constants.js
packages/mdc-snackbar/foundation.js
packages/mdc-snackbar/index.js
test/unit/mdc-snackbar/foundation.test.js
test/unit/mdc-snackbar/mdc-snackbar.test.js

Add feature to emit MDCSnackbar:show when shown or MDCSnackbar:hide when
dismissed.

feat(snackbar): Emit show or hide event. fixes #1603

---

packages/mdc-list/mdc-list.scss

Fixes #1748.
@lynnjepsen I replicated what you did in #1733.
The dark-theme selectors are still nested: e.g. `.mdc-theme--dark .mdc-list-group .mdc-list-group__subheader`. I didn't come up with an elegant solution :-/

fix(list): Respect BEM when outputting the base stylesheet.

---

demos/select.html
demos/theme/index.html
packages/mdc-select/README.md
packages/mdc-select/index.js
packages/mdc-select/mdc-select.scss
test/unit/mdc-select/mdc-select.test.js

Fixes #1725. Also applies the same shade while the select is open as when it's focused.
BREAKING CHANGE: JS-enhanced Select should now apply tabindex to the surface element instead of the root element. The adapter APIs related to focus, interaction handling, and tabbability now operate on the surface element instead of the root element.

feat(select): Move focus handling to surface element for focus shade

---

packages/mdc-checkbox/_mixins.scss

The `mdc-checkbox__background` mixin included the
`mdc-checkbox__child--cover-parent-` mixin which set the positioning for
the element on all sides to 0. However, the `mdc-rtl-reflexive-position`
mixin **also** sets left and right positioning and the
`mdc-checkbox__background` mixin **also** set the top positioning,
resulting in duplicate properties when compiled out to CSS. This fix
removes the colliding `mdc-checkbox__child--cover-parent-` mixin and
sets only the remaining properties (`position` and `bottom`) to what
they would've been with the `mdc-checkbos__child--cover-parent-` mixin.

fix(checkbox): Remove duplicate background props

---

demos/text-field.html
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/mdc-text-field.scss

Fixes: https://github.com/material-components/material-components-web/issues/1505. Also added a dark theme and disabled checkbox on the CSS Only textfield to showcase fix.

fix(textfield): placeholder colors

---

demos/text-field.html
packages/mdc-ripple/foundation.js
packages/mdc-textfield/adapter.js
packages/mdc-textfield/foundation.js
packages/mdc-textfield/index.js
test/unit/mdc-textfield/foundation.test.js

fixes: https://github.com/material-components/material-components-web/issues/1529

fix(textfield): added isFocused to adapter incase autofocus attr is present

---

packages/mdc-textfield/README.md

Added Missing Part of Readme. Update to https://github.com/material-components/material-components-web/pull/1815/

docs(textfield): updated readme with missing adapter method

---

packages/mdc-ripple/README.md
packages/mdc-ripple/foundation.js
packages/mdc-ripple/index.js
test/unit/mdc-ripple/foundation.test.js

Add setUnbounded to foundation, allowing a method to change whether a
ripple is bounded or not. Modify the unbounded setter on the ripple
implementation to use a local private method to solve closure compiler
access control issues.

feat(ripple): Add setUnbounded to foundation

---

packages/mdc-switch/README.md

docs(switch): Remove not-existing class `mdc-switch--disabled`.

---

scripts/closure-test.sh
scripts/rewrite-decl-statements-for-closure-test.js

To follow internal Google build tool formatting, dashes must not be present in the `goog.module` names. Dashed module names like `goog.module('mdc.form-field.adapter')` now become `goog.module('mdc.formfield.adapter')`. I chose no dashes over underscores to keep keystrokes low (underscore is 2 while **nothing** is 0 which is less than 2).
Fixes #1671

chore(infrastructure): Remove goog.module dashes

---

package.json

Update to package.json to allow `text-field` commit messages to have dash instead of being 1 word.

fix(text-field): allow commit message text-field with dash

---

packages/mdc-textfield/_variables.scss
packages/mdc-textfield/label/mdc-text-field-label.scss
packages/mdc-textfield/mdc-text-field.scss

- increase outline opacity to 87% on hover when input is non-empty and valid
- change label to primary color only when text field is focused (currently it's using the primary color also when input is non-empty and valid)
- change idle label opacity to 60%

fix(text-field): Update outline and label styles according to spec

---

packages/mdc-textfield/icon/README.md

Adds outlined text field example to the icon README, and clarify that icons can only be used with box or outlined text fields.

docs(text-field): Update icon docs with outlined text field

---

demos/drawer/permanent-drawer-above-toolbar.html
demos/drawer/permanent-drawer-below-toolbar.html
demos/drawer/persistent-drawer.html
demos/drawer/temporary-drawer.html

Fixed ids on radio button to update classes on drawer demo pages.

fix(drawer): update radio button ids to correct add/remove classes on demos

---

packages/mdc-textfield/README.md
packages/mdc-textfield/constants.js
packages/mdc-textfield/foundation.js
packages/mdc-textfield/index.js
packages/mdc-textfield/outline/README.md
packages/mdc-textfield/outline/adapter.js
packages/mdc-textfield/outline/constants.js
packages/mdc-textfield/outline/foundation.js
packages/mdc-textfield/outline/index.js
test/unit/mdc-textfield/foundation.test.js
test/unit/mdc-textfield/mdc-text-field-outline.foundation.test.js
test/unit/mdc-textfield/mdc-text-field-outline.test.js
test/unit/mdc-textfield/mdc-text-field.test.js

Remove `getIdleOutlineStyleValue` method from textfield adapter. Add
`getIdleOutlineStyleValue` method to textfield outline adapter. Update
tests to check new functionality.
BREAKING CHANGE: Text field outline adapter now must implement the `getIdleOutlineStyleValue` method previously implemented in the text field adapter. The functionality is exactly the same and requires only small changes to accessing the outline node.

chore(text-field): Move idle outline style method

---

packages/mdc-textfield/adapter.js

Remove `getIdleOutlineStyleValue` method from text field adapter as it
was unused following the merge of #1911

fix(text-field): Remove extra adapter method

---

packages/mdc-textfield/mdc-text-field.scss

The outline color should be the primary color on hover when focused (before this fix, it turns black on hover when focused)

fix(text-field): Fix focused hover state on outlined text field

---

packages/mdc-textfield/README.md

Hero screenshot is broken on live catalog site: https://material.io/components/web/catalog/input-controls/text-field/

docs(text-field): Fix broken image URL

---

packages/mdc-toolbar/_mixins.scss

IE 11 renders the toolbar menu icon with a grey background when the icon's `background-color` is set to `inherit`. Changing the value to `transparent` fixes the bug and doesn't seem to have any adverse affects in other browsers.
Fixes #881

fix(toolbar): Use transparent bg for menu icon to avoid IE 11 bug

---

demos/common.scss

The `mdc-theme-dark` mixin uses Sass's `&` to append to the parent CSS selector. Unfortunately, Sass isn't smart enough to handle multiple comma-separated selectors; it only appends to the last one.
We need to split up the parent rule into two separate rules to ensure that we don't apply `$dark-button-color` in light mode.
The unelevated button on the [theme demo page](https://material-components-web.appspot.com/theme/index.html) actually has a green background applied to it due to this bug, but the order of our CSS imports on the theme demo page happens to prevent us from seeing it.

fix(demos): Fix CSS selector for dark theme buttons

---

packages/mdc-dialog/mdc-dialog.scss

`.mdc-dialog__surface` already has `transition: mdc-animation-enter(opacity, 120ms), mdc-animation-enter(transform, 120ms);` at line 169. So I dont think we need to apply it within the `.mdc-dialog--open .mdc-dialog__surface`.
Furthermore, `.mdc-dialog--open .mdc-dialog__surface` is nested within `.mdc-dialog--animating`, which does not make any sense, since `.mdc-dialog--open` and `.mdc-dialog--animating` shoud be used in conjunction. So I think this is just dead code

fix(dialog): Remove code that does nothing

---

demos/button.html
demos/common.scss
demos/ready.js

For this PR, I only updated the button demo page to use the new `demoReady()` function. #1920 updates the remaining demo pages.
Also note that our packaged JS is now being loaded with `async`, which speeds up initial rendering time over slow connections. Using "Mid-tier mobile" network emulation in Chrome devtools, the [TTFMP](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint) of the button demo page was reduced from ~10.5s to ~9.5s, and the time to render the Material icon font  dropped from ~12s to ~10.5s.

feat(demos): Add global `demoReady()` function

---

demos/theme/index.html
demos/theme/index.scss

Ripple isn't an actual component, and other components on the page already have ripples, so there's no need for separate ripple examples on the page.

chore(demos): Remove ripple examples from theme page

---

demos/text-field.html
demos/text-field.scss
packages/mdc-textfield/README.md
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/bottom-line/_mixins.scss
packages/mdc-textfield/bottom-line/mdc-text-field-bottom-line.scss
packages/mdc-textfield/helper-text/_mixins.scss
packages/mdc-textfield/helper-text/mdc-text-field-helper-text.scss
packages/mdc-textfield/mdc-text-field.scss
packages/mdc-textfield/outline/_mixins.scss
packages/mdc-textfield/outline/mdc-text-field-outline.scss

Breaking Change: Moves color customization of the outline text-field to SASS mixins. 
refs: #1526

feat(text-field): Move text-field outline colors to mixins

---

packages/mdc-slider/index.js

Re-adds an MDCSliderFoundation export to `index.js`.

fix(slider): Add MDCSliderFoundation export

---

demos/theme/_theme-shared.scss
demos/theme/index.html

- Remove unused code
- IE 11 compatible property values (`unset` -> `auto`)
- Fix duplicate IDs
- Use `--stroked` buttons instead of `--raised` for checkbox demo
- Rename CSS classes to be more BEM-y
- Rename and reorganize Sass demo vars
- Reword text-field labels and helper text for clarity
- Remove `getAll()`
- Inline some JS vars

style(demos): Clean up theme demo Sass and HTML

---

packages/mdc-ripple/constants.js
packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation-deactivation.test.js

This fixes problems where a ripple surface would show the ripple twice on touch events, observable on [ripple.html](http://material-components-web.appspot.com/ripple.html) on Chrome on Android or Chrome on desktop with device emulation enabled.
The issue is fixed by relaxing the delay to 300ms to match tap delay on touch devices, and by removing the event x/y coordinate comparisons, as apparently sometimes the coordinates can change from the original user-initiated touch event to the simulated mouse event fired by the user agent.

fix(ripple): Relax deduplication conditions for touch devices

---

demos/common.scss

This is no longer needed because toolbar automatically sets an accessible ink color by default

chore(demos): Remove hard-coded toolbar ink color

---

demos/list.html

This reverts commit fa0f58c0fc9e10fa171cbe0dc954fbecc2151fee.

fix(list): updated demo to show checkbox examples

---

demos/list.html
packages/mdc-list/mdc-list.scss

fixes https://github.com/material-components/material-components-web/issues/1591

fix(list): added ellipsis to text and secondary text if text overflows

---

.stylelintrc.yaml

CSS3 spec requires the quotes. Unquoted strings are only supported for legacy reasons.
We don't currently use function URLs (e.g., `@import url("...")`) in any of our `packages/`, but we _do_ use them in our demo pages, and we'll soon be using them in our screenshot tests.
I want to lint all of our screenshot test code, so this PR is a step in that direction.

chore: Require function URL quotes in stylelintrc

---

packages/mdc-menu/README.md
packages/mdc-menu/adapter.js
packages/mdc-menu/constants.js
packages/mdc-menu/foundation.js
packages/mdc-menu/index.js
test/unit/mdc-menu/mdc-simple-menu.test.js
test/unit/mdc-menu/simple.foundation.test.js

Previously clicks on a list-item in the page would leave the menu open. Now we check if a item in this menu was clicked and leave the menu open.
Fixes #1747 
@amsheehan You introduced this behavior in 02fe795139. Is my fix correct?

fix(menu): Close menu even when a list-item was clicked.

---

demos/ready.js
demos/toolbar/custom-toolbar.html
demos/toolbar/default-flexible-toolbar.html
demos/toolbar/default-toolbar.html
demos/toolbar/fixed-toolbar.html
demos/toolbar/index.html
demos/toolbar/menu-toolbar.html
demos/toolbar/waterfall-flexible-toolbar-custom-style.html
demos/toolbar/waterfall-flexible-toolbar.html
demos/toolbar/waterfall-toolbar-fix-last-row.html
demos/toolbar/waterfall-toolbar.html

This adds ready.js and common.js to the toolbar demo pages so that they get # link canceling behavior, and fixes an issue with ready.js so it also works for demos that only need styles and no JS.

docs(toolbar): Avoid demo page jumping when clicking toolbar icons

---

packages/mdc-textfield/mdc-text-field.scss

This reverts #2163, which moved @includes that involve `&:not(...)` selectors out of their parent class and under an `@at-root` selector, causing them to always match.

revert: chore(text-field): reduce scss specificity (#2163)

---

.eslintrc.yaml
closure_externs.js
package.json
test/build/goldens/build-config-dev-env.golden.json
test/build/goldens/build-config-no-env.golden.json
test/build/goldens/build-config-prod-env.golden.json
test/build/index.js
test/build/mock-env.js
test/build/webpack-config-loader.js
test/build/webpack-module-exports.test.js

- Adds an `npm run test:buildconfig` command, and calls it in `npm test`
- Replaces `;` with `&&` in `package.json` (Windows `cmd.exe` does not support `;`)
To test this PR, simply change a single character in a `test/build/goldens/*.json` file.
Then run `npm run test:buildconfig` in the console.
This PR is a prerequisite for #1994.

chore: Add tests for webpack.config.js module exports

---

packages/mdc-line-ripple/README.md

Also fixes inconsistencies between things ending with a period or not in tables.

docs(line-ripple): Fix typos and add hyphen to improve readability

---

package.json
test/build/goldens/build-config-dev-env.golden.json
webpack.config.js

`MDC_BUILD_STATIC_DEMO_ASSETS` is no longer necessary because we're going to create entirely separate HTML pages for screenshot tests.
Also removed the `npm run build:demo` command, which used the obsolete env var.

chore: Remove obsolete env var from webpack.config.js

---

packages/mdc-textfield/README.md

(This change apparently also caught a bunch of trailing whitespace, so that's also removed here.)
Resolves #2164.

docs(text-field): Add box/outlined clarification for icon

---

packages/mdc-ripple/_mixins.scss

Previously, if the ripple surface had a non-statically-positioned child element (e.g., `position: absolute`), the hover/focus wash was displayed _below_ the child instead of _above_ it.

fix(ripple): Ensure hover/focus states have proper z-index

---

packages/mdc-ripple/README.md

Just realized I never removed a caveat that no longer exists after the refactoring for states.

docs(ripple): Remove obsolete caveat

---

demos/text-field.scss
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/mdc-text-field.scss

Also fixes typos in a couple of private mixins (asterix -> asterisk, full-width -> fullwidth for consistency with other mixins incl. a public one)
Observable using the required checkbox under the fullwidth examples at the end of text-field.html.
Fixes #2165.

fix(text-field): Apply error color on bottom line of fullwidth field

---

packages/mdc-menu/README.md

I think it quickOpen should be set to true in order to turn off menu animation.

docs(menu): wrong boolean value

---

packages/mdc-menu/README.md

Setting a menu as initially open via the `--open` modifier class has probably not worked for a long time and is a questionable use case at best, but the docs still mentioned it.
(There was also apparently a generous helping of trailing whitespace in here, which this PR removes.)
Fixes #2217.

docs(menu): Remove unsupported initially-open DOM example

---

packages/mdc-checkbox/_mixins.scss

Fixes #2213.
Compiles successfully with the Sass gem. Has no effect on output CSS via node-sass.

fix(checkbox): Avoid using & within @at-root context

---

docs/open_source/release.md

Updating missing step during `Push` step, since admins cannot directly push from Git CLI.

docs(package): update docs to release

---

demos/select.html
packages/mdc-select/foundation.js
test/unit/mdc-select/foundation.test.js

Fixes: #2282 
Added tests and demo to check for regression.

fix(select): Fix floating label for pre-selected option

---

packages/mdc-select/README.md

Refs: #2275 
Doesn't fix the entire README, which needs to be redone, but it does fix our JS example to actually run until we get to it.

chore(select): Fix JS example to actually work

---

demos/ready.js

Safari 9.x and IE 10 do not support `const`.
This change is necessary because `ready.js` is not transpiled to ES5.

fix: Use `var` instead of `const` in demos/ready.js

---

demos/card.html
demos/top-app-bar.html

* **Problem:** The right-to-left ↔ left-to-right toggling on [the top-app-bar demo](http://material-components-web.appspot.com/top-app-bar.html ) is broken in Safari 11.0.3 (on macOS 10.13.3)
* **Solution:** Don’t remove the `dir` attribute on `body` in the demo: change its value to `ltr` when the “RTL” checkbox is unchecked
* **Testing:**
1. Get the fix branch set up:
```shell
git clone git@github.com:swashcap/material-components-web.git mcw2
cd mcw2
npm install
npm run dev
```
2. Open http://localhost:8080/top-app-bar.html in Safari
3. Confirm the “RTL” checkbox works after checked and unchecked

Fix demos’ RTL ↔ LTR toggling in Safari

---

packages/mdc-theme/_mixins.scss

`@alternate` annotations need to come before the _second_ property. Otherwise, Closure Compiler strips the first property (it does not output it at all).

fix(theme): Move @alternate annotations for Closure Stylesheets

---

packages/mdc-textfield/mdc-text-field.scss

Fixes : #2015 
Makes the label work like a standard label. If the `for` attribute is specified, clicking the label will focus the corresponding `input`.

fix(text-field): Clicking label should focus textfield

---

demos/drawer/persistent-drawer.html
demos/drawer/temporary-drawer.html

fix(drawer): Update menu icon to be anchor element

---

demos/image-list.scss

Fixes a bug where the Image List in the hero section was right-aligned in IE 11 for some reason. I can only think that for some reason the combination of `auto` side margins when the parent already used flexbox to center its content rubbed IE 11 the wrong way?
The change doesn't cause any visible difference in any other browser.

docs(image-list): Fix hero section of demo in IE 11

---

demos/image-list.html
demos/image-list.scss
packages/mdc-image-list/README.md
packages/mdc-image-list/_mixins.scss

feat(image-list): Add corner radius mixin

---

packages/mdc-top-app-bar/_mixins.scss
packages/mdc-top-app-bar/_variables.scss

The padding for mobile/desktop was refactored to apply from the section, so the desktop value is incorrect and the mobile style is no longer needed.

fix(top-app-bar): Adjust title padding-left

---

.stylelintrc.yaml

IMO it makes no sense to require `column-count` _after_ other CSS columns properties; column count is the most pertinent bit of information (and sometimes is the rule that makes it evident that something is even using CSS columns to begin with) and putting it first should make other columns properties more readable.

style: Order column-count before column-gap

---

demos/image-list.html
demos/image-list.scss
packages/mdc-image-list/README.md
packages/mdc-image-list/_mixins.scss
packages/mdc-image-list/_variables.scss
packages/mdc-image-list/mdc-image-list.scss

feat(image-list): Add Masonry Image List

---

packages/mdc-top-app-bar/_mixins.scss

Noticed this while preparing a demo.

fix(top-app-bar): Fix mixin to use parameter instead of variable

---

packages/mdc-top-app-bar/_variables.scss

Updated this value to align with the baseline spec.

fix(top-app-bar): Update short collapsed border-radius to match baseline

---

demos/webpack.config.js
package.json
test/build/goldens/build-config-dev-env.golden.json

Fixes a regression introduced by #2325.
Supersedes #2433.
To verify:
1. Build and deploy to staging server:
```bash
MDC_ENV=development npm run build && gcloud app deploy app.yaml --project google.com:mdc-web-dev --version $USER
```
2. View the staging server:
```
http://$USER.material-components-web.appspot.com
```

fix: Compile demo CSS/JS during `npm run build`

---

package-lock.json
package.json
packages/mdc-ripple/_mixins.scss

Fixes #2458 and #2410.
node-sass 4.8.3 is now public on npm and still causes the same problem that people had previously experienced.
The cause is actually an [intentional change](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3_5_0__12_July_2017_) in Sass 3.5.0:
> The way CSS variables are handled has changed to better correspond to the CSS spec. They no longer allow arbitrary SassScript in their values; instead, almost all text in the property values will be passed through unchanged to CSS. The only exception is #{}, which will inject a SassScript value as before.
The solution is therefore to explicitly use `#{...}` around values of CSS custom properties that use SassScript expressions. The only place I noticed us using SassScript expressions for a CSS custom property value …

chore: Update node-sass to 4.8.3 and fix ripple regression

---

scripts/check-pkg-for-release.js

Follow-up to #2499. We missed part of the check-pkg-for-release script that needed to be revised.

chore: Skip both package and webpack checks for private packages

---

packages/mdc-tab/README.md

This falls under the same category as #2499. We don't want this listed on the component catalog until all of the pieces of the tab redesign are done.
Also, when we do add it, we should probably use nested paths e.g. `/catalog/tabs/tab` so that there is one top-level item on the catalog listing and the rest appear under it in the nav when you navigate to it.

docs(tab): Remove front-matter since package isn't public yet

---

packages/mdc-toolbar/README.md

The site catalog currently uses `h1::before` for the icon at the top of each catalog page, so having multiple h1 elements causes multiple icons. It should probably not do that, but in the interim, this will make the page look normal again.

docs(toolbar): Only use h1 on the main heading to fix catalog site

---

test/screenshot/asset-uploader.js
test/screenshot/run-upload-assets.js

There's a subtle but important difference between these two lines of code:
```js
promise.then(good, bad);
promise.then(good).catch(bad);
```
The first line is probably better, because it only calls `bad` when there's an error in the promise _executor_.
The second line calls `bad` if an error is thrown in the promise executor _or_ the `good` handler, which is a little strange and unexpected.
See https://gist.github.com/kfranqueiro/9ba61be2a71727d75271d336a81a7d72

chore(infrastructure): Use `Promise.then()` instead of `.catch()`

---

docs/importing-js.md

Right now this isn't included in the documentation nav on material.io for MDC Web, which causes it to cross-link to github instead. Adding this causes links to it to remain within material.io.

docs: Add front-matter to importing-js.md to appear in catalog

---

packages/mdc-toolbar/README.md
packages/mdc-top-app-bar/README.md

We held off adding this until several features of Top App Bar were fleshed out. Now that we've added the deprecation notice to Toolbar, it makes sense to make this visible in the catalog.

docs(top-app-bar): Add metadata for catalog site

---

packages/mdc-textfield/README.md

This updates docs that I missed when doing #2419. The `ripple` property is only populated for Text Field Box now.

docs(text-field): Update documentation around ripple property

---

demos/select.html
packages/mdc-select/README.md

Fixes #2514, where it was pointed out that there is still a mention of an old API in a README example.
I also looked at the demos and made it use component APIs rather than referencing the select element directly.

docs(select): Remove old API usage from README; update demo

---

packages/mdc-button/README.md
packages/mdc-button/_mixins.scss

When creating the horizontal-padding mixin, we unwittingly removed styles that set 0 top and bottom padding, which is important for overriding UA stylesheets. I also didn't need to remove the line-height style when switching to inline-flex.
Also added a note to the readme to clarify the case of customizing padding when stroke is used.

fix(button): Fix vertical alignment of contents

---

packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation-activation.test.js

Fixes #2241.
We currently have a `requestAnimationFrame` call to delay a frame before checking whether the element matches the `:active` selector, to work around issues in Chrome and Firefox. This delay causes the crash in Edge when a submit button is interacted with.
Given that the two problems are mutually exclusive in terms of affected browsers, this means we can forego the `requestAnimationFrame` delay in Edge, and avoid the crash.

fix(ripple): Re-flow logic to avoid crashing Edge

---

packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation-general-events.test.js
test/unit/mdc-ripple/foundation.test.js

Call `layoutInternal_` from within `animateActivation_` so that `layout` doesn't need to be called on bounded ripples when the page resizes or the surface becomes visible.
Unbounded ripples still need to run layout logic in init and on resize, because they dynamically determine positioning/size for the hover/focus shade as well as the press ripple (whereas bounded ripples only dynamically determine positioning/size for the press ripple, which can be done upon activation).
This also enables us to remove code that invokes ripple layout logic in a few components that use bounded ripples, which I'll send separate PRs for.
Fixes #2207.

feat(ripple): Call layout on each activation

---

package.json
scripts/closure-test.sh

Fixes #2558
Closure Compiler removed the `LEGACY` value for `--module_resolution`. It now defaults to `BROWSER` instead.
That change was made in google/closure-compiler@c2cd433
I ran `npm run test:closure` on this PR and `master` and compared their generated `.closure-tmp` directories. [Beyond Compare](https://www.scootersoftware.com/) found no diffs.

chore(package): update google-closure-compiler to version 20180402.0.0

---

packages/mdc-checkbox/foundation.js
packages/mdc-checkbox/index.js
test/unit/mdc-checkbox/foundation.test.js
test/unit/mdc-checkbox/mdc-checkbox.test.js

fix(checkbox): Implement component/adapter APIs to sync aria-checked

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/mdc-text-field.scss

Fix #2056 (label shake animation for RTL outlined variant with leading icon).
Fix #2575 (label font size and position for dense variants (font-size was being overridden by floating-label selectors).

fix(text-field): Update label position and shake animation

---

packages/mdc-chips/_mixins.scss
packages/mdc-chips/_variables.scss
packages/mdc-chips/chip/mdc-chip.scss
packages/mdc-chips/package.json

Fixes: #2479 
Adds proper typography style.
Changes references to `black` color to use `on-surface`

fix(chips): Update to guidance

---

packages/mdc-drawer/_mixins.scss
packages/mdc-drawer/temporary/mdc-temporary-drawer.scss
packages/mdc-elevation/_mixins.scss
packages/mdc-elevation/_variables.scss
packages/mdc-form-field/mdc-form-field.scss
packages/mdc-icon-toggle/mdc-icon-toggle.scss
packages/mdc-rtl/_mixins.scss
packages/mdc-slider/mdc-slider.scss
packages/mdc-snackbar/mdc-snackbar.scss
packages/mdc-tab/mdc-tab.scss
packages/mdc-theme/_variables.scss
packages/mdc-typography/_variables.scss

Multi-line `/* ... */` comments get emitted verbatim in the CSS output,
whereas single-line `//` comments do not.
To test, run `npm run build` and compare
`build/material-components-web.css` against the same file generated by
`master`.
You'll notice a bunch of seemingly random orphaned CSS comments are no
longer emitted.

style: Use single-line `//` comments in Sass

---

.github/ISSUE_TEMPLATE.md

Update issue template to move bug reporting steps and codepen to the top. Also updates the codepen link to a codepen template that include material icons and the roboto font.

docs: Update issue template codepen to include icons/roboto

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/mdc-text-field.scss

Update colors to match the latest guidance. 
Removes the transparent background from the `--box` variant by mixing the surface/on-surface colors with 4% opacity instead of just applying a 4% opacity on black. 
Adds new variables and remove inline usage of `-on-background` colors, since those colors are wrong but not all components have new colors specified.

fix(text-field): Update colors to match guidance

---

packages/mdc-select/mdc-select.scss
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/mdc-text-field.scss

Fixes: #2538 
Updates the typography for select and text-field. Explicitly declares line-height instead of implicitly depending on normalize.css

fix(text-field): Update typography

---

packages/mdc-textfield/icon/README.md
packages/mdc-textfield/icon/adapter.js
packages/mdc-textfield/icon/foundation.js
packages/mdc-textfield/icon/index.js
test/unit/mdc-textfield/mdc-text-field-icon-foundation.test.js
test/unit/mdc-textfield/mdc-text-field-icon.test.js

h/t to @MrChriZ for originally giving this a shot in #2441. This is effectively a review of that with fewer overall changes, but I figured it'd be easier to re-apply the changes since that PR had conflicts with master at this point.
Fixes #2156.
BREAKING CHANGE: Adds getAttr adapter API to text field icon

fix(text-field): Restore icon tabindex according to its initial value

---

demos/chips.html
demos/chips.scss
packages/mdc-chips/README.md
packages/mdc-chips/chip/constants.js
packages/mdc-chips/chip/foundation.js
test/unit/mdc-chips/mdc-chip.foundation.test.js

Remove all references to a "remove" icon because that is the only type of trailing icon allowed.
Also, trailing (remove) icons are permissible only in entry chips.

fix(chips): Trailing icon and remove icon are the same thing

---

packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss
packages/mdc-chips/_variables.scss
packages/mdc-chips/chip/mdc-chip.scss

- Make leading and trailing icon sizes customizable individually
- Update the default leading icon size to 20px
- Make leading and trailing icon colors customizable individually (with optional params for opacity)
- Set icon colors in `mdc-chip-fill-color-accessible` mixin 
Fixes #2484

feat(chips): Customize icon size and color

---

packages/mdc-select/mdc-select.scss

Update `select` component to use the `subtitle1` type.

fix(select): Update typography to match latest guidance

---

packages/mdc-textfield/_mixins.scss

Add error color to invalid trailing icon.

fix(text-field): Add error state to trailing icon

---

demos/button.html
demos/button.scss
demos/checkbox.html
demos/drawer/permanent-drawer-above-toolbar.html
demos/drawer/permanent-drawer-below-toolbar.html
demos/drawer/persistent-drawer.html
demos/drawer/temporary-drawer.html
demos/shape.html
demos/theme/index.html
demos/toolbar/index.html
packages/mdc-button/README.md
packages/mdc-button/_mixins.scss
packages/mdc-button/mdc-button.scss
test/screenshot/README.md
test/screenshot/mdc-button/classes/baseline.html
test/screenshot/mdc-button/classes/dense.html
test/screenshot/mdc-button/mixins/corner-radius.html
test/screenshot/mdc-button/mixins/custom.scss
test/screenshot/mdc-button/mixins/horizontal-padding-baseline.html
test/screenshot/mdc-button/mixins/horizontal-padding-dense.html
test/screenshot/mdc-button/mixins/stroke-color.html
test/screenshot/mdc-button/mixins/stroke-width.html

BREAKING CHANGE: Renames variant, classes and mixins containing `stroke` to use `outline`.

fix(button): Rename stroke to outline

---

demos/card.html
demos/shape.html
demos/shape.scss
packages/mdc-card/README.md
packages/mdc-card/_mixins.scss
packages/mdc-card/_variables.scss
packages/mdc-card/mdc-card.scss

BREAKING CHANGE: Renames variant, classes and mixins containing the word stroke to use the word outline.

fix(card): Rename stroke to outline

---

demos/shape.html
demos/shape.scss
packages/mdc-shape/README.md
packages/mdc-shape/_mixins.scss

BREAKING CHANGE: Renames variant, classes and mixins containing the word stroke to use the word outline.

fix(shape): Rename stroke to outline

---

demos/chips.scss
packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss

BREAKING CHANGE: Renames variant, classes and mixins containing the word stroke to use the word outline.

fix(chips): Rename stroke to outline

---

packages/mdc-chips/chip/mdc-chip.scss

fixes: #2667 
Chips with spaces in the text are wrapping when the exit animation is occurring, causing the chip to increase in height.

fix(chips): Add nowrap to chip text

---

packages/mdc-select/_mixins.scss

SassC::SyntaxError compilation error is caused by unquoted backround-image url:
```
SassC::SyntaxError: Error: expected a variable name (e.g. $x) or ')' for the parameter list for url
on line 17987 of stdin
>>   background-image: url(data:image/svg+xml,%3Csvg%20width%3D%2210px%22%20heigh
-----------------------^
stdin:17987
/home/lex/.gem/ruby/2.3.0/gems/sassc-1.11.4/lib/sassc/engine.rb:47:in `render'
/home/lex/.gem/ruby/2.3.0/gems/sassc-rails-1.3.0/lib/sassc/rails/compressor.rb:16:in `call'
/home/lex/.gem/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:28:in `call'
/home/lex/.gem/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/lex/.gem/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in …
```

fix(select): Fix SassC compilation error

---

packages/mdc-animation/README.md
packages/mdc-layout-grid/README.md
packages/mdc-shape/README.md
packages/mdc-snackbar/README.md

NOTE: This is pending https://github.com/material-components/material-components-web-catalog/pull/131 being merged and the catalog being redeployed, for the new shape demo to exist.

docs: A few more links

---

CHANGELOG.md

fixes: #2732 
The last changelog generation skipped 2 refactor commits for the v35.0 release. This commit adds those and also updates the breaking change list.

docs(changelog): Update Changelog to include missed refactor commits

---

packages/mdc-top-app-bar/index.js
test/unit/mdc-top-app-bar/mdc-top-app-bar.test.js

Fixes Top App Bar's initialize method to add ripple to nav icon only when it is present.
Fixes #2721

fix(top-app-bar): Fix JS error when navigation icon is not present.

---

packages/mdc-textfield/helper-text/mdc-text-field-helper-text.scss

Remove the redundant font-size from textfield helper text. The font-size is already specified in the typography settings and this line is redundant.

chore(text-field): Remove redundant font-size

---

test/unit/mdc-top-app-bar/mdc-top-app-bar.test.js

Moved number of calls check to when() on stubbing using "times".
Follow up to PR: #2751

fix(top-app-bar): Fix testdouble warning about using both stub & verify.

---

test/screenshot/lib/screenshot.js
test/screenshot/lib/storage.js

```bash
```
Open two or more terminals and run the tests in both terminals at the same time:
```bash
```
CBT allows us to test up to 5 pages concurrently.
If two developers run their tests at the same time, we hit that limit:
```
Parallel execution limit reached - waiting for 5 seconds before retrying...
```
Currently, the tests will fail after 5 failed retry attempts:
```
Error: Capture request failed after 5 retry attempts - https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/05/24/16_43_43_944/704147ef0/mdc-button/classes/dense.html
at sendCaptureRequest (/Users/advorak/dev/mdc-web/test/screenshot/lib/screenshot.js:77:11)
at …
```

chore(infrastructure): Remove retry limit for parallel executions on CBT

---

packages/mdc-list/README.md
packages/mdc-textfield/README.md

A couple of tables are broken on the material.io site. 
https://material.io/develop/web/components/lists/

docs: Add new line before tables to fix generated content

---

test/screenshot/lib/cbt-user-agent.js
test/screenshot/lib/storage.js

```bash
```
- Fixes a bug in which all diff images get uploaded to the same URL (which throws an error and crashes the test run)
- Prints a warning message to the console if a file already exists, but continues uploading remaining files
- Removes the argument from `fetchBrowsersToRun()`, because it uses a promise to memoize the result (which means the result needs to be invariant between calls)
- Refactors `fetchBrowserByAlias()`

chore(infrastructure): Fix browser alias lookup bug

---

packages/mdc-dialog/mdc-dialog.scss
test/screenshot/fixture.scss
test/screenshot/golden.json
test/screenshot/mdc-button/classes/baseline.html
test/screenshot/mdc-button/classes/dense.html
test/screenshot/mdc-button/custom.scss
test/screenshot/mdc-button/fixture.scss
test/screenshot/mdc-button/mixins/container-fill-color.html
test/screenshot/mdc-button/mixins/corner-radius.html
test/screenshot/mdc-button/mixins/filled-accessible.html
test/screenshot/mdc-button/mixins/horizontal-padding-baseline.html
test/screenshot/mdc-button/mixins/horizontal-padding-dense.html
test/screenshot/mdc-button/mixins/icon-color.html
test/screenshot/mdc-button/mixins/ink-color.html
test/screenshot/mdc-button/mixins/stroke-color.html
test/screenshot/mdc-button/mixins/stroke-width.html
test/screenshot/mdc-fab/classes/baseline.html
test/screenshot/mdc-fab/classes/mini.html
test/screenshot/mdc-fab/fixture.scss

Fixes #2805
```bash
```
- Sets button-specific widths/heights with new `test-main--button` and `test-cell--button` classes
- Sets FAB-specific widths/heights with new `test-main--fab` and `test-cell--fab` classes
- Moves `mdc-button/mixins/custom.scss` to `mdc-button/custom.scss`
- Changes `<span class="test-cell">` to `<div class="test-cell">`
- Removes and inlines some Sass variables
[Diff report](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/05/24/19_19_57_797/3ac00277f/report.html) (**NOTE:** the first diff on the report is flaky - it is NOT included in this PR's `golden.json`)

chore(infrastructure): Use component-specific test page dimensions

---

packages/mdc-dialog/package.json

It uses legacy @material/typography which is incompatible with
other material components.
#2820

fix(dialog): Fix Typography version

---

packages/mdc-top-app-bar/mdc-top-app-bar.scss

fixes: #2822
Add z-index to the base top app bar style since they're all fixed now. Remove redundant styles.

fix(top-app-bar): Add z-index. Cleanup redundant properties.

---

demos/fab.html
demos/theme/index.html
docs/theming.md
packages/mdc-fab/README.md
test/screenshot/golden.json
test/screenshot/mdc-fab/classes/baseline.html
test/screenshot/mdc-fab/classes/mini.html

IE vertically displaces icons from the Material Icons font if there is trailing whitespace after the text content intended to render the icon.
This fixes all instances of `mdc-fab__icon material-icons` to put the entire element on one line, in docs and demos and screenshot tests.
Fixes #2752.

docs(fab): Remove trailing whitespace from material icons

---

packages/mdc-layout-grid/README.md

Rename 'mobile' to 'phone' for consistency.
Fixes #2836.

docs(layout-grid): update README.md

---

packages/mdc-elevation/_mixins.scss
packages/mdc-elevation/package.json

I noticed while testing installing 0.36.0 that elevation ends up with a nested `node_modules/@material/theme` because it is still depending on a really old version. This fixes that, and takes advantage of the `mdc-theme-prop-value` function that now exists, which elevation was pretty much repeating code from (with a potentially less-helpful error message).

chore(elevation): Update to use latest theme version

---

scripts/post-release.sh

This will allow us to manually run `npm run changelog` and tweak the output ourselves before running `post-release.sh` if we want (e.g. to combine changelogs from pre-releases for a minor release).
To test:
* I would suggest commenting out the latter half of the file to avoid creating spurious tags (i.e. beyond line 37)
* Make a dummy modification to CHANGELOG.md and leave it unstaged in your local repo
* Run `post-release.sh`
* It should detect the existing change and forego running `npm run changelog` itself
* Make another dummy modification, then `git add CHANGELOG.md` so it is staged but not committed
* Run `post-release.sh`
* Again, it should detect the existing change and forego running `npm run changelog` itself
* Run `post-release.sh` without any local changes to CHANGELOG.md
* …

chore: Support manually modifying changelog before post-release

---

packages/mdc-ripple/README.md
packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/mdc-ripple.test.js

This change adds two new public methods to MDC Ripple Foundation - including `handleFocus` and `handleBlur` to be used by other frameworks on focus and blur.
Fixes #2838

fix(ripple): Expose focus/blur handlers 

---

demos/button.html
demos/card.html
demos/checkbox.html
demos/dialog.html
demos/grid-list.html
demos/image-list.html
demos/list.html
demos/snackbar.html
demos/switch.html
demos/theme/index.html
packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
packages/mdc-checkbox/_variables.scss
packages/mdc-checkbox/mdc-checkbox.scss
test/unit/mdc-checkbox/mdc-checkbox.test.js

**NOTE:** The `stroke="white"` SVG attribute has been removed as it is no longer needed.

fix(checkbox): support high contrast mode in Firefox on Windows

---

test/screenshot/lib/cbt-user-agent.js
test/screenshot/lib/cli-arg-parser.js

```bash
node - --mdc-include-browser=chrome
```
Copy and paste these lines of JS into the `node` console:
```js
const CbtUserAgent = require('./test/screenshot/lib/cbt-user-agent');
CbtUserAgent.fetchBrowsersToRun().then((uas) => console.log(uas.map((ua) => ua.alias)), (err) => console.error(err));
CbtUserAgent.fetchSkippedBrowsers().then((uas) => console.log(uas.map((ua) => ua.alias)), (err) => console.error(err));
```
* Adds a `fetchSkippedBrowsers()` method to `cbt-user-agent.js`
- This will be needed by a future PR to display skipped tests on the report page
* Fixes a debugging issue that occurs when you run `node` interactively

chore(infrastructure): Add method to fetch browsers skipped by user's CLI flags

---

test/screenshot/lib/controller.js
test/screenshot/lib/git-repo.js
test/screenshot/lib/screenshot.js
test/screenshot/lib/storage.js

```bash
```
- Uses the `gsutil` CLI command to upload asset files instead of the Node API (`@google-cloud/storage`)
- Speeds up asset file uploads from ~2 minutes to ~45 seconds
- Improves reliability of asset file uploads by letting `gsutil` handle retries and parallelism
- Skips top-level files/directories that are ignored by git
- Displays which HTML files are being tested and which ones are being skipped due to CLI filters
- Displays an error message if no page URLs match the CLI filters
- Adds a more specific error message for bad URLs sent to CBT (HTTP 404, 403, etc.)

chore(infrastructure): Faster, more reliable asset file uploads to GCS

---

package.json
test/screenshot/.gitignore
test/screenshot/lib/controller.js
test/screenshot/lib/image-differ.js
test/screenshot/lib/report-generator.js
test/screenshot/lib/snapshot-store.js
test/screenshot/lib/types.js

Env vars:
```bash
```
Test:
```bash
mv test/screenshot/mdc-button/classes/{baseline,default}.html
```
- Adds three new sections to the diff report page:
* Added (new pages and/or browsers)
* Removed (deleted pages and/or browsers)
* Unchanged (no diffs)
- Writes `report.html` to local disk (in addition to uploading it to GCS)
- Writes `report.json` and `snapshot.json` to local disk and uploads them to GCS
- Updates `npm run screenshot:clean` to delete `report.html`, `report.json`, and `snapshot.json`
- Updates `.gitignore` to ignore `report.html`, `report.json`, and `snapshot.json`
- **NOTE**: At the moment, screenshots that get filtered out by the CLI flags …

chore(infrastructure): Show "added", "removed", and "unchanged" screenshots in report

---

test/screenshot/lib/controller.js
test/screenshot/lib/image-differ.js
test/screenshot/lib/report-generator.js
test/screenshot/lib/types.js

Env vars:
```bash
```
Test with filters:
```bash
npm run screenshot:test -- --mdc-include-url=fab/classes/mini --mdc-include-browser=chrome
```
Test without filters:
```bash
```
- Fixes #2806
- Adds a "skipped" section to the report page (instead of incorrectly displaying skipped screenshots as "removed")
- [67 skipped, 0 diffs](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/06/14/22_54_11_534/report.html)
- [64 skipped, 1 diff](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/06/14/22_51_54_901/report.html)
- [0 skipped, 1 diff](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/06/14/22_57_28_534/repor …

chore(infrastructure): Show "skipped" screenshots on report page

---

packages/mdc-icon-button/README.md

The docs are just missing the right event.

docs(mdc-icon-button): Fix event description

---

docs/open_source/release-process.md
scripts/post-release.sh
scripts/pre-release.sh

* Adds info on how to remove cherry-picked commits that don't belong in a patch release
* Changes output at end of pre and post-release scripts to point to docs, since the next command depends on the type of release

docs: Add more info to release process; update next steps output

---

packages/mdc-icon-button/README.md
packages/mdc-icon-button/adapter.js
packages/mdc-icon-button/foundation.js
packages/mdc-icon-button/index.js
packages/mdc-icon-button/mdc-icon-button.scss
test/unit/mdc-icon-button/foundation.test.js
test/unit/mdc-icon-button/mdc-icon-button-toggle.test.js

Address: #2918 
Also, fixes a bug where the foundation was always initializing as 'off'.

fix(icon-button): Remove unused styles and update docs

---

.eslintignore
test/screenshot/README.md
test/screenshot/commands/test.js
test/screenshot/diffing.json
test/screenshot/fixture.js
test/screenshot/golden.json
test/screenshot/lib/cbt-api.js
test/screenshot/lib/cli.js
test/screenshot/lib/constants.js
test/screenshot/lib/controller.js
test/screenshot/lib/golden-io.js
test/screenshot/lib/image-differ.js
test/screenshot/lib/report-builder.js
test/screenshot/lib/report-writer.js
test/screenshot/lib/selenium-api.js
test/screenshot/lib/user-agent-store.js
test/screenshot/mdc-button/classes/baseline-button-without-icons.html
test/screenshot/mdc-button/classes/baseline-link-without-icons.html
test/screenshot/mdc-button/classes/dense-button-without-icons.html
test/screenshot/mdc-button/classes/dense-link-without-icons.html
test/screenshot/mdc-button/mixins/horizontal-padding-baseline.html
test/screenshot/mdc-button/mixins/horizontal-padding-dense.html
test/screenshot/proto/mdc.pb.js
test/screenshot/proto/mdc.proto
test/screenshot/report/_metadata.hbs
test/screenshot/resemble.json
test/screenshot/run.js

Run this command over and over, and scan the console output for lines that start with "Retry":
```bash
npm run screenshot:test -- \
--url=mdc-button/classes/baseline-button-with-icons.html \
--browser=desktop_windows_ie@11
```
- Automatically retries screenshots that have diffs up to 3 times
- Minimizes noisy diffs due to flaky browser rendering
- Significantly reduces noise across all 4 browsers, especially IE 11 💩
- Compares each screenshot to its golden counterpart immediately after capturing it, instead of waiting until all screenshots have been captured
- Adds `--retries` and `--max-parallels` CLI options
- Fixes buggy parsing of `--diff-base` local `golden.json` files
- Increases the minimum pixel diff threshold from 10 pixels to 15 pixels
- Avoids noisy FAB diffs in Edge
- Changes …

chore(infrastructure): Automatically retry screenshots up to 3 times to reduce flakes

---

README.md

- Remove "Opera". We don't test in it, and it uses the same rendering engine as Chrome (Blink)
- Reorganize list into a map of browsers to OSes (I find it easier to read)

docs: Update list of officially supported browsers

---

.travis.yml
test/screenshot/lib/controller.js

PRs have a separate "status check" for screenshot diffs in the GitHub UI, so we don't want to fail the Travis job if a PR has diffs.
However, once the PR has been merged into `master`, we absolutely _should_ fail the Travis job if there are any diffs.

chore(infrastructure): Post-merge Travis runs should fail w/ diffs

---

scripts/rewrite-decl-statements-for-closure-test.js

The current `goog.module` position-finding logic causes problems when there are other comments in the header of the file. This change resolves that.

fix(infrastructure): Rework goog.module positioning

---

packages/mdc-switch/_variables.scss
packages/mdc-switch/mdc-switch.scss

Discovered through screenshot tests that IE and Firefox have issues with absolutely positioned elements inside elements that are display: flex (although it was working in Chrome).

fix(switch): Fix switch styling in IE and Firefox

---

packages/mdc-tab/_variables.scss
packages/mdc-tab/mdc-tab.scss

Update the use of color and typography in MDCTab to use the most-recent mixins. Add variables for icon size, tab height, text label opacity, and icon opacity. Closes #3058

feat(tab): Update tab color and typography

---

packages/mdc-extended-fab/README.md

Removes the `mdc-extended-fab` readme and directory since we're merging extending fab into `mdc-fab`.

chore: Remove unused extended-fab directory

---

docs/docsite-tabs.md
packages/mdc-tab-indicator/README.md
packages/mdc-tab-scroller/README.md
packages/mdc-tab/README.md
packages/mdc-tabs/README.md

Fixes #3056.
For now, the top-level "Tabs" navigation entry redirects to Tab. We should redirect it to Tab Bar instead once that exists (just update `docs/docsite-tabs.md`).

docs(tabs): Update metadata and synopses

---

test/screenshot/infra/lib/cli.js
test/screenshot/infra/lib/selenium-api.js

- Replaces the `--max-parallels` boolean flag with a `--parallels` numeric flag
- Doesn't retry screenshots when the diff percentage is greater than 10% of pixels (they're probably not flakes)

chore(infrastructure): Add `--parallels` CLI flag; don't retry big diffs

---

packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/constants.js
packages/mdc-tab/foundation.js
packages/mdc-tab/index.js
test/unit/mdc-tab/foundation.test.js
test/unit/mdc-tab/mdc-tab.test.js

Add `computeDimensions` method to `MDCTab` and `MDCTabFoundation`. Add `MDCTabDimensions` type to adapter file. Add `getOffsetWidth`, `getOffsetLeft`, `getContentOffsetWidth`, and `getContentOffsetLeft` to `MDCTabAdapter`. Add tests for new adapter, foundation, and component methods. Update readme. Add periods to the end of JSDoc lines with no periods. Closes #3121

feat(tab): Add MDCTabDimensions computation method

---

.travis.yml
test/screenshot/infra/commands/build.js
test/screenshot/infra/commands/travis.sh
test/screenshot/infra/lib/selenium-api.js

A few recent Travis jobs have had their job logs truncated for being too long. Let's fix that.
- Reduces Travis job log output from ~8k lines to ~2k lines
- Suppresses noisy log output from `install` step
- Only runs `npm install` (but not `npm ls`)
- Travis runs `npm ls` by default, which produces about 4k log lines. This makes the log output harder to read and slower to load in the UI, and it doesn't seem terribly useful.
- Suppresses noisy log output from gcloud installer's `tar` command
- Makes the log output easier to read and faster to load in the Travis job log UI
- Colorizes log output for "parallel execution limit reached" warning messages

chore(infrastructure): Reduce noisy Travis job log output

---

packages/mdc-switch/mdc-switch.scss

Fixes #3111, tested in Chrome, Firefox, IE, and Edge. The issue seems to have come from some sort of interaction between the display flex on the parent of the thumb and the rest of the styling (for IE and Edge).

fix(switch): Fix switch toggling on IE and Edge

---

demos/tab.html
packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/constants.js
packages/mdc-tab/foundation.js
packages/mdc-tab/index.js
test/unit/mdc-tab/foundation.test.js
test/unit/mdc-tab/mdc-tab.test.js

Add `notifySelected` and `notifyActivated` methods to adapter. Add `handleClick` to the foundation. Update tests and demo. Update readme. Closes #3123

feat(tab): Emit selection and activation events

---

packages/mdc-switch/mdc-switch.scss

Realized that having '$has-nested-focusable-element' in mdc-states for switch was causing the focus state to not show up properly in Edge. 
In addition, since we're no longer supporting CSS only switch with the new version that requires JS for styling, it's not necessary to have the focus-within selector for ripple anyway and should be safe to remove.
Tested on Edge, Chrome, and Firefox.

fix(switch): Fix showing switch ripple focus state in Edge

---

test/screenshot/golden.json
test/screenshot/spec/mdc-textfield/classes/baseline-textfield.html
test/screenshot/spec/mdc-textfield/fixture.js
test/screenshot/spec/mdc-textfield/fixture.scss

Does not include textarea, full-width or icon variants, or mixin use.
Intentionally omits the current default since it is being deprecated.
Original report that generated the new goldens: https://storage.googleapis.com/mdc-web-screenshot-tests/kfranqueiro/2018/07/18/20_19_24_759/report/report.html

chore(text-field): Add baseline screenshot test page

---

demos/tab-indicator.html
packages/mdc-tab-indicator/README.md
packages/mdc-tab-scroller/README.md
packages/mdc-tab/README.md

* Fixes #2985
* Fixes #2986
* Fixes #2987

docs(tabs): Update new READMEs to match standard

---

packages/mdc-switch/foundation.js
test/unit/mdc-switch/foundation.test.js

This fixes an issue where Firefox would remember the state of the hidden input element on refresh which could result in a mismatch between switch styling and actual checked state.

fix(switch): Update switch checked styling on foundation init

---

test/screenshot/infra/lib/report-builder.js
test/screenshot/report/_collection.hbs
test/screenshot/report/report.js

- Adds a `#` link on the right side of every screenshot:
- Links to that exact screenshot on the report page
- Collapses all other screenshots if the hash link is present in the URL on page load
- Disables fetching CBT devices in `--offline` mode
- Changes the behavior of the "Collapse Images" button:
- Only collapses images now
- No longer expands/collapses other `<details>` elements

chore(infrastructure): Add image anchors and deep links to report page

---

test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/cli.js
test/screenshot/infra/lib/controller.js
test/screenshot/infra/lib/diff-base-parser.js
test/screenshot/infra/lib/git-repo.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/lib/selenium-api.js
test/screenshot/report/_footer.hbs
test/screenshot/report/report.scss

- Disables `git fetch` by default, but enables it IFF:
1. `--diff-base` looks like a remote branch or version tag (e.g., `origin/master` or `v0.37.1`); and
2. the user has not explicitly disabled fetching with the `--no-fetch` CLI flag
- Swaps the icons for "Collapse All" and "Collapse None" buttons
- Removes the blank space between the browser name and `#` deep link on the report page
- Tweaks the wording of a few log messages

chore(infrastructure): Disable `git fetch` by default

---

test/screenshot/infra/lib/controller.js
test/screenshot/spec/mdc-button/fixture.scss

Ken Was Right.
If there are screenshot diffs, we _should_ fail Travis PR builds by returning a non-zero exit code.
Otherwise, when you look at the build history in Travis, commits that have screenshot diffs are misleadingly displayed with a happy green "passed" badge.

chore(infrastructure): Fail Travis if PR has diffs #KenWasRight

---

packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/foundation.js
packages/mdc-tab/index.js
test/unit/mdc-tab/foundation.test.js
test/unit/mdc-tab/mdc-tab.test.js

feat(tab): Give focus to tab when activated

---

packages/mdc-switch/_variables.scss
packages/mdc-switch/mdc-switch.scss

Checked with design and the knob should be further out than it was to make more of the track visible. This change results in 16px of the track being visible in both checked and unchecked positions (not covered by the knob). Before this change only 12px was visible.
Also added a no-op fix to correctly calculate underlay top.

fix(switch): Update switch styling to match the design spec

---

karma.conf.js
test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/proto/mdc.pb.js
test/screenshot/infra/proto/mdc.proto
test/screenshot/report/_metadata.hbs

- Fixes 2 bugs introduced in #3171:
- Test runs with zero diffs would not print the report page URL to the console
- Test duration calculation always returned `0 milliseconds` for diffs against `master`
- Also removes buggy `commit_offset` field:
- It only works with non-bug-fix releases. It would fail on `v0.36.1`, for example.

chore(infrastructure): Always print report page URL

---

packages/mdc-tab/mdc-tab.scss

fix(tab): Remove extraneous padding from the stacked text label in LTR

---

packages/mdc-tab-scroller/README.md
packages/mdc-tab-scroller/index.js
packages/mdc-tab-scroller/util.js
test/unit/mdc-tab-scroller/util.test.js

This PR:
* Documents `eventTargetMatchesSelector` in the tab-scroller readme
* Adds a util API akin to one in mdc-ripple to help implement this adapter API
* Documents the util APIs in their own subsection

feat(tabs): Add missing docs and create helper util API

---

packages/mdc-menu-surface/README.md
packages/mdc-menu-surface/adapter.js
packages/mdc-menu-surface/constants.js
packages/mdc-menu-surface/foundation.js
packages/mdc-menu-surface/index.js
test/unit/mdc-menu-surface/mdc-menu-surface.test.js
test/unit/mdc-menu-surface/menu-surface.foundation.test.js

Adds a custom event for when the menu is opened to match the event when the menu is closed. 
Focusing a menu item before the menu is opened causes the window to scroll to the initial position of the menu. If the menu is hoisted to the body, it will be initially positioned at the bottom of the page. This PR will cause the menu-surface to emit an event after the menu is opened, so the menu can listen to that event prior to the list item being focused.

feat(menu-surface): Emit an event after the menu is opened

---

.travis.yml
test/screenshot/infra/commands/test.js
test/screenshot/infra/commands/travis.sh

- Runs `npm run build` on external PRs
- Screenshot tests no longer exit before building
- Only runs `test/screenshot/infra/commands/travis.sh` on `TEST_SUITE=screenshot` tests
- Unit tests will no longer fail fast, and will no longer print a meaningful error message
- Skips extracting API credentials and installing/authorizing `gcloud` if required env vars are missing

chore(infrastructure): Build external PRs

---

test/screenshot/infra/commands/serve.js

- Changes `npm start` and `npm run screenshot:serve` console output:
- Makes the top and bottom `===` bars green, and makes their length dynamic
- Bolds/underlines the URL

chore(infrastructure): Colorize `npm start` output

---

test/screenshot/infra/commands/build.js
test/screenshot/infra/commands/proto.js
test/screenshot/infra/lib/cloud-storage.js
test/screenshot/infra/lib/process-manager.js
test/screenshot/infra/types/node-api-externs.js
test/screenshot/run.js

chore(infrastructure): Fail builds/tests on non-zero exit codes

---

karma.conf.js

Also:
- Allows unit tests to run on Sauce Labs without Travis CI:
- Assuming you have the `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` env vars set
- Assuming tunnels to SL are permitted by your organization's security policy

chore(infrastructure): Don't run Chrome headless during SL runs

---

karma.conf.js

Headless chrome should only be used for TravisCI, since locally we need to be able to debug unit tests in a normal chrome browser. 
Fixes: #3217

chore(infrastructure): Add chrome to tests for local debugging

---

test/screenshot/infra/lib/diff-base-parser.js
test/screenshot/infra/lib/git-repo.js
test/screenshot/infra/lib/github-api.js

- (Hopefully) Fixes failing screenshot tests on Travis for merges into `master`
- Uses the `TRAVIS_COMMIT` env var instead of querying `git`
- Looking up the commit with `git rev-parse master` seems to fail on Travis for some reason
- Stops trying to set GitHub commit status if API credentials are not found
- Previously, this would throw an error and kill the whole test
- Adds a bit of logging

chore(infrastructure): Try to fix Travis for merges into master

---

karma.conf.js
test/screenshot/infra/commands/travis.sh
test/screenshot/infra/lib/diff-base-parser.js
test/screenshot/infra/lib/git-repo.js
test/screenshot/infra/lib/github-api.js
test/screenshot/infra/lib/stacktrace.js

This should fix Travis screenshot failures.

Chore(switch): Merge master into switch update

---

karma.conf.js

Updating to windows 10 IE11 fixes 2 failing tests in #3165. Since Windows 10 is our main target, I'm switching SauceLabs to point to Windows 10 IE11.

fix(infrastructure): update saucelabs windows 8 to windows 10 IE11 browser

---

packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/constants.js
packages/mdc-tab/foundation.js
packages/mdc-tab/index.js
test/unit/mdc-tab/foundation.test.js
test/unit/mdc-tab/mdc-tab.test.js

Remove the MDCTab:activated event emitting from the adapter, foundation, and component. Update the readme and tests to reflect the change.

feat(tab): Remove activation event emitting

---

scripts/webpack/js-bundle-factory.js

Webpack wasn't not creating a mdc.list.js file that was transpiled to ES5.

fix(list): add list to webpack js bundler

---

CONTRIBUTING.md
README.md
test/screenshot/infra/lib/github-api.js

Travis CI is migrating all projects from `travis-ci.org` (aka "legacy") to `travis-ci.com`.
I spoke to support@travis-ci.com, and they told me that all open source projects would be automatically migrated to `.com` at EOY 2018, but we could also manually migrate right now.
Rather than waiting for an unexpected migration to break things, I decided to get a head start and do the migration sooner.
* https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

docs: Update Travis CI URLs from legacy .org to new .com

---

test/screenshot/golden.json
test/screenshot/spec/mdc-checkbox/fixture.scss
test/screenshot/spec/mdc-checkbox/mixins/container-colors.html
test/screenshot/spec/mdc-checkbox/mixins/ink-color.html

Adds screenshot test pages for checkbox mixins:
- `mdc-checkbox-container-colors()`
- `mdc-checkbox-ink-color()`

test(checkbox): Add screenshot tests for Sass mixins

---

docs/docsite-tabs.md

It probably makes more sense to redirect straight to tab bar, since that's what most people should be interested in.

docs(tab-bar): Update Tabs redirect to point to Tab Bar

---

demos/menu-surface.html
packages/mdc-menu-surface/README.md
packages/mdc-menu-surface/foundation.js
packages/mdc-menu-surface/index.js
test/unit/mdc-menu-surface/mdc-menu-surface.test.js
test/unit/mdc-menu-surface/menu-surface.foundation.test.js

Completely fixes #2770. 
Adds the ability to specify an absolute x/y that the menu should open to instead of being based on an element's position in the DOM.
Updates/adds a couple unrelated tests for additional coverage.

feat(menu-surface): Add ability to position a menu-surface by x/y

---

packages/mdc-select/mdc-select.scss
packages/mdc-textfield/_mixins.scss

`$has-nested-focusable-element` styles serve no purpose on Text Field and Select since they require JS.

fix(text-field): Stop emitting unused CSS in Text Field & Select

---

scripts/travis-env-vars.sh
test/screenshot/infra/commands/build.js
test/screenshot/infra/commands/serve.js
test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/cbt-api.js
test/screenshot/infra/lib/controller.js
test/screenshot/infra/lib/git-repo.js
test/screenshot/infra/lib/github-api.js
test/screenshot/infra/lib/local-storage.js
test/screenshot/infra/lib/logger.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/lib/selenium-api.js
test/screenshot/infra/lib/stacktrace.js
test/screenshot/infra/types/cbt-externs.js
test/screenshot/infra/types/node-externs.js

- Adds logging for file copy operations and network fetches to help debug slow/flaky Travis builds
- Adds `Logger.debug()` method which prints the amount of time elapsed since the previous call
- Fixes typo that prevented PRs with only `.scss` files from being screenshot tested ([example](https://travis-ci.com/material-components/material-components-web/jobs/138129432))
- Fixes `master` diff report bug by only added _existing_ screenshots to the "unchanged" list. Previously, newly-added screenshots were listed under "unchanged" in addition to "added".
- Fixes missing `await` inside `try` statements that return a `Promise`
- Fixes `spawn E2BIG` error when the local repo has a lot of ignored files
- Fixes `GitHubApi.createPullRequestComment()` so that it exits early if it's not …

chore(infrastructure): Add fs/network logging; fix bugs

---

demos/text-field.html
demos/typography.html
packages/mdc-list/README.md
packages/mdc-textfield/helper-text/README.md
packages/mdc-typography/_mixins.scss

Flexbox works differently with pseudo elements on Chrome/FF vs IE/Edge. Reverted mixin to use display inline-block.
BREAKING CHANGE: Updates to typography baseline mixin which requires the text element to strip the white-space. Helper text and MDC List two line text should strip the white-space.

fix(typography): Reverted baseline mixin to use display inline-block

---

test/screenshot/infra/lib/user-agent-store.js

Significantly improves rendering speed and scrolling performance on the report page.
Should also speed up rendering of "Details" element in GitHub PR comments.

chore(infrastructure): Use PNG instead of SVG for browser icons

---

packages/mdc-tab-bar/README.md
packages/mdc-tab/README.md
test/unit/mdc-tab/mdc-tab.test.js

Demos already use spans in these instances, but the READMEs and test fixture documented div elements inside the button element, which is invalid.
Fixes #3301.

docs(tab): Fix tab markup to avoid div inside button

---

test/screenshot/spec/fixture.js

Adds a `500ms` delay before setting `data-fonts-loaded` on the `<body>`.
This is needed to reduce MS Edge font rendering flakiness in #3306.

chore(infrastructure): Add `fontsLoaded` Promise & delay to `fixture.js`

---

packages/mdc-list/README.md
packages/mdc-list/constants.js
packages/mdc-list/index.js
test/unit/mdc-list/mdc-list.test.js

Updates the enabled items selector to search for descendant elements of `.mdc-list-item` instead of all `a` and `button` elements. 
Updates Readme demo to show `tabindex=0` for the first element that should be in tab order for single selection lists. 
Updates the list component to default to vertical list if `aria-orientation` is not present or is misspelled.
Adds unit test for instantiating the component with various `aria-orientation` values.

fix(list): Update clickable elements selector

---

packages/mdc-checkbox/_variables.scss
packages/mdc-checkbox/mdc-checkbox.scss
packages/mdc-radio/mdc-radio.scss
packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation.test.js

Ripple JS logic has historically always completely short-circuited browsers that don't support CSS variables. This changes it to still set up focus and blur handling, for the sake of components with complex DOM structure where a focusable element is not the root element of the ripple.
This also updates checkbox and radio styles to avoid applying their unique CSS-only focus styles to instances with JS ripples... and also fixes those CSS-only focus styles to use the same opacity as the JS ripples.
Fixes #3212.

fix(ripple): Register focus/blur handlers in IE

---

demos/card.html
demos/icon-button.html
demos/theme/index.html
packages/material-components-web/README.md
packages/mdc-card/README.md
packages/mdc-icon-button/README.md
packages/mdc-icon-button/adapter.js
packages/mdc-icon-button/constants.js
packages/mdc-icon-button/foundation.js
packages/mdc-icon-button/index.js
packages/mdc-icon-button/mdc-icon-button.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-card/classes/baseline.html
test/screenshot/spec/mdc-icon-button/classes/baseline-icon-button-toggle.html
test/screenshot/spec/mdc-icon-button/fixture.scss
test/unit/mdc-icon-button/foundation.test.js
test/unit/mdc-icon-button/mdc-icon-button-toggle.test.js

fixes: #3277 , resolves #3154, resolves #3107
BREAKING CHANGE: Removes the previous `data` attributes and no longer dynamically changes the label. Allows developers to add both elements to the button, with one indicated as the `on` state by using a `data-toggle-on` attribute. State is now changed by adding/removing the `mdc-icon-button--on` class to the `mdc-icon-button` element. All icon elements should have the `mdc-icon-button__icon` class.

feat(icon-button): Add SVG support

---

test/screenshot/diffing.json
test/screenshot/golden.json
test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/lib/report-writer.js
test/screenshot/infra/proto/mdc.pb.js
test/screenshot/infra/proto/mdc.proto

- Disables 7 `mdc-typography` and `mdc-text-field--textarea` tests in Edge
- Even with **6** retries, Edge was still flaking frequently enough to fail lots of tests:
- https://travis-ci.com/material-components/material-components-web/jobs/139469358
- https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/08/11/18_50_20_627/report/report.html
- More examples of flaky diffs:
- [4 diffs](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/08/08/03_20_16_788/report/report.html)
- [4 diffs](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/08/08/03_58_53_044/report/report.html)
- [4 diffs](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/08/08/04_01_04_052/report/report.html)
- [4 …

chore(infrastructure): Disable flaky Edge tests

---

packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/constants.js
packages/mdc-tab/foundation.js
packages/mdc-tab/index.js
packages/mdc-tab/mdc-tab.scss
test/unit/mdc-tab/foundation.test.js
test/unit/mdc-tab/mdc-tab.test.js

Also removes unnecessary `animating` classes and `transitionend` handler.
Refs #2813 for Tab.
Fixes #3316.
BREAKING CHANGE: Removes handleTransitionEnd foundation API. Removes [de]registerEventHandler adapter API. Event registration is now the component's responsibility.

feat(tab): Move event registration to component

---

test/screenshot/golden.json
test/screenshot/spec/fixture.scss
test/screenshot/spec/mdc-linear-progress/classes/baseline.html
test/screenshot/spec/mdc-linear-progress/fixture.js
test/screenshot/spec/mdc-linear-progress/fixture.scss
test/screenshot/spec/mdc-linear-progress/mixins/bar-color.html
test/screenshot/spec/mdc-linear-progress/mixins/buffer-color.html

IE 11 💩  renders `mdc-linear-progress--reversed` incorrectly. This is being tracked in #3344.

test(linear-progress): Add screenshot tests

---

packages/mdc-dialog/foundation.js
test/unit/mdc-dialog/foundation.test.js

fix(dialog): Expose numbers on foundation

---

test/screenshot/golden.json
test/screenshot/spec/fixture.scss
test/screenshot/spec/mdc-linear-progress/classes/baseline.html
test/screenshot/spec/mdc-linear-progress/fixture.js
test/screenshot/spec/mdc-linear-progress/mixins/bar-color.html
test/screenshot/spec/mdc-linear-progress/mixins/buffer-color.html

- Adds an "Enable animation" checkbox to `linear-progress` pages:
- For screenshot test pages to replace demo pages, we need to be able to manually verify animations. However, we also need to ensure consistent rendering for screenshot tests.
- The checkbox is positioned _outside_ the green cropping border, so it does not appear in screenshot images.
- Checkbox state is synchronized with a URL param to enable persistence between reloads and linking to a specific state (e.g., [animation enabled](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/08/14/18_05_33_820/spec/mdc-linear-progress/classes/baseline.html?enable_animation=true) vs. [animation disabled](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/08/14/18_05_33_820/spec/mdc-linear-progress/classes …

chore(infrastructure): Add "enable animation" checkbox

---

test/screenshot/infra/lib/cbt-api.js
test/screenshot/infra/lib/report-writer.js
test/screenshot/infra/lib/selenium-api.js
test/screenshot/infra/proto/mdc.pb.js
test/screenshot/infra/proto/mdc.proto

When a CBT browser VM starts or terminates, we now print the browser's:
- Selenium session ID (e.g., `a149dd53-b1c6-4ea8-9fc5-9b68c1eefc89`)
- Public CBT result page URL (e.g., [Chrome 68 on Windows 10](https://app.crossbrowsertesting.com/public/ib956cb930a76197/selenium/13590389/))
In addition, the browser icons in the "Metadata" section of the [report page](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/08/15/21_24_46_592/report/report.html) now link to their corresponding CBT test result pages. The pages are public and contain a video capture of each test.
This makes it much easier to debug flaky tests and report errors to CBT.

chore(infrastructure): Log Selenium session ID and public CBT URL

---

README.md

We only have a `chat` badge to link to our discord channel. Just adding this section to increase visibility.

docs: add a Need Help section to main Readme to add discord

---

packages/mdc-tab-bar/README.md

AFAICT the icon won't render w/o the `material-icons` class. /cc @filiph @Sfshaza

Add missing material-icons class to tab-bar example

---

packages/mdc-tab/README.md

AFAICT the icon won't render w/o the `material-icons` class. /cc @filiph @Sfshaza

Add missing material-icons class to tab example

---

packages/mdc-tab-bar/README.md
packages/mdc-tab-bar/adapter.js
packages/mdc-tab-bar/foundation.js
packages/mdc-tab-bar/index.js
packages/mdc-tab/README.md
test/unit/mdc-tab-bar/foundation.test.js
test/unit/mdc-tab-bar/mdc-tab-bar.test.js

Move the job of calling `activateTab` into an adapter method instead of directly in the foundation's handler methods. In the React wrapper, handler methods should only update props. `activateTab` will then be called in the `componentDidUpdate` lifecycle method. 
Also rename `getActiveTabIndex` to `getPreviousActiveTabIndex` to disambiguate. React wrapper stores the previous active index in state and returns it in this adapter method.

fix(tab-bar): Move activateTab to adapter

---

packages/mdc-list/README.md
packages/mdc-list/adapter.js
packages/mdc-list/foundation.js
packages/mdc-list/index.js
test/unit/mdc-list/foundation.test.js
test/unit/mdc-list/mdc-list.test.js

`MDCListAdapter.isElementFocusable` was never actually called from `MDCListFoundation`

chore(list): Remove dead code

---

packages/mdc-list/README.md
packages/mdc-list/adapter.js
packages/mdc-list/foundation.js
packages/mdc-list/index.js
test/unit/mdc-list/foundation.test.js
test/unit/mdc-list/mdc-list.test.js

Fixes #3406.
I also tested this by cherry-picking it into the feat/navigation-drawer branch, adding a unique hash to one of the drawer links, and testing click vs. space/enter, and both work (and also emit click events).
I also fixed formatting of a few test names and Sublime Text automatically removed some trailing whitespace (how'd all that get in there).
BREAKING CHANGE: Adds a followHref adapter API.

fix(list): Follow hrefs on keypresses on links

---

packages/mdc-textfield/README.md

Currently the Web Text Field page on material.io has this image:
(Note: the background of the image blends in with the background of the area it occupies in the page; this is showing the old default variant, not filled.)
We've removed that variant as it's no longer in spec, and currently don't have infrastructure to quickly update this image, so I'm removing it to avoid confusion.

docs(text-field): Remove outdated image

---

packages/mdc-icon-button/README.md

Updating to match demo code.
- Use `mdc-icon-button__icon--on` for `favorite`, instead of `favorite_border`.

docs(icon-button): Update icon button variant example

---

docs/open_source/release-process.md

Hopefully fixing these docs once and for all.
A couple of months back, I got confused when I noticed that selecting Pre-Minor for a second pre-release would actually rev the minor version number, which we don't want. In that particular case we should select Prerelease which revs the existing pre-release version number.

docs: Update pre-release docs RE lerna option to pick

---

docs/open_source/release-process.md

I didn't have the latest tags and lerna failed as a result since I was using the `--since` option.

docs: Update release-process docs to include fetching tags

---

test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/analytics.js
test/screenshot/infra/lib/cbt-api.js
test/screenshot/infra/lib/cli.js
test/screenshot/infra/lib/github-api.js
test/screenshot/infra/lib/golden-file.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/lib/selenium-api.js
test/screenshot/infra/proto/mdc.pb.js
test/screenshot/infra/proto/mdc.proto

* Adds [custom GA params](https://support.google.com/analytics/answer/1033863?hl=en) to user-facing URLs:
- HTML files displayed in:
- Console output
- GitHub PR status checks
- GitHub PR report comments
- `golden.json`'s `public_url` field
- CBT Selenium tests
- Params:
- `utm_source=cbt&utm_content=selenium`
- `utm_source=cli&utm_content=inventory`
- `utm_source=cli&utm_content=progress`
- `utm_source=github&utm_content=pr_status`
- `utm_source=github&utm_content=pr_comment`
- `utm_source=golden_json`
* Colorizes the output so that the URLs are still readable (by dimming the query portion in gray)
* Removes noisy `CROP: https://...` lines from console output

chore(infrastructure): Add URL params for Google Analytics

---

packages/mdc-select/index.js
test/unit/mdc-select/mdc-select.test.js

Modifies the line ripple logic in the `select` to only add the event listeners or updates if the line ripple element exists.

fix(select): Only add line ripple listeners when line ripple is present

---

packages/mdc-drawer/index.js
test/unit/mdc-drawer/mdc-drawer.test.js

refs: #3471 
List was being instantiated in the `init` but never destroyed.

fix(drawer): Destroy list in destroy method

---

packages/mdc-typography/README.md

Map items are separated with comma and not semicolon, quotes should be unquoted.
```
$map: (key1: value1, key2: value2, key3: value3);
```
https://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps

doc(typography): Fix styles examples

---

test/screenshot/infra/lib/cli.js
test/screenshot/infra/lib/selenium-api.js

- Colorizes log output:
- URL params: dimmer
- User agent alias: bold + italic
- Image dimensions: bold
- Changes `FAILED` to `ERROR` (shown when an error is thrown during a Selenium session)
- Refactors `SeleniumApi.takeScreenshotWithRetries_()` into `logRetry_()`

chore(infrastructure): Render important info in bold in log output

---

test/screenshot/infra/lib/cli.js
test/screenshot/infra/lib/selenium-api.js

Running 3 parallel browsers is a waste of resources.
`npm run screenshot:test` captures screenshots in 4 browsers, so it takes the same amount of time to finish whether it run 2 or 3 browsers in parallel.
By only consuming 2 parallels, we free up a VM for someone else to use.
As before, the `--parallels=N` CLI flag can be used to override the default.

chore(infrastructure): Run 2 parallel browsers by default instead of 3

---

packages/mdc-line-ripple/foundation.js
packages/mdc-list/foundation.js

This solves the mystery in https://github.com/material-components/material-components-web/pull/3516#discussion_r215364312.
All of our foundation constructors follow the pattern of calling `super(Object.assign(MDCFooFoundation.defaultAdapter, adapter))`, but two components in particular (three if you include the Dialog prototype) were also assigning an empty object as the default value, which caused coverage to decrease due to the default "branch" never being taken. The default assignment is not necessary, since `Object.assign` effectively no-ops on `undefined` sources anyway.

chore: Remove unnecessary default arguments that affect coverage

---

packages/mdc-theme/_variables.scss

To allow customization SASS variables should be declared as `!default`

fix(theme): Declare error variables as !default

---

packages/mdc-ripple/foundation.js
test/screenshot/golden.json

Used to update the FF screenshots on CBT since something changed and all FF screenshots are rendering slightly differently (likely a browser, VM upgrade).

fix(infrastructure): Update ff screenshot tests

---

packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation.test.js

This is analogous to #2490, except for the deactivation timer rather than the activation timer.
Fixes #3527.

fix(ripple): Clean deactivation timer and CSS when interrupted

---

scripts/cherry-pick-patch-commits.js
test/screenshot/report/report.scss

This fixes the cherry-pick-patch-commits script to work when the last release tag is off-master (which typically happens when there was a previous patch release).
If you run the current script on master right now, you'll immediately see odd errors with cherry-picks. What's happening is the script attempts to cherry-pick things that were already cherry-picked, because attempting to log commits between an off-master patch release and master results in listing all commits since the two references diverged, which is typically the last .0 release.
The fix involves the following:
* Detect when the last release is off-branch (by checking if `git branch --points-at HEAD --contains <tag>` returns the current branch)
* For off-branch patch tags, resolve to the equivalent commit in history (this is …

chore: Support cherry-picking from tags not in master

---

test/screenshot/infra/commands/test.js

This should at least enable the screenshot CI task to pass again.
Refs #3555.

chore: Skip comparing against master screenshots

---

packages/mdc-drawer/README.md

Someone on Discord ended up confused trying to apply our drawer examples because the focus examples reference `drawerEl` but that's never defined in our JS initialization example.
Given that our initialization example already assumes a single drawer, I just changed the other examples to use `document.querySelector` since they're otherwise already using specific enough selectors to work. I also changed `document.body.querySelector` to just `document.querySelector` for consistency.

docs(drawer): Improve continuity between examples

---

packages/mdc-tab-bar/index.js

fixes: #3570 
Trailing commas are not officially supported until ES 2017.

fix(tab-bar): Remove trailing comma from function.

---

packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss
packages/mdc-chips/_variables.scss
packages/mdc-chips/chip/mdc-chip.scss

This is necessary for handling the case where an input chip needs to have a box-shadow transition. If mdc-elevation-transition-value() is used on its own without this, it overrides the .mdc-chip--exit transition and input chips don't animate out properly.

feat(chips): Add a mixin to handle chip elevation transitions

---

packages/mdc-dialog/README.md
packages/mdc-dialog/adapter.js
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
test/screenshot/golden.json
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-dialog/mdc-dialog.test.js

Fixes #3561.
BREAKING CHANGE: Adds hasClass and reverseButtons adapter APIs.

feat(dialog): Reverse buttons when stacked; allow toggling auto-stack

---

packages/mdc-dialog/mdc-dialog.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-dialog/classes/baseline-alert-with-title.html

Note: This is based on the dialog-stacked-reverse branch since that already has other golden updates.
This fixes the following:
* Increases spacing between top of dialog and body text when there is no title
* Reduces spacing between title and body text to get as close to spec as possible for alert dialogs
* In particular, however, the specs WRT simple vs. alert dialogs seem to contradict each other in terms of how much space is between title and content
* Reduces spacing when dialog is scrollable to match spec
* Also eliminates padding from MDC List for confirmation dialogs, since Dialog styles already add content padding
I've updated goldens, but I think it's out of sync, because the screenshot test report showed "added" chips screenshot tests which are already in master. I'll have to …

fix(dialog): Conform more closely with spec

---

packages/mdc-ripple/foundation.js
packages/mdc-ripple/util.js

After attempting to port MDCRipple to TypeScript, I found the typing of ripple to be unclear or wrong. This PR cleans up the typing of MDCRipple. Some of the main offenders were the `activate` and `deactivate` methods, which took *three* different types: `Event|null|undefined`. I've cleaned them up to only take two types, `Event|undefined`, by removing `null`.

chore(ripple): Clean up types

---

packages/mdc-chips/package.json
packages/mdc-drawer/package.json
packages/mdc-floating-label/package.json
packages/mdc-menu/package.json
packages/mdc-slider/package.json

I ran into these when testing my [symlink script](https://gist.github.com/kfranqueiro/d06c7073c5012de3edb6c5875d6a4a50) with the Catalog.
I'm a bit baffled as to how these weren't caught by anything else...

chore: Fix missing package dependencies

---

packages/mdc-list/foundation.js
test/unit/mdc-list/foundation.test.js

I encountered this issue while attempting some approaches for lists in dialogs.
Currently, if single-selection mode isn't enabled, links don't get followed. I'm pretty sure they ought to be followed regardless.
I also noticed another test was accidentally testing the enter key twice instead of enter and space.

fix(list): Always call followHref regardless of single-selection mode

---

packages/mdc-dialog/README.md
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
test/screenshot/spec/mdc-dialog/classes/baseline-confirmation.html
test/screenshot/spec/mdc-dialog/classes/baseline-simple.html
test/screenshot/spec/mdc-dialog/fixture.js
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-dialog/mdc-dialog.test.js

Fixes #3592.
Also adds a couple of tests for `autoStackButtons` that I apparently missed before.

feat(dialog): Integrate with MDC List; add keyboard action handling

---

scripts/travis-env-vars.sh
test/screenshot/golden.json
test/screenshot/spec/mdc-dialog/classes/baseline-alert-with-title.html
test/screenshot/spec/mdc-dialog/classes/baseline-alert.html
test/screenshot/spec/mdc-dialog/classes/baseline-confirmation.html
test/screenshot/spec/mdc-dialog/classes/baseline-simple.html
test/screenshot/spec/mdc-dialog/classes/manual-window-resize.html
test/screenshot/spec/mdc-dialog/classes/overflow-accessible-font-size.html
test/screenshot/spec/mdc-dialog/classes/overflow-bottom.html
test/screenshot/spec/mdc-dialog/classes/overflow-top.html
test/screenshot/spec/mdc-dialog/fixture.js
test/screenshot/spec/mdc-dialog/mixins/container-fill-color.html
test/screenshot/spec/mdc-dialog/mixins/content-ink-color.html
test/screenshot/spec/mdc-dialog/mixins/corner-radius.html
test/screenshot/spec/mdc-dialog/mixins/max-height.html
test/screenshot/spec/mdc-dialog/mixins/max-width.html
test/screenshot/spec/mdc-dialog/mixins/min-width.html
test/screenshot/spec/mdc-dialog/mixins/scrim-color.html
test/screenshot/spec/mdc-dialog/mixins/scroll-divider-color.html
test/screenshot/spec/mdc-dialog/mixins/title-ink-color.html

- Reduces text rendering flakiness on dialog pages in IE 11 💩, Edge, and Firefox
- Avoids reflow by adding CSS classes directly to the HTML:
- `mdc-dialog--open`
- `mdc-dialog-scroll-lock` (without this, scrollbars flicker in IE 11 💩 and Edge)
- Fixes a broken regex that caused screenshot tests to be skipped on PRs that only have HTML or YAML file changes 😞

chore(infrastructure): Reduce dialog flakiness by avoiding reflow

---

packages/mdc-dialog/README.md
packages/mdc-dialog/adapter.js
packages/mdc-dialog/constants.js
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
test/screenshot/spec/mdc-dialog/classes/baseline-confirmation.html
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-dialog/mdc-dialog.test.js

Fixes #3593.
Implements default action via a CSS modifier class that can be added to one of the buttons in the actions area of the dialog. If present, pressing enter while focused in the dialog will equate to clicking that button, unless:
* The keypress came from an excluded element e.g. a textarea or MDC Menu item
* The default button is disabled (in which case calling `click` does nothing)
This can be tested live via the baseline-confirmation screenshot test page.
This adds an adapter API and changes another, but this is already encompassed under the general breaking change note for the new Dialog implementation.

feat(dialog): Support default action button

---

packages/mdc-dialog/README.md
test/screenshot/spec/mdc-dialog/classes/baseline-confirmation.html
test/screenshot/spec/mdc-dialog/classes/baseline-simple.html

* add `mdc-list-item__text` where missing
* remove extra tabindex attributes

docs(dialog): Fix list item markup in docs and tests

---

test/screenshot/golden.json
test/screenshot/spec/mdc-dialog/classes/baseline-alert-above-drawer.html
test/screenshot/spec/mdc-dialog/classes/manual-window-resize.html
test/screenshot/spec/mdc-dialog/classes/overflow-accessible-font-size.html
test/screenshot/spec/mdc-dialog/classes/overflow-bottom.html
test/screenshot/spec/mdc-dialog/classes/overflow-top.html
test/screenshot/spec/mdc-dialog/mixins/container-fill-color.html
test/screenshot/spec/mdc-dialog/mixins/content-ink-color.html
test/screenshot/spec/mdc-dialog/mixins/corner-radius.html
test/screenshot/spec/mdc-dialog/mixins/max-height.html
test/screenshot/spec/mdc-dialog/mixins/max-width.html
test/screenshot/spec/mdc-dialog/mixins/scrim-color.html
test/screenshot/spec/mdc-dialog/mixins/scroll-divider-color.html
test/screenshot/spec/mdc-dialog/mixins/title-ink-color.html

Redacts the word "Dumas" from dialogs in MS Edge because it's causing a lot of flaky diffs.
The letter "u" shifts by 1px.
Example:
* [Diff report](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/09/21/22_15_48_632/report/report.html?utm_source=cli&utm_content=test_results)
* [Travis CI job log](https://travis-ci.com/material-components/material-components-web/jobs/147298739)
This PR also adds missing CSS classes to `baseline-alert-above-drawer.html`,
which significantly reduces flakiness in IE 11 💩 and Edge.
Examples:
* [`2018/09/21/23_16_17_667`](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/09/21/23_16_17_667/report/report.html?utm_source=cli&utm_content=test_results)
* [`2018/09/21/23_20_38_796`](https://storage.googleapis.com/mdc-web-screensho …

chore(infrastructure): Redact flaky dialog text in Edge

---

packages/material-components-web/material-components-web.scss

I could've sworn I saw this in one of the other shape PRs originally, but we somehow missed removing this reference from material-components-web.scss, which breaks the build/dist targets for the all-in-one package, because there are no longer any emitted shape styles OOTB.

fix(shape): Remove reference from MCW package

---

demos/button.html
demos/button.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-button/mixins/shape-radius.html
test/screenshot/spec/mdc-card/mixins/mixins.html
test/screenshot/spec/mdc-chips/mixins/shape-radius.html
test/screenshot/spec/mdc-dialog/mixins/shape-radius.html
test/screenshot/spec/mdc-image-list/fixture.scss
test/screenshot/spec/mdc-image-list/mixins/standard-shape-radius.html
test/screenshot/spec/mdc-image-list/mixins/standard-with-text-protection-shape-radius.html
test/screenshot/spec/mdc-select/fixture.scss
test/screenshot/spec/mdc-select/mixins/shape-radius.html

Note: This is based on #3552, so review after that's merged. (I'm running it against feat/shape so it runs screenshot tests.)

Rename corner -> shape in tests

---

packages/mdc-dialog/README.md
packages/mdc-dialog/mdc-dialog.scss
test/screenshot/spec/mdc-dialog/classes/baseline-alert-above-drawer.html
test/screenshot/spec/mdc-dialog/classes/baseline-alert-with-title.html
test/screenshot/spec/mdc-dialog/classes/baseline-alert.html
test/screenshot/spec/mdc-dialog/classes/baseline-confirmation.html
test/screenshot/spec/mdc-dialog/classes/baseline-simple.html
test/screenshot/spec/mdc-dialog/classes/manual-window-resize.html
test/screenshot/spec/mdc-dialog/classes/overflow-accessible-font-size.html
test/screenshot/spec/mdc-dialog/classes/overflow-bottom.html
test/screenshot/spec/mdc-dialog/classes/overflow-top.html
test/screenshot/spec/mdc-dialog/mixins/container-fill-color.html
test/screenshot/spec/mdc-dialog/mixins/content-ink-color.html
test/screenshot/spec/mdc-dialog/mixins/corner-radius.html
test/screenshot/spec/mdc-dialog/mixins/max-height.html
test/screenshot/spec/mdc-dialog/mixins/max-width.html
test/screenshot/spec/mdc-dialog/mixins/min-width.html
test/screenshot/spec/mdc-dialog/mixins/scrim-color.html
test/screenshot/spec/mdc-dialog/mixins/scroll-divider-color.html
test/screenshot/spec/mdc-dialog/mixins/title-ink-color.html

Fixes #3620, #3621.
Also fixes a lint error that somehow snuck through.
Note: View this PR with `?w=1` in the URL to make it easier to see the diff (ignoring indentation changes).

docs(dialog): Fix markup in docs and tests

---

test/screenshot/infra/commands/test.js
test/screenshot/infra/lib/analytics.js
test/screenshot/infra/lib/github-api.js
test/screenshot/infra/lib/report-builder.js
test/screenshot/infra/lib/selenium-api.js

`utm_medium` is displayed prominently in the Google Analytics console, whereas `utm_content` is harder to find.

chore(infrastructure): Fix analytics URLs

---

test/screenshot/infra/lib/selenium-api.js

Increases the default number of parallel CBT browsers from **`2`** to **`4`** when running outside of \
normal business hours (M–F 9–6).
This saves about 5–10 minutes on each Travis job.
When nobody else is running screenshot tests:
* **Outside of normal business hours** (evenings and weekends):\
Defaults to **`4`** parallel browsers 🆕
* **During normal business hours** (Monday through Friday, 9am EST to 6pm PST): \
Defaults to **`2`** parallel browsers (same behavior as before)
When other users are already running screenshot tests:
* **Any day/time**: \
Defaults to **`1`** parallel browser (same behavior as before)
Just like before, you can override the default number of parallels with the `--parallels=N` CLI option:
```bash
npm run screenshot-test -- --parallels=4
```

chore(infrastructure): Increase max CBT parallels off-hours

---

scripts/travis-env-vars.sh
test/screenshot/infra/lib/selenium-api.js

Fixes oversights in #3652:
* Fixes `SATURDAY` value
* Explicitly sets timezone in Travis CI by adding `export TZ=America/Los_Angeles` to `scripts/travis-env-vars.sh`
* Prints current date and timezone to terminal in `scripts/travis-env-vars.sh`

chore(infrastructure): Set timezone & fix date calc

---

test/screenshot/infra/lib/cbt-api.js
test/screenshot/infra/lib/constants.js

- Retries failed CBT HTTP requests up to 5 times
- Mitigates CBT's and Travis CI's intermittent network flakiness
- Kills stalled Selenium sessions that have not received any commands

chore(infrastructure): Retry failed CBT HTTP requests

---

app.yaml
demos/README.md
demos/redirect.html
docs/code/readme_template.md
docs/open_source/README.md
docs/open_source/release-process.md

[Appspot](http://material-components-web.appspot.com/) demo page now redirects to [catalog](https://material-components.github.io/material-components-web-catalog/) demo page.

chore: Remove reference to appspot demo server.

---

packages/mdc-dialog/README.md
packages/mdc-dialog/adapter.js
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
test/unit/mdc-dialog/foundation.test.js
test/unit/mdc-dialog/mdc-dialog.test.js

Fixes #3676 for Dialog.
Firefox needs a rAF + setTimeout to animate properly (possibly related [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=731974) and [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Performance_best_practices_for_Firefox_fe_engineers#How_do_I_avoid_triggering_uninterruptible_reflow)).

fix(dialog): Wait for rAF/timeout to apply open class

---

packages/mdc-ripple/_mixins.scss

Context: https://github.com/material-components/material-components-web-codelabs/pull/66#pullrequestreview-160820735
Reproducible within MDC Web using the drawer screenshot pages or demos/list.html. (Slowing down animations to 25% or 10% helps.)

fix(ripple): Transition background-color to avoid flashes

---

test/screenshot/diffing.json
test/screenshot/infra/lib/cbt-api.js
test/screenshot/infra/lib/report-writer.js
test/screenshot/infra/lib/selenium-api.js

- Fixes bug in detection of stalled/zombie Selenium sessions
- Adds missing `else` statement
- Disables Dialog and Drawer test pages in Edge until font loading flakiness is resolved
- Formats # of screenshots on diff report page (e.g., "1234" -> "1,234")
- Adds # of diffs to CLI output

chore(infrastructure): Fix zombie detection

---

docs/open_source/triage.md

We're now planning to rely on GitHub milestones rather than Pivotal. I renamed the in-tracker tag to icebox so we can use it for that purpose, and move things into release milestones to use as the backlog.

docs: Update triage links for new label name and milestone usage

---

packages/mdc-drawer/dismissible/mdc-drawer-dismissible.scss

Realized this was unused while thinking about what would be shared by Side Sheet.
There is already an exclusion for the --closing modifier class within the rest of drawer's styles, so the only thing this is overriding is another 0 margin style.

fix(drawer): Remove redundant style

---

packages/mdc-ripple/foundation.js
test/unit/mdc-ripple/foundation-deactivation.test.js

Fixes #3524.
While testing I wasn't able to get tap-hold to bring up the context menu at all on mobile for some reason... but I confirmed that this fixes the issue for right-click in Chrome and Safari on OS X, which are the only browsers I could reproduce it on.
OS | Browser | Before | After
--- | --- | --- | ---
OS X | Chrome | Buggy | OK
OS X | Safari | Buggy | OK
OS X | Firefox | OK | OK
Win10 | Chrome | OK | OK
Win10 | Firefox | OK | OK
Win10 | Edge | OK | OK
Tested on Win10 with both mouse and touch. IE is N/A because it doesn't use JS for ripple effect.

fix(ripple): Deactivate on contextmenu event

---

packages/mdc-radio/README.md
packages/mdc-radio/adapter.js
packages/mdc-radio/foundation.js
packages/mdc-radio/index.js
test/unit/mdc-radio/foundation.test.js
test/unit/mdc-radio/mdc-radio.test.js

fixes https://github.com/material-components/material-components-web/issues/3763
related https://github.com/material-components/material-components-web/issues/2684 
BREAKING CHANGE: Removed `getNativeControl` from adapter, and subsequent foundation methods that called `getNativeControl`. Foundation methods removed: `isChecked`, `setChecked`, `isDisabled`, `getValue`, `setValue`.

fix(radio): remove getNativeControl from adapter

---

packages/mdc-notched-outline/README.md
packages/mdc-notched-outline/_functions.scss
packages/mdc-notched-outline/_variables.scss
packages/mdc-notched-outline/constants.js
packages/mdc-notched-outline/foundation.js
packages/mdc-select/_mixins.scss
packages/mdc-select/_variables.scss
packages/mdc-select/mdc-select.scss
packages/mdc-shape/README.md
packages/mdc-shape/_functions.scss
packages/mdc-shape/_mixins.scss
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/mdc-text-field.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-select/fixture.scss
test/screenshot/spec/mdc-textfield/fixture.scss
test/screenshot/spec/mdc-textfield/mixins/outline-shape-radius.html

This change fixes the issue where notched outline overlaps with floating label on text field & select components.
Notch position is calculated based on the corner size of notched outline and accordingly the shape mixins in text field and select components sets the floating label position based on radius size.
The leading stroke length is calculated with: `Math.max(0, numbers.MIN_LEADING_STROKE_EDGE_POSITION - radius - 1.2)` which gets shrunk when large radius is used.
The floating label position calculation with: `$cornerSize + $leadingStrokeLength + $mdc-notched-outline-notch-gutter-size + 1.2` where `$leadingStrokeLength` is the stroke length that applies the same formula as above.
Fixes #3158, #3936

fix(notched-outline): Auto position the notch and floating label based on corner size

---

packages/mdc-drawer/modal/foundation.js

Modal Drawer extends Dismissible Drawer. There's no need for an adapter generic assignment.

fix(drawer): Remove unnecessary Closure annotation

---

packages/mdc-menu/README.md
packages/mdc-menu/foundation.js
test/unit/mdc-menu/menu.foundation.test.js

Exposing `handleSelection` to public for web frameworks which doesn't have access to events triggered by inner child component such as list component.
- `handleSelection_(listItem: Element)` => `handleSelection(listItem: Element)`

feat(menu): Expose handleSelection API to public

---

package.json
packages/mdc-side-sheet/README.md
packages/mdc-side-sheet/_mixins.scss
packages/mdc-side-sheet/_variables.scss
packages/mdc-side-sheet/mdc-side-sheet.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-side-sheet/fixture.scss
test/screenshot/spec/mdc-side-sheet/mixins/stroke-color.html

Refs #3742.
This removes opacity parameters to match how drawer's mixin APIs are currently exposed (with the reasoning that it's easier to add later than remove), and reorganizes some styles to make them reusable between side sheet and drawer.

feat(side-sheet): Make mixins more consistent with Drawer

---

packages/mdc-drawer/README.md

Resolves a comment on another PR: https://github.com/material-components/material-components-web/pull/3947#discussion_r227064522
It makes more sense to fix this in master rather than hold it back in the side sheet branch.

docs(drawer): Rename icon heading to make more sense contextually

---

packages/mdc-notched-outline/mdc-notched-outline.scss

Add the `@noflip` annotation to the notched outline Sass in RTL. This is necessary for closure stylesheets.

fix(notched-outline): Add noflip annotation

---

packages/mdc-select/README.md
packages/mdc-select/adapter.js
packages/mdc-select/foundation.js
packages/mdc-select/index.js
test/unit/mdc-select/mdc-select.test.js

Fixes #3728.
Rearranges README content regarding the enhanced select to its own variant section, adds some notes around usability trade-offs, and also moves the accessibility example into there as well.
Also fixes a few mistyped `mdc-list-item` classnames I noticed.
While reviewing the README, I found an opportunity to simplify one of the new APIs (`notifyChange`) so I added that here as well, in a separate commit.
This PR is currently based on the branch for #3986 since that also had readme changes, so we can hopefully merge these in order.

docs(select): Reorganize / clean up enhanced select docs

---

packages/mdc-select/README.md
packages/mdc-select/adapter.js
packages/mdc-select/constants.js
packages/mdc-select/foundation.js
packages/mdc-select/index.js
test/unit/mdc-select/mdc-select-enhanced.test.js
test/unit/mdc-select/mdc-select.test.js

Fixes #3729.
Currently comparing against add-invalid branch since I wrote it on top of that.

feat(select): Support synchronizing enhanced select w/ hidden input

---

packages/mdc-select/README.md

Our Select JS example was using global namespace syntax, inconsistent with the rest of our READMEs.
(This was already the case prior to the enhanced select work, and went unnoticed during that.)
Fixes #3995.

docs(select): Update module format used in JS example

---

packages/mdc-drawer/common.scss
packages/mdc-fab/README.md
packages/mdc-fab/_mixins.scss
packages/mdc-shape/_functions.scss
packages/mdc-snackbar/package-lock.json
test/screenshot/golden.json
test/screenshot/spec/mdc-fab/fixture.scss
test/screenshot/spec/mdc-fab/mixins/extended-shape-radius.html
test/screenshot/spec/mdc-fab/mixins/shape-radius.html

BREAKING CHANGE: Fab now has 2 separate mixins - `mdc-fab-shape-radius` for regular & mini Fab variants & `mdc-fab-extended-shape-radius` for Extended FAB variant. 
Before:
```
mdc-fab-shape-radius(50%) => border-radius: 28px;
```
After:
```
mdc-fab-shape-radius(50%) => border-radius: 50%;
```
Where, `mdc-fab-shape-radius` doesn't resolve percentage to absolute value.
- `mdc-fab-shape-radius` sets rounded shape to regular & mini FAB.
- `mdc-fab-extended-shape-radius`sets rounded shape to only Extended FAB.
Fixes #3989

fix(fab): Separate mixins for regular FAB and Extended FAB

---

packages/mdc-menu/README.md
packages/mdc-menu/index.js
packages/mdc-select/index.js
test/unit/mdc-menu/mdc-menu.test.js

Added new API to menu to set list's `wrapFocus` property. Enhanced select uses this new API to set it to `false` since select component doesn't wrap focus.
Fixes #3733

fix(select): Enhanced select doesn't wrap focus

---

packages/mdc-textfield/foundation.js
test/unit/mdc-textfield/foundation.test.js

fix(text-field): Send client position to line ripple for touch events

---

packages/mdc-snackbar/adapter.js
packages/mdc-snackbar/constants.js
packages/mdc-snackbar/foundation.js
packages/mdc-snackbar/index.js
packages/mdc-snackbar/util.js
test/screenshot/spec/mdc-snackbar/classes/baseline-with-action.html
test/screenshot/spec/mdc-snackbar/classes/baseline-without-action.html
test/screenshot/spec/mdc-snackbar/classes/leading.html
test/screenshot/spec/mdc-snackbar/classes/stacked.html
test/screenshot/spec/mdc-snackbar/classes/wide.html
test/screenshot/spec/mdc-snackbar/mixins/elevation.html
test/screenshot/spec/mdc-snackbar/mixins/fill-color.html
test/screenshot/spec/mdc-snackbar/mixins/label-ink-color.html
test/screenshot/spec/mdc-snackbar/mixins/max-width.html
test/screenshot/spec/mdc-snackbar/mixins/min-width.html
test/screenshot/spec/mdc-snackbar/mixins/shape-radius.html
test/screenshot/spec/mdc-snackbar/mixins/viewport-margin.html
test/unit/mdc-snackbar/foundation.test.js
test/unit/mdc-snackbar/mdc-snackbar.test.js
test/unit/mdc-snackbar/util.test.js

feat(snackbar): Accessibility: Announce label text to screen readers

---

packages/mdc-top-app-bar/index.js
test/unit/mdc-top-app-bar/mdc-top-app-bar.test.js

This resolves the test failure discovered in #4046.
The `getViewportScrollY` adapter unit test was coincidentally passing because the page's scroll offset and the scroll offset of the content element were typically both 0. This only ended up not being the case when I tried running our unit tests via headless Firefox on Travis.
The test as written actually should never have passed, because `getDefaultFoundation` in the Top App Bar component had the side effect of resetting the scroll target, effectively undoing the test's setup.
This fixes the component to initialize the scroll target in `initialize` rather than `getDefaultFoundation`, and fixes the test to use a mock object to guarantee a distinguishable expected value.

fix(top-app-bar): Move scroll target initialization; improve test

---

karma.conf.js

Fixes #4041.
Sending out initially to see what happens on Travis. Tested locally on OS X forcing the travis flag to true.

chore: Update karma to run Chrome+FF headless and only IE on SL

---

packages/mdc-ripple/_mixins.scss
test/screenshot/golden.json

Fixes #4057.
Also removes a stale comment which presumably became obsolete partway through ripple style refactoring.
There are a few ways to verify, but this is probably the quickest:
1. Run `npm start`
2. Navigate to http://localhost:8080/spec/mdc-textfield/classes/baseline.html
3. Inspect one of the outlined text fields
4. Confirm there are no before/after pseudo-elements visible under the root element (in contrast to the filled text fields, where they are visible)
Alternatively, this can also be verified using the catalog's text field page and [this script](https://gist.github.com/kfranqueiro/d06c7073c5012de3edb6c5875d6a4a50) to copy this branch's dist CSS into the catalog's `node_modules` folder. Without this fix, if you resize the text field catalog page just wide enough to fit all …

fix(ripple): Suppress before/after when color is transparent

---

packages/mdc-shape/_mixins.scss

This has 3 changes/fixes:
* Don't bother emitting separate RTL styles when we can easily tell it's identical to LTR
* Add `@noflip` annotations to both the LTR and RTL emitted styles when both are emitted
* Fix RTL emitted styles to resolve shape category names (this caused a bug in drawer's RTL styles previously)

fix(shape): Add noflip comments, fix RTL for categories

---

.stylelintrc.yaml
packages/mdc-button/_mixins.scss
packages/mdc-card/mdc-card.scss
packages/mdc-drawer/common.scss
packages/mdc-floating-label/mdc-floating-label.scss
packages/mdc-form-field/mdc-form-field.scss
packages/mdc-grid-list/mdc-grid-list.scss
packages/mdc-icon-toggle/mdc-icon-toggle.scss
packages/mdc-list/mdc-list.scss
packages/mdc-notched-outline/mdc-notched-outline.scss
packages/mdc-radio/mdc-radio.scss
packages/mdc-ripple/_mixins.scss
packages/mdc-rtl/_mixins.scss
packages/mdc-top-app-bar/mdc-top-app-bar.scss
packages/mdc-typography/_mixins.scss

This piggybacks on #4117 to override the `stylelint-config-standard` rule that was requiring us to add empty lines before our CSS annotation comments, and remove those newlines. The newlines are kind of confusing since really the annotations simply indicate something about the next line, and there's not actually any logical division from the previous line.
CSS output is identical before/after this change.

style: Remove newlines before CSS annotations

---

packages/mdc-list/README.md

Fixes #4031.
Also updates all JS examples to use ES2015+ syntax consistent with other readmes, and links to the importing JS docs.

docs(list): Document how to instantiate ripples

---

packages/mdc-list/README.md
packages/mdc-menu/README.md

Fixes #3679.
Adds mention of `--disabled` modifier class to List docs for CSS classes and a11y, and also mentions the modifier class in the Menu docs.
Also improves wording around selected and activated states in MDC List docs.

docs(list): Document disabled modifier class

---

docs/code/architecture.md

Fixes #4119.
The vanilla component section pretty much already covered the "foundation has-a adapter" bit anyway, so I just tried to clarify things.

docs: Improve architecture wording

---

test/screenshot/golden.json

I cherry-picked this from Andy's `feat/snackbar--readme` branch (PR #4091) so it won't conflict when syncing with master.

chore(linear-progress): Update goldens for Chrome update (69 to 71)

---

docs/code/architecture.md
packages/mdc-tab-bar/README.md
packages/mdc-tab-bar/adapter.js
packages/mdc-tab-bar/foundation.js
packages/mdc-tab-bar/index.js
packages/mdc-tab/README.md
packages/mdc-tab/adapter.js
packages/mdc-tab/index.js
test/unit/mdc-tab-bar/foundation.test.js
test/unit/mdc-tab-bar/mdc-tab-bar.test.js

Use unique identifiers to reference tabs instead of the object equality comparison. Change the `getIndexOfTab` method to `getIndexOfTabByID`. Update tests.
This makes it more feasible to wrap MDC Tab Bar for frameworks, which shouldn't need to reference the vanilla component.
BREAKING CHANGE: `MDCTabBar#getIndexOfTab(tab: MDCTab): boolean` is now `MDCTabBar#getIndexOfTabByID(id: string): boolean`

feat(tab): Get tabs by their ID

---

packages/mdc-menu/README.md

We had a cross-link in the JS section, but not under sass mixins, so it was easy to miss the correlation between menu and menu-surface and list.

docs(menu): Cross-link to menu-surface and list Sass mixins

---

package-lock.json

Although greenkeeper tries to update package-lock itself, its updates always seem to cause noise against what an actual local `npm i` does.

chore: Sync package lock w/ npm install

---

test/screenshot/infra/lib/diff-base-parser.js

This avoids needlessly querying GitHub APIs for local screenshot test runs, which is very likely to hit rate limits for anonymous requests. Getting the associated PR ID is typically not useful (or not even applicable) when running screenshot tests locally, so we certainly don't want to fail on it.

chore(infrastructure): Only try resolving PR ID on Travis CBT runs

---

packages/mdc-dialog/README.md

Looks like handleClick was renamed to handleInteraction, but it is not displayed in documentation

docs(dialog): rename handleClick for mdc-dialog to handleInteraction

---

packages/mdc-snackbar/README.md
packages/mdc-snackbar/_variables.scss
packages/mdc-snackbar/constants.js
packages/mdc-snackbar/index.js
packages/mdc-snackbar/mdc-snackbar.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-snackbar/classes/baseline-with-action.html
test/screenshot/spec/mdc-snackbar/classes/baseline-without-action.html
test/screenshot/spec/mdc-snackbar/classes/leading.html
test/screenshot/spec/mdc-snackbar/classes/stacked.html
test/screenshot/spec/mdc-snackbar/mixins/elevation.html
test/screenshot/spec/mdc-snackbar/mixins/fill-color.html
test/screenshot/spec/mdc-snackbar/mixins/label-ink-color.html
test/screenshot/spec/mdc-snackbar/mixins/max-width.html
test/screenshot/spec/mdc-snackbar/mixins/min-width.html
test/screenshot/spec/mdc-snackbar/mixins/shape-radius.html
test/screenshot/spec/mdc-snackbar/mixins/viewport-margin.html
test/unit/mdc-snackbar/mdc-snackbar.test.js

This revises the names of the action and dismiss elements to make them potentially more indicative and less bound to specifically being a button or icon, for potential future-proofing.
I've also revised our docs' wording a bit after talking to our designer again, who expressed serious reservations about featuring the dismiss icon as prominently as we were, at least until further discussion RE IxD and accessibility on his end.
(I'm not including a breaking change note, because this hasn't been released yet. All the better to revise classnames now.)

fix(snackbar): Rename action/dismiss classes and revise docs/tests

---

packages/mdc-base/README.md
packages/mdc-dialog/foundation.js
packages/mdc-dialog/index.js
packages/mdc-drawer/index.js
packages/mdc-grid-list/foundation.js
packages/mdc-grid-list/index.js
packages/mdc-linear-progress/foundation.js
packages/mdc-linear-progress/index.js
packages/mdc-select/foundation.js
packages/mdc-select/index.js
packages/mdc-snackbar/foundation.js
packages/mdc-snackbar/index.js
packages/mdc-toolbar/index.js
test/unit/mdc-base/component.test.js
test/unit/mdc-base/foundation.test.js

As per [closure-compiler](https://github.com/material-components/material-components-web/blob/master/docs/closure-compiler.md#all-import-statements-must-not-use-re-exported-modules) doc, all import statements must not use re-exported modules.
Fixes #4211

chore: Fix base component re-import statements.

---

docs/theming.md
packages/mdc-button/_variables.scss
packages/mdc-card/_variables.scss
packages/mdc-chips/_variables.scss
packages/mdc-dialog/_variables.scss
packages/mdc-drawer/_variables.scss
packages/mdc-elevation/_variables.scss
packages/mdc-fab/_variables.scss
packages/mdc-floating-label/_variables.scss
packages/mdc-icon-button/_variables.scss
packages/mdc-image-list/_variables.scss
packages/mdc-linear-progress/_variables.scss
packages/mdc-list/_variables.scss
packages/mdc-menu-surface/_variables.scss
packages/mdc-menu/_variables.scss
packages/mdc-notched-outline/_variables.scss
packages/mdc-radio/_variables.scss
packages/mdc-ripple/_variables.scss
packages/mdc-select/_variables.scss
packages/mdc-shape/_variables.scss
packages/mdc-slider/_variables.scss
packages/mdc-switch/_variables.scss
packages/mdc-tab/_variables.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/icon/_variables.scss
packages/mdc-theme/_variables.scss
packages/mdc-toolbar/_variables.scss
packages/mdc-top-app-bar/_variables.scss
packages/mdc-typography/_variables.scss

Continuing what was done to checkbox in #3635 and fulfilling #3708, I've added `!default` to all variables such that they can be overridden in client applications.
Fixes #3708

chore: Declare all sass variables as !default (#3708)

---

packages/mdc-layout-grid/README.md

It looks like someone forgot to change param name in README.md.

doc(layout-grid): Renamed 'type-of-device' param to 'size' in sass mixin docs

---

package-lock.json
packages/mdc-chips/README.md
packages/mdc-chips/chip/adapter.js
packages/mdc-chips/chip/foundation.js
packages/mdc-chips/chip/index.js
test/unit/mdc-chips/mdc-chip.foundation.test.js
test/unit/mdc-chips/mdc-chip.test.js

This change makes adding ripple easier for clients wrapping chips.
BREAKING CHANGE: Adds 3 new chips adapter methods: hasLeadingIcon, getRootBoundingClientRect, and getCheckmarkBoundingClientRect. Also adds a new foundation method: getDimensions.

feat(chips): Move logic for calculating chip bounding rect into a foundation method

---

packages/mdc-tab-scroller/util.js

getMatchesProperty returns Array.pop() from an Array of strings, so the return value should be string.

refactor(tab-scroller): Fix a Closure type declaration in the Tab Scroller util.

---

packages/mdc-feature-targeting/_mixins.scss

Nesting this mixin could lead to unexpected results. (e.g. the following property would not get emitted if the color styles were requested)
```scss
@include mdc-feature-targets($feat-structure) {
@include mdc-feature-targets($feat-color) {
color: red;
}
}
```
This PR makes the above pattern an error by using a global variable to track when we're inside the mixin and raise an error if the mixin is included again in that context.

fix(feature-targeting): prevent accidental nesting of mdc-feature-targets mixin

---

packages/mdc-checkbox/_mixins.scss
packages/mdc-ripple/_mixins.scss

Fixes: https://github.com/material-components/material-components-web/issues/4283
Supersedes: https://github.com/material-components/material-components-web/pull/4291
Re-orders animation mixins to put the animation name at the beginning.

chore: Fixed the order of css animation shorthand values

---

packages/mdc-textfield/README.md

This came up in a user study, where it was discovered that placing the deprecation notice for a single variant at the top of the readme was overly alarming and could be mistaken for the entire component being deprecated.

docs(text-field): Move dense deprecation notice to reduce confusion

---

packages/mdc-textfield/index.js

The function takes 2 parameters but the jsdoc only documented one.

fix(text-field): Update closure type for rippleFactory

---

package.json

Our lint task has not been failing on CI for stylelint failures under `packages` for a few months because of a `;` added to its invocation, because that completely discards the exit code from the first command.

chore: Fix stylelint error code reporting for packages

---

packages/mdc-ripple/_variables.scss

This change is being made after review by designers based on user feedback indicating that 16% press opacity in on-surface situations seems too pronounced. Designers also tested baseline on-primary for the reduction from 32% to 24% in that case.

feat(ripple): Reduce press opacity by 25%

---

packages/mdc-base/component.ts
packages/mdc-base/index.ts
packages/mdc-base/types.ts
packages/mdc-checkbox/adapter.ts
packages/mdc-checkbox/index.ts
packages/mdc-checkbox/package.json
packages/mdc-dom/index.ts
packages/mdc-form-field/adapter.ts
packages/mdc-icon-button/adapter.js
packages/mdc-linear-progress/adapter.ts
packages/mdc-menu-surface/adapter.ts
packages/mdc-menu-surface/index.ts
packages/mdc-menu-surface/package.json
packages/mdc-radio/adapter.ts
packages/mdc-radio/index.ts
packages/mdc-radio/package.json
packages/mdc-ripple/adapter.ts
packages/mdc-ripple/foundation.ts
packages/mdc-ripple/package.json
packages/mdc-ripple/types.ts
packages/mdc-ripple/util.ts

Also moves `mdc-dom/events.ts` to `mdc-base/types.ts`
and adds `CustomEventListener<E extends Event>` type.

feat(base): Add generic type signatures to listen/unlisten/emit

---

packages/mdc-chips/_mixins.scss

`border-width` requires a unit and has a weird default value: https://jsfiddle.net/04j5sqzw/1/. This change fixes that behavior.

fix(chips): Use required pixel value

---

CHANGELOG.md

#4244 didn't include a BREAKING CHANGE note when it was merged. This is super important because all existing helper-text usages are broken by its changes.
Thanks @jamesmfriedman for pointing this out.

docs(text-field): Add breaking change to changelog for helper-line

---

packages/mdc-menu/index.js
test/unit/mdc-menu/mdc-menu.test.js

This fixes a regression caused by PR #4356, and adds a unit test to catch future integration failures between list and menu events.

fix(menu): Read index property from list item event detail

---

packages/mdc-chips/_mixins.scss

This fixes the margin of leading icons inside Chips from being applied to the incorrect side of the icon when the Chip appears in a page with RTL writing mode.
Fixes #4379.

fix(chips): Flip leading icon margin when used in RTL contexts (#4379)

---

test/screenshot/golden.json

Firefox updated from version 63 to 65, which slightly changed antialiasing behavior of text
and `border-radius`.
Unfortunately, Chrome 72 broke `padding-right` on `mdc-dialog__actions` for `mdc-dialog--stacked`:
https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2019/02/11/22_13_08_557/report/report.html
This may be related to https://crbug.com/927066. It still renders correctly in Firefox 65, IE 11,
and Edge 18.
I wasn't able to find a workaround, so I'm approving the broken "stacked dialog" screenshots in Chrome for now. If/when Chromium fixes this regression, the dialog screenshot tests will start failing, which will remind us to update the screenshots again.

chore(infrastructure): Update screenshots after browser upgrades

---

package-lock.json
packages/mdc-elevation/_mixins.scss
packages/mdc-elevation/mdc-elevation.scss
packages/mdc-ripple/_mixins.scss
packages/mdc-ripple/mdc-ripple.scss
packages/mdc-theme/_mixins.scss
packages/mdc-theme/mdc-theme.scss
packages/mdc-theme/package.json
packages/mdc-typography/_mixins.scss
packages/mdc-typography/mdc-typography.scss
test/scss/feature-targeting.scss

theme, and typography (part of #4227)

feat(feature-targeting): target top-level styles for elevation, ripple,

---

packages/mdc-checkbox/index.js
packages/mdc-checkbox/package.json
packages/mdc-ripple/README.md
packages/mdc-ripple/index.js
packages/mdc-ripple/package.json
packages/mdc-ripple/util.js
packages/mdc-switch/index.js
packages/mdc-switch/package.json
packages/mdc-tab-scroller/README.md
packages/mdc-tab-scroller/index.js
packages/mdc-tab-scroller/package.json
packages/mdc-tab-scroller/util.js
packages/mdc-textfield/index.js
packages/mdc-textfield/package.json
test/unit/mdc-checkbox/mdc-checkbox.test.js
test/unit/mdc-ripple/mdc-ripple.test.js
test/unit/mdc-ripple/util.test.js
test/unit/mdc-tab-scroller/util.test.js

Fixes #4340
`mdc-dom` implements a `matches()` method that wasn't used everywhere. These custom implementations prevented some SSR usage of the material-components library. This commit removes all the custom implementations.
I removed some tests that were testing a now removed method, and I handled to make the other pass.
PS: This is my first contribution here, I hope I did everything right!
BREAKING CHANGE: `getMatchesProperty()` has been removed from `@material/ripple/util`. Use `matches()` from `@material/dom/ponyfill` instead.

fix(ripple): Use mdc-dom.matches everywhere instead of a custom one (#4340)

---

packages/mdc-chips/chip/types.ts

This fixes the build, which previously was complaining about two references to MDCRipple not matching due to inconsistent imports.

fix(chips): Reference ripple/index in types for consistency

---

packages/mdc-dialog/README.md

docs(dialog): Expand wording RE layout-sensitive children

---

packages/mdc-floating-label/_mixins.scss

add missing @material/theme/mixins.scss `@import` to @material/floating-label/mixins.scss

fix: add missing import to mdc-floating-label/mixins

---

packages/mdc-checkbox/component.ts
packages/mdc-chips/chip/foundation.ts

PR #4332 inadvertently broke short-circuit logic and evaluation order.
The change caused incorrect ripple size calculations on filter chips without leading icons, which was caught by internal screenshot tests.

chore: Fix regression in `MDCChipFoundation.getDimensions()`

---

packages/mdc-animation/index.js
packages/mdc-linear-progress/foundation.js

Mirrors https://github.com/material-components/material-components-web/pull/4407#discussion_r258668567 from the `feat/typescript` branch.
BREAKING CHANGE: The `transformStyleProperties` array export has been removed from `mdc-animation`. Please use `getCorrectPropertyName(window, 'transform')` instead.

refactor(animation): Remove `transformStyleProperties` export

---

scripts/cp-pkgs.js
scripts/verify-pkg-main.js

chore: grammar mistakes on script comments

---

packages/mdc-menu-surface/component.ts
test/screenshot/spec/mdc-menu/classes/baseline.html
test/screenshot/spec/mdc-menu/classes/bottom-anchored.html
test/screenshot/spec/mdc-menu/classes/menu-selection-group.html
test/screenshot/spec/mdc-menu/fixture.js
test/unit/mdc-menu-surface/mdc-menu-surface.test.js

When Menu Surface was converted to TypeScript, its `anchorElement` field was initialized to `null`. This caused a regression, because any proper setup that occurred in `initialSyncWithDOM` was being steamrolled by this `null` initialization, because that occurs in `constructor` _after_ `super` is called.

fix(menu-surface): Fix anchorElement initialization

---

scripts/cp-pkgs.js

Refs https://github.com/material-components/material-components-web/issues/4463#issuecomment-469306836
Example of module declarations before:
```
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog' {
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog/util' {
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog/adapter' {
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog/component' {
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog/foundation' {
./dialog/dist/mdc.dialog.d.ts:declare module 'mdc-dialog/types' {
```
Example of module declarations after:
```
packages/mdc-dialog/dist/mdc.dialog.d.ts:declare module '@material/dialog' {
packages/mdc-dialog/dist/mdc.dialog.d.ts:declare module '@material/dialog/util' {
packages/mdc-dialog/dist/mdc.dialog.d.ts:declare …
```

fix(package): Fix module declaration names in dist d.ts files

---

packages/mdc-top-app-bar/README.md
packages/mdc-top-app-bar/_variables.scss
packages/mdc-top-app-bar/mdc-top-app-bar.scss

Swap the order of prominent and dense within the variables file to match other sections of the package.
Issue: #4497

refactor: Swap MDCTopAppBar Sass Variable Word Order

---

packages/mdc-form-field/_mixins.scss
packages/mdc-form-field/_variables.scss
test/scss/feature-targeting.scss

feat(form-field): add feature targeting for styles

---

docs/open_source/release-process.md
scripts/cherry-pick-commits.js

This renames `cherry-pick-patch-commits.js` to just `cherry-pick-commits.js`, and it now expects to see either a `--patch` or `--minor` argument.
`--patch` continues to behave as this script behaved before.
`--minor` seeks to the latest major/minor (not patch) tag, then cherry-picks all non-breaking-change commits.
The end result is similar in both cases - you end up detached from any branch in your local clone and can follow the rest of the release process from there.
(I'll send a separate PR to update the rest of our release process doc.)
This also adds a `--skip-tests` flag to the script, which really shouldn't be used for actual releases, but can be useful when testing updates to this script since it takes a while to build our assets and run our tests, and the final results don't get …

chore: Add ability to cherry-pick commits for minor releases

---

packages/mdc-shape/_functions.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-shape/fixture.js
test/screenshot/spec/mdc-shape/fixture.scss
test/screenshot/spec/mdc-shape/variables/override.html

This PR fixes issue with overriding global shape variables with percentage values.
For example, overriding small component shape global variable would apply given radius (i.e., `50%`) to all small components (button, textfield, etc.).
```
$mdc-shape-small-component-radius: 50%;
```
Whereas, default shape radius value of small component is `4px`. Before this change, overriding shape global variables with percentages resulted in compilation error or wouldn't resolve the percentage value from shape literals.
This change fixes it by resolving shape literals (e.g., `small`) before resolving percentage values.
Refs #4140

fix(shape): Allow percentage based global overrides

---

packages/mdc-select/_mixins.scss
packages/mdc-select/mdc-select.scss

I realized while digging into #4547 that our select and text field were using inconsistent shape categories. I checked with design and our text field is correctly using `small`, so select needs to be updated.
This causes no diffs in CSS because small and medium both default to `4px` (which is also how this went unnoticed for so long).

fix(select): Use correct shape category consistently with text-field

---

packages/mdc-tab/mdc-tab.scss

Disables the dotted line focus ring, added on firefox, from the button used by `mdc-tab`.

fix(tab): Disable firefox focus ring

---

packages/mdc-notched-outline/_mixins.scss
packages/mdc-select/_mixins.scss
packages/mdc-shape/_functions.scss
packages/mdc-textfield/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-shape/fixture.js
test/screenshot/spec/mdc-shape/fixture.scss

Refs #4140.
This PR changes the behavior from throwing an error and failing compilation, to warning about each encountered case and automatically falling back to using the first radius value. This is done in such a way as to avoid this problem even when multiple values are assigned at the shape variable level (i.e. centrally for small/medium/large).
I have a separate WIP branch to actually support multiple corner radii for notched-outline-related components (see the bug).
To test, assign multiple radii to the small/medium `$mdc-shape-...-component-radius` variable(s) in `mdc-shape/_variables.scss`.

fix(shape): Fix errors related to multi-value shape categories

---

docs/framework-wrappers.md

Adds front-matter to the framework-wrappers.md page, because one of our designers on the site team pointed out it would be a really helpful page to have showing up on material.io.

docs: Make framework wrappers page discoverable to site generator

---

packages/mdc-list/_mixins.scss
packages/mdc-menu/_mixins.scss

fix(list): Add cursor: pointer for interactive list items

---

packages/mdc-tab/mdc-tab.scss

The previous style does not work as expected on all versions of firefox, so this change copies the selector used by the button element to disable the dotted line outline.

fix(tab): Update moz-focusring to moz-focus-inner to match button

---

packages/mdc-chips/chip/foundation.ts

fix(chips): Fix incorrect ripple effect on filter chip

---

packages/mdc-select/component.ts
packages/mdc-top-app-bar/README.md
test/unit/mdc-select/mdc-select-enhanced.test.js
test/unit/mdc-select/mdc-select.test.js

continuation of https://github.com/material-components/material-components-web/pull/4413
fixes #4173

fix(select): Fix enhanced select issue where it does not stay open on long press #4173

---

packages/mdc-checkbox/constants.ts
packages/mdc-checkbox/foundation.ts
test/unit/mdc-checkbox/foundation.test.js

Add the `mdc-checkbox--selected` class when the checkbox goes from unchecked to checked or unchecked to indeterminate. Remove `mdc-checkbox--selected` when the checkbox goes from checked to unchecked or indeterminate to unchecked.

feat(checkbox): Toggle selected class with state

---

packages/mdc-textfield/icon/constants.ts
packages/mdc-textfield/icon/foundation.ts

There is one question!
"mdc-text-field__icon" or "mdc-text-field-icon", which one is correct?
Almost code is written "mdc-text-field__icon".
But definition of cssClasses is written "mdc-text-field-icon" in README.
And other module(helper-text/counter) follows this convention.

feat(text-field): define icon's cssClasses

---

packages/mdc-list/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-list/classes/meta-text.html

Updates the `__meta` class to use the caption typography style. 
fixes: #4622

fix(list): Update meta class to use caption typogrpahy style

---

packages/mdc-tab-bar/adapter.ts
packages/mdc-tab-bar/foundation.ts
test/unit/mdc-tab-bar/foundation.test.js

If there is no previous active tab, the index will be `-1`, which will be trigger errors in the adapter of the component when trying to call methods on `this.tabList_[index]`. This is now handled gracefully for the case when there is no previously active tab.
Fixes #4226

fix(tab-bar): fix the activation of tab without previous active tab

---

packages/mdc-ripple/util.ts
test/unit/mdc-ripple/helpers.js

No functional change but helps with linters.

fix(ripple): Use standard element removal method

---

packages/mdc-tab/mdc-tab.scss

fix(tab): Explicitly set margin to 0 on tabs for Safari

---

CHANGELOG.md

Replaced breaking change note that is superseded by latest breaking change of MDC Menu.

docs: Updated Changelog with latest menu breaking changes

---

packages/mdc-typography/README.md

Updates the example of setting the global font-family to use unquote.

docs(typography): Update setting font-family to use unquote

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/icon/_variables.scss

Refs #4294 
Padding is now constant across text field variants and icon position at 12px.
I have a question about a variable initialized 2 times with different values, please see comment.

fix(text-field): Fix TextField padding with leading icon

---

packages/mdc-tab/_variables.scss

This should fix #4686 to some extent.
- Used theme literal (`primary`) when defining override variables, where as, `mdc-theme-prop-value` is a function that returns a color value of `primary`.
- Set `!default` to all sass variables defined in `_variable.scss` for full customization.

fix(tab): Fix tab color variables to use color literals

---

CHANGELOG.md
packages/mdc-ripple/_mixins.scss
test/screenshot/golden.json

Removed will-change CSS property from Ripple.
Didn't notice any drastic performance changes with & without will-change CSS property.
* [Prototype: with will-change](https://mdc-list-will-change-test-qf5w6fen7.now.sh/checkbox.html) - _Current Behaviour_  
* [Prototype: without will-change](https://mdc-list-will-change-test-jcjev60xb.now.sh/checkbox.html)
As per documentation from MDN & other resources:
> Don't apply will-change to too many elements. The browser already tries as hard as it can to optimize everything. Some of the stronger optimizations that are likely to be tied to will-change end up using a lot of a machine’s resources, and when overused like this can cause the page to slow down or consume a lot of resources. ([MDN …

fix(ripple): Fixes issue where Chrome v74 shows black artifact on ripple surface on hover

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/icon/_variables.scss

Together with my PR #4595, this should fix #4296 
`$mdc-text-field-icon-padding` was set to `48px`.
But when an icon is present, the input padding should be the sum of:
- the icon padding: `12px`,
- the icon width: `24px`,
- the input padding: `16px`
Therefore `52px`.

fix(text-field): Padding between Textfield and Icon

---

packages/mdc-chips/README.md
packages/mdc-chips/chip/adapter.ts
packages/mdc-chips/chip/component.ts
packages/mdc-chips/chip/constants.ts
packages/mdc-chips/chip/foundation.ts
test/screenshot/golden.json
test/screenshot/spec/mdc-chips/classes/choice.html
test/screenshot/spec/mdc-chips/classes/filter.html
test/unit/mdc-chips/mdc-chip.foundation.test.js

Add `MDCChipAdapter#setAttr` method. Update screenshot tests with appropriate roles.
BREAKING CHANGE: Add the `setAttr` method to the chip adapter.

feat(chips): Add setAttr adapter method

---

test/screenshot/golden.json
test/screenshot/spec/mdc-checkbox/classes/baseline.html

Fixing checkbox screenshot test. SVG has changed on Firefox.

fix(checkbox): screenshot test golden update

---

packages/mdc-dialog/_mixins.scss
test/screenshot/golden.json

`vh` includes the browser top/bottom bars on Chrome/Android and is inconsistent in Safari, causing scrolling content to overflow.

fix(dialog): Fix scrolling content overflowing on Chrome/Android.

---

packages/mdc-dialog/_mixins.scss

Use 100vw as it doesn't have the same browser incompatibilities that 100vh does (see PR #4746 for context). 100% width on the other hand breaks on mobile/Safari.

fix(dialog): Use 100vw for dialog max-width calculation.

---

packages/mdc-menu-surface/README.md
packages/mdc-menu-surface/adapter.ts
packages/mdc-menu-surface/component.ts
packages/mdc-menu-surface/foundation.ts
test/unit/mdc-menu-surface/mdc-menu-surface.test.js
test/unit/mdc-menu-surface/menu-surface.foundation.test.js

Instead, TAB should close the menu and respect default browser tab order.
BREAKING CHANGE: The following adapter methods were removed: `isFirstElementFocused`, `isLastElementFocused`, `focusFirstElement`, `focusLastElement`. The following functionality to handle TAB on menusurface has been removed: "If TAB and last element is focused => Focus on first element", "If SHIFT + TAB and first element is focused => Focus on last element"

fix(menu): Remove code to focus on first/last element on TAB/SHIFT+TAB.

---

packages/mdc-list/README.md
packages/mdc-list/_mixins.scss
packages/mdc-list/_variables.scss
packages/mdc-menu/_mixins.scss

Set opacity for all items instead of color. This solves problems where high-contrast mode on Windows 7 causes disabled and enabled list items to be indistinguishable.

feat(list): Add mixin for disabled text opacity

---

packages/mdc-menu/_mixins.scss
test/screenshot/golden.json

IE11 does not vertically position the group icon when it is followed by a text item. This fixes that behavior.

fix(menu): Vertically center the group icon

---

scripts/webpack/js-bundle-factory.js

related https://github.com/material-components/material-components-web-react/issues/954
Confirmed that in [v2.3.0 of drawer](https://unpkg.com/@material/drawer@2.3.0/dist/mdc.drawer.js), the output.globalObject referenced `this`. In the [webpack 4 update](https://github.com/material-components/material-components-web/pull/4847), this was changed to `window`. To support SSR and ensure that no breaking changes occur during the webpack 4 upgrade, I suggest this change.

fix(infrastructure): support ssr by removing the reference from window

---

packages/mdc-fab/_mixins.scss

Clears the `text-decoration` from the FAB, otherwise text-based icons might become underlined in some browsers.
Here's an example of Angular Material on Edge:

fix(fab): clear text decoration

---

packages/mdc-chips/README.md
packages/mdc-chips/chip-set/adapter.ts
packages/mdc-chips/chip-set/component.ts
packages/mdc-chips/chip-set/foundation.ts
test/unit/mdc-chips/mdc-chip-set.foundation.test.js
test/unit/mdc-chips/mdc-chip-set.test.js

Change interface for `MDCChipSetAdapter#removeChip` to `MDCChipSetAdapter#removeChipAtIndex`. Update comments for `MDCChipSetAdapter`.
BREAKING CHANGE: `MDCChipSetAdapter#removeChip` has been replaced with `MDCChipSetAdapter#removeChipAtIndex`. `MDCChipSetAdapter#setSelected` has been replaced with `MDCChipSetAdapter#selectChipAtIndex`

feat(chips): Use index for all chip operations

---

packages/mdc-checkbox/_functions.scss
packages/mdc-checkbox/_mixins.scss

Used Sass's `unique-id()` unique id generator function instead of using number incriminator which might not work if override Sass mixin is compiled in another session.
Fixes #4710

fix(checkbox): Fixed checkbox container fill color when animating

---

packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-checkbox/classes/baseline.html
test/screenshot/spec/mdc-checkbox/fixture.js
test/screenshot/spec/mdc-checkbox/fixture.scss
test/screenshot/spec/mdc-checkbox/mixins/container-colors.html
test/screenshot/spec/mdc-checkbox/mixins/touch-dimension.html

* Updated `mdc-checkbox-focus-indicator` mixin to allow customizing ripple color for checked checkboxes. Previously `mdc-checkbox-focus-indicator` use to only set color for JS disabled checkboxes.
* Included `mdc-checkbox-focus-indicator` mixin to `.mdc-checkbox` class name since this mixin uses state selectors such as `--selected` with root class.
* Updated screenshot files to include `--selected` class name for checked checkboxes.
Refs #2949

fix(checkbox): Fixed hover focus colors for unchecked checkbox

---

packages/mdc-data-table/README.md
packages/mdc-data-table/_mixins.scss
packages/mdc-data-table/mdc-data-table.scss
test/scss/_feature-targeting-test.scss
test/unit/mdc-dialog/foundation.test.js

* Moved `mdc-data-table-checked-icon-color` mixin to separate baseline theme mixin that prevents duplicating checkbox styles when theming.
* Minor updates to README.
* Reverted dialog test changes.
Refs #4591

feat(data-table): Separated baseline theming from core styles

---

packages/mdc-select/README.md
packages/mdc-select/adapter.ts
packages/mdc-select/component.ts
packages/mdc-select/foundation.ts
test/unit/mdc-select/foundation.test.js
test/unit/mdc-select/mdc-select.test.js

Simplify adapter and component by moving `setDisabled` logic into foundation.
BREAKING CHANGE: `MDCSelectAdapter#setDisabled` is removed, and `MDCSelectAdapter#setSelectedTextAttr` is added.

refactor(select): Move disabled logic into foundation

---

packages/material-components-web/package.json
packages/mdc-density/README.md
packages/mdc-density/_functions.scss
packages/mdc-density/_variables.scss
packages/mdc-density/package.json

* Added `mdc-density-prop-value` function to return appropriate component height / size based on given density scale and component's density scale map. The `*-prop-value` name is given to be consistent with other utility functions used within MDC. For example, `mdc-theme-prop-value`.
* Component scale maps (e.g., `$mdc-button-density-scale-map`) use literals (e.g., `compact`) as keys to easily refer baseline / default component (max) height and compact (min) height to easily validate and throw error for unsupported component height. Scale map variable can be overridden by developers.
@jelbourn For review.

feat(density): Added density utility component.

---

packages/mdc-button/_mixins.scss
test/screenshot/golden.json

This fixes touch target elements inside buttons getting clipped in iE11.

fix(button): Add `overflow: visible` to button.

---

packages/mdc-chips/_mixins.scss

Ripple element is stacked below other chip inner elements that are not positioned, thereby blocking clicks on chip close icon.

fix(chips): Add `pointer-events: none` to chip ripple element.

---

test/screenshot/infra/lib/cbt-api.js

Possible fix for WebDriver timeout issue:
```
ERROR: WebDriverError: FORWARDING_ERROR: timeout from remote selenium
```

chore: Bump up idle_timeout to fix webdriver timeout issues

---

packages/mdc-ripple/util.ts
test/unit/mdc-ripple/helpers.js

If this script is invoked in the head, then the body won't exist yet, which causes the appendChild line to throw.
I confirmed that the bug is still detected in Edge 15.15063.

fix: Use head instead of body to detect edge pseudo var bug

---

packages/mdc-select/README.md
packages/mdc-select/adapter.ts
packages/mdc-select/component.ts
packages/mdc-select/foundation.ts
test/screenshot/golden.json
test/unit/mdc-select/foundation.test.js
test/unit/mdc-select/mdc-select.test.js

- Proxy to foundation for `get/set required`
- Move `checkValidity` and `setValid` adapter logic to foundation
- Simplify `openMenu` in adapter
- Remove unused adapter method `getSelectedMenuItem`
- Simplify `toggleClassAtIndex` adapter method into `addClassAtIndex` and `removeClassAtIndex`

refactor(select): Move adapter logic into foundation

---

packages/mdc-select/README.md
packages/mdc-select/adapter.ts
packages/mdc-select/component.ts
packages/mdc-select/foundation.ts
packages/mdc-select/icon/README.md
test/screenshot/golden.json
test/screenshot/spec/mdc-select/classes/invalid-helper-text-persistent-validation-msg.html
test/screenshot/spec/mdc-select/classes/invalid-helper-text-persistent.html
test/screenshot/spec/mdc-select/classes/invalid-helper-text.html
test/screenshot/spec/mdc-select/classes/invalid.html
test/unit/mdc-select/foundation.test.js
test/unit/mdc-select/mdc-select.test.js

Fixes as part of #4993
- Remove programmatically adding `WITH_LEADING_ICON` classes, update docs to recommend adding these classes in HTML instead.
- Remove programmatically setting the selected value (i.e., `this.foundation_.setValue` in `initialSyncWithDOM`), update docs to recommend having selected item inside selected text element.
- Remove programmatically adding `aria-required` attr and `REQUIRED` class, update docs to recommend adding these in HTML instead.
- Remove mutation observers from component and replace it with `setRequired` API that consumer can use to set required field which delegates to foundation.
- Split and delegate `getValue` adapter logic to foundation.

refactor(select): Remove programmatically adding classes/attributes and update getValue

---

packages/mdc-top-app-bar/README.md
packages/mdc-top-app-bar/short/foundation.ts
test/unit/mdc-top-app-bar/short.foundation.test.js

- Add `setAlwaysCollapsed(value: boolean)` and `getAlwaysCollapsed()`
methods
- Keep behavior of initializing with `SHORT_COLLAPSED_CLASS` to mean
that the component should always be collapsed.
Fixes #4928

fix(top-app-bar): "always collapsed" variant semantics in Short TopAppBar Foundation

---

packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
packages/mdc-checkbox/_variables.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-checkbox/fixture.scss
test/screenshot/spec/mdc-checkbox/mixins/ripple-size.html
test/scss/_feature-targeting-test.scss

BREAKING CHANGE: Renamed sass mixin `mdc-checkbox-touch-dimension` => `mdc-checkbox-ripple-size`. Also renamed 2 other sass variables accordingly.

fix(checkbox): Fix checkbox terminology in sass mixins

---

packages/mdc-chips/_mixins.scss

For chips with an increased touch target, the touch target element should not block clicks on the trailing icon.

fix(chips): Stack trailing/leading icons above touch target in input chips.

---

packages/mdc-tab/_mixins.scss

Styles were accidentally changed in 
https://github.com/material-components/material-components-web/commit/c7efc10afea37f724c7c258e80dfd95a455f31d8#diff-d1669061bc1d2998fb197e25382d0f6c

fix(tabs): Fix tab img icon styling.

---

packages/mdc-rtl/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-rtl/variables/include.html

`mdc-rtl` mixin already covers this condition.

fix(rtl): Removed mdc-rtl-include check from mdc-rtl-reflexive mixin

---

packages/mdc-floating-label/_variables.scss
packages/mdc-notched-outline/_mixins.scss
packages/mdc-notched-outline/_variables.scss
packages/mdc-notched-outline/mdc-notched-outline.scss
packages/mdc-notched-outline/package.json
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/mdc-text-field.scss
packages/mdc-typography/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-textfield/classes/textarea-invalid.html
test/screenshot/spec/mdc-textfield/fixture.js
test/screenshot/spec/mdc-textfield/fixture.scss
test/screenshot/spec/mdc-textfield/mixins/height-invalid.html
test/screenshot/spec/mdc-textfield/mixins/height.html

* Added `mdc-text-field-height` and `mdc-text-field-outlined-height` mixins to set custom height for default variant and outlined text field variant.
* Floating label
* Vertically aligned to center, previously positioned `18px` from top for default variant.
* Notched outline
* Added `mdc-notched-outline-floating-label-float-position-absolute` to float label in `px` unit which is based on the component height. Previously in percentage unit which is based on float label height.
* Notch element now has transparent top border when label is center aligned to prevent jump on focused state.
* Added `mdc-notched-outline-notched-reset` to reset border for labels where it is not center aligned.
Tested on IE11, iOS browser, Firefox & Chrome.
Fixes #4967 
BREAKING CHANGE: Removed sass variable in …

feat(text-field): Added mixin to set custom height and center aligned inner elements

---

packages/mdc-tab-indicator/_mixins.scss

Accidentally removed in
https://github.com/material-components/material-components-web/commit/c7efc10afea37f724c7c258e80dfd95a455f31d8#diff-d1669061bc1d2998fb197e25382d0f6c

fix(tabs): Fix tab indicator underline not being centered in compact tabs.

---

docs/framework-wrappers.md

Replace link to Vue MDC Adapter with a non-deprecated fork
closes #5071

docs: replace deprecated link in framework-wrappers

---

lerna.json
package.json
scripts/canary-release.sh
scripts/pre-release.sh

* This script fully automates publishing current commit to NPM and also creating a release on git.
* Releases are tagged to `@canary` so MDC Web frameworks can always point to `material-components-web@canary` or `@material/button@canary` which'll be always synced to `develop` branch (Latest updates to MDC Web including breaking changes).
* Create a GitHub Action to automatically run this script on every merge to `develop` branch.

chore: Add a script to automate creating pre-release (canary)

---

packages/mdc-drawer/_mixins.scss
packages/mdc-list/README.md
packages/mdc-list/_mixins.scss
packages/mdc-list/_variables.scss
packages/mdc-list/package.json
test/screenshot/golden.json
test/screenshot/spec/mdc-list/classes/list-group.html
test/screenshot/spec/mdc-list/classes/two-line.html
test/screenshot/spec/mdc-list/fixture.scss
test/screenshot/spec/mdc-list/mixins/density-checkbox.html
test/screenshot/spec/mdc-list/mixins/density.html
test/screenshot/spec/mdc-list/mixins/shape-single-line.html
test/scss/_feature-targeting-test.scss

* Added `mdc-list-single-line-density()` mixin to customize density of single line list variant.
* Fixed shape mixin to accept percentage radius value.
* Added additional screenshot tests (Two-line, shape etc).
BREAKING CHANGE: Renamed mixin `mdc-list-item-shape-radius()` => `mdc-list-single-line-shape-radius()`
Fixes #5046

feat(list): Add density mixin to list

---

packages/mdc-textfield/README.md
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/icon/mdc-text-field-icon.scss
packages/mdc-textfield/package.json
test/screenshot/golden.json
test/screenshot/spec/mdc-textfield/fixture.scss
test/screenshot/spec/mdc-textfield/mixins/density-invalid.html
test/screenshot/spec/mdc-textfield/mixins/density-leading-icon-invalid.html
test/screenshot/spec/mdc-textfield/mixins/density-leading-icon.html
test/screenshot/spec/mdc-textfield/mixins/density.html

feat(text-field): Add density mixin to text field variants

---

packages/mdc-textfield/foundation.ts
test/screenshot/spec/mdc-textfield/fixture.js
test/unit/mdc-textfield/foundation.test.js

fix(text-field): Do not trigger shake animation when text field is empty

---

package-lock.json
packages/mdc-button/_mixins.scss
packages/mdc-button/_variables.scss
packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss
packages/mdc-chips/_variables.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-chips/fixture.scss
test/screenshot/spec/mdc-chips/mixins/density.html
test/scss/_feature-targeting-test.scss

Fixes #5100:
* Adds density mixin to chip, with supported values `0` (default), `-1`, and `-2`
* Adds screenshot test for chip with density mixin applied

feat(chip): Add density mixin to chip.

---

packages/mdc-button/_mixins.scss
test/scss/_feature-targeting-test.scss

Resets styles related to touch target when density applied since dense component don't necessarily need additional touch target.

fix(button): Adjust touch target size when density is applied

---

packages/mdc-select/icon/README.md

The select component currently does not support custom trailing icons, and the `mdc-select--with-trailing-icon` class has no effect. This update removes the text that mentions the `mdc-select--with-trailing-icon` class.

docs: remove `mdc-select--with-trailing-icon`

---

packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss
packages/mdc-switch/README.md
packages/mdc-switch/_mixins.scss
packages/mdc-switch/_variables.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-switch/fixture.js
test/screenshot/spec/mdc-switch/fixture.scss
test/screenshot/spec/mdc-switch/mixins/density.html
test/scss/_feature-targeting-test.scss

Fixes #5124 and #5104 
* Add mdc-switch-density, mdc-switch-ripple-size mixins
* Rename $mdc-switch-tap-target-size => $mdc-switch-ripple-size, to be consistent with e.g. checkbox
BREAKING CHANGE: Renames switch variables `$mdc-switch-tap-target-size` => `$mdc-switch-ripple-size`, removes `$mdc-switch-tap-target-initial-position` and `$mdc-switch-native-control-width`.

feat(switch): Add density support for switch component.

---

packages/mdc-density/_variables.scss
packages/mdc-radio/README.md
packages/mdc-radio/_mixins.scss
packages/mdc-radio/_variables.scss
packages/mdc-radio/package.json
test/screenshot/golden.json
test/screenshot/spec/mdc-radio/classes/baseline-touch-target.html
test/screenshot/spec/mdc-radio/fixture.js
test/screenshot/spec/mdc-radio/fixture.scss
test/screenshot/spec/mdc-radio/mixins/density.html
test/scss/_feature-targeting-test.scss

* Added `mdc-radio-ripple-size($size)` & `mdc-radio-density($density-scale)` mixins to adjust component dimension.
* Renamed `$mdc-radio-touch-area` => `$mdc-radio-ripple-size` to be consistent with checkbox.
* Renamed `$mdc-radio-ui-size` => `$mdc-radio-icon-size` to be consistent with checkbox.
* Removed `$mdc-radio-ui-pct` sass variable.
BREAKING CHANGE: In Checkbox, Renamed sass variables `$mdc-radio-touch-area` => `$mdc-radio-ripple-size` & `$mdc-radio-ui-size` => `$mdc-radio-icon-size` to be consistent with checkbox. Also, removed `$mdc-radio-ui-pct` sass variable.
Fixes #5102 #5101

feat(radio): Add density mixin to radio

---

packages/mdc-checkbox/_mixins.scss
packages/mdc-checkbox/_variables.scss
packages/mdc-checkbox/package.json

It was original introduced in #381 but no longer required.

fix(checkbox): Remove RTL styles from checkbox ripple

---

packages/mdc-ripple/_mixins.scss
packages/mdc-switch/README.md
packages/mdc-switch/_mixins.scss

Allow customization of ripple opacity in MDC switch.

feat(switch): add ripple opacity customization mixins

---

packages/mdc-notched-outline/_mixins.scss
packages/mdc-textfield/_mixins.scss
test/screenshot/golden.json

Other changes:
- notched-outline: Remove padding calculation from notch offset
- Removed applying color to asterisk since it is inherited from parent (floating label).
This PR keeps text field in sync with internal version.

fix(text-field): Fixes input text alignment on IE11 for densed textfield 2

---

packages/mdc-tab-bar/README.md
packages/mdc-tab-bar/_mixins.scss
packages/mdc-tab-bar/package.json
test/scss/_feature-targeting-test.scss

Since Tab Scroller is a helper component that clients may not have access to uses this new mixin (`mdc-tab-bar-tab-scroller-transition()` calls `tab-scroller-transition()`) that sets styles to child component.

feat(tab-bar): Add a mixin to set scroller animation

---

packages/mdc-ripple/README.md
packages/mdc-ripple/_mixins.scss
packages/mdc-switch/_mixins.scss

This addresses the issue of easy re-usability of ripple opacity mix-ins across all components, not just switch, as raised in #5126. It introduces a single interface for customizing one or more ripple states. Changes are backwards compatible, since old mixins for customizing individual ripple states are kept and simply wrapped in the new mixin.

refactor(switch): move core ripple opacity logic from switch to ripple

---

packages/mdc-button/README.md
packages/mdc-button/_mixins.scss
packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
packages/mdc-chips/README.md
packages/mdc-chips/_mixins.scss
packages/mdc-radio/README.md
packages/mdc-radio/_mixins.scss
packages/mdc-touch-target/README.md
packages/mdc-touch-target/_mixins.scss
packages/mdc-touch-target/mdc-touch-target.scss
test/scss/_feature-targeting-test.scss

This will make it more transparent to clients that the wrapper element is part of the touch target configuration, as well as make future changes easier.

fix(touch-target): Add class to touch target wrapper.

---

packages/mdc-linear-progress/README.md
packages/mdc-linear-progress/adapter.ts
packages/mdc-linear-progress/component.ts
packages/mdc-linear-progress/foundation.ts
test/unit/mdc-linear-progress/foundation.test.js

This fixes the bug where if the bar is in indeterminate state,
setting it to reverse after the page has loaded will cause the animation timers to go out of
sync and make the bar look funny.
BREAKING CHANGE: adapter has new forceLayout() method

fix(linear-progress): Fix indeterminate animation bug

---

packages/mdc-ripple/_mixins.scss

fix(ripple): Remove unnecessary overflow: hidden.

---

packages/mdc-linear-progress/_mixins.scss
packages/mdc-linear-progress/_variables.scss

Adds styles to ensure that the progress bar is visible Windows high contrast mode.
Summary of issue:
- When in HCM on IE/Firefox, the browsers force all background-colors to the same color. This makes the progress bar invisible in those browsers.
Changes:
- Adds invisible outline around the entire component. The outline is rendered in a high contrast color when HCM is enabled.
- Updated inner bar colors using a border instead of background-color. This appears visually the same as the background-color in standard browser. In HCM, the browser recolors the bar to a high-contrast color which is easy to see.
Tested:
- Checked spec/mdc-linear-progress/classes/baseline.html to ensure no regressions in standard browser environment.
- Checked spec/mdc-linear-progress/classes/baseline.html in …

fix(linearprogress): Supports high contrast mode

---

packages/mdc-icon-button/README.md

As it already happens by default.
Fixes #5192

docs: Removed icon toggle unbounded = true in docs 

---

packages/mdc-tab-scroller/README.md
packages/mdc-tab-scroller/foundation.ts
test/unit/mdc-tab-scroller/foundation.test.js

feat(tab-scroller): Add incrementScrollImmediate to bypass animation

---

packages/mdc-menu-surface/index.ts

This addresses issue: https://github.com/material-components/material-components-web/issues/5198
The removed variables are already exported below when all constants are exported.

fix(menu-surface): remove duplicate export from menu-surface

---

packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-checkbox/fixture.scss
test/screenshot/spec/mdc-checkbox/mixins/ink-color.html

Adds the `mdc-checkbox-disabled-container-colors` and `mdc-checkbox-disabled-ink-color` mixins to allow customizing disabled state colors. 
Screenshot test for ink colors that was previously removed has been re-added. (fixes #4774)
BREAKING CHANGE: `mdc-checkbox-ink-color` mixin now only applies to enabled checkboxes

feat(checkbox): Add disabled state color mixins

---

packages/mdc-radio/README.md
packages/mdc-radio/_mixins.scss
packages/mdc-radio/_variables.scss
test/screenshot/golden.json
test/screenshot/spec/mdc-radio/fixture.scss

Adds the `mdc-radio-disabled-unchecked-stroke-color`, `mdc-radio-disabled-checked-stroke-color`, and the `mdc-disabled-radio-ink-color` mix-ins for radio buttons in disabled state.

feat(radio): Add disabled state color mixins

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss

- Updated text field shape mixins to set density scale instead of height to be consistent with other component's shape mixins.
- Renamed `$mdc-text-field-density-default-scale` => `$mdc-text-field-density-scale`

fix(text-field): Updated shape mixins to set density scale

---

packages/mdc-drawer/README.md

In response to the comment suggesting this solution for responsive drawers in https://github.com/material-components/material-components-web/issues/4802#issuecomment-501823698

docs(drawer): add link to suggested implementation for responsive drawer

---

.github/workflows/release-canary.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml

* Updated canary release action to create canary tag based on `master` branch (Previously on `develop` branch).
* New GitHub action to create release pull request that bumps MDC Web & automatically creates changelog.
* New GitHub action that is triggered when release pull request is merged, creates a new git tag & publishes to npm registry.

chore: GitHub Actions to automate minor / major releases

---

packages/mdc-select/README.md
packages/mdc-select/icon/README.md

Notched outline and icons should be inside `mdc-select__anchor`.

docs(select): Update for HTML changes

---

.github/workflows/release-pull-request.yml

Lerna.js does not allow creating release on `master`, had to create a new local branch based on master.
Here is a sample error from recent [GitHub Action](https://github.com/material-components/material-components-web/commit/a59617495c809d5d70ce7df0d127d996b69a51a0/checks?check_suite_id=299052838):
```sh
$ npx lerna version --conventional-commits --no-git-tag-version --no-push --yes
lerna notice cli v3.14.1
lerna info current version 4.0.0
lerna ERR! ENOGIT Detached git HEAD, please checkout a branch to choose versions.
##[error]Process completed with exit code 1.
```

chore: create local branch based on master before release

---

.github/workflows/release-pull-request.yml

actions/checkout seem to have a [bug](https://github.com/actions/checkout/issues/6) where it checkout detached to HEAD.  Changed base branch from `master` to `refs/remotes/origin/master`. 
Excerpts from previous action:
```
$ git checkout --progress --force refs/remotes/origin/master
Note: switching to 'refs/remotes/origin/master'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
```
```
$ git checkout -B release/lerna master
fatal: 'master' is not a commit and a branch 'release/lerna' cannot be created from it.
```

chore: change checkout branch master => chore/actions_fix_checkout

---

.github/workflows/release-canary.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml

actions/checkout does not seem to give access to latest copy of `master` 🤦🏻‍♂️, explicitly checkout master branch and pull changes.

chore: Fix checkout in release action

---

CHANGELOG.md

Indent code examples same as list in rendered markdown.
Add syntax highlighting for HTML code.

docs: Fix code examples

---

packages/mdc-button/README.md
packages/mdc-button/_mixins.scss

fix(button): Fixed  parameter default value in height mixin

---

packages/mdc-button/_mixins.scss
packages/mdc-checkbox/_mixins.scss
packages/mdc-chips/_mixins.scss
packages/mdc-fab/_mixins.scss
packages/mdc-radio/_mixins.scss
packages/mdc-touch-target/README.md
packages/mdc-touch-target/_mixins.scss
test/scss/_feature-targeting-test.scss

BREAKING CHANGE: Mixin renaming from mdc-touch-target-component => mdc-touch-target-margin

refactor(touchtarget): Rename mdc-touch-target-component => mdc-touch-target-margin.

---

packages/mdc-dialog/README.md
test/screenshot/spec/mdc-dialog/mixins/container-fill-color.html
test/screenshot/spec/mdc-dialog/mixins/content-ink-color.html
test/screenshot/spec/mdc-dialog/mixins/max-height.html
test/screenshot/spec/mdc-dialog/mixins/max-width.html
test/screenshot/spec/mdc-dialog/mixins/min-width.html
test/screenshot/spec/mdc-dialog/mixins/scrim-color.html
test/screenshot/spec/mdc-dialog/mixins/scroll-divider-color.html
test/screenshot/spec/mdc-dialog/mixins/shape-radius.html
test/screenshot/spec/mdc-dialog/mixins/title-ink-color.html

This fixes an issue in ChromeVox on ChromeOS where the screenreader was able to navigate outside of the dialog, to the scrim element.
See cl/277146439 for context.

fix(dialog): Move aria roles from dialog root to dialog surface element.

---

docs/framework-wrappers.md

The purpose of this change is to let the reader know that react material web components is no longer under active development.

docs: Update status of react material web components

---

packages/mdc-elevation/README.md
packages/mdc-elevation/_functions.scss
packages/mdc-elevation/_mixins.scss
packages/mdc-elevation/_variables.scss
packages/mdc-elevation/common.scss
packages/mdc-elevation/package.json
test/scss/_feature-targeting-test.scss

Add mixins to set the overlay fill color, opacity, size, parent position, and shadow.
BREAKING CHANGE: Functions moved into the `_functions.scss` file

feat(elevation): Add elevation overlay mixins

---

packages/mdc-linear-progress/README.md
packages/mdc-linear-progress/adapter.ts
packages/mdc-linear-progress/component.ts
packages/mdc-linear-progress/constants.ts
packages/mdc-linear-progress/foundation.ts
test/unit/mdc-linear-progress/foundation.test.js
test/unit/mdc-linear-progress/mdc-linear-progress.test.js

fix(linear-progress) support aria attributes
Adds aria attributes to MDC Linear progress to support screen readers.
BREAKING CHANGE: Adds new adapter methods to MDCLinearProgressAdapter.

fix(linear-progress): Add aria attributes to linear progress bar to support screen readers

---

packages/mdc-chips/README.md
packages/mdc-chips/chip/component.ts
packages/mdc-chips/chip/foundation.ts
test/unit/mdc-chips/mdc-chip.foundation.test.js
test/unit/mdc-chips/mdc-chip.test.js

Consolidate interaction event handlers into discrete root-level handlers: `handleClick` and `handleKeydown`.
BREAKING CHANGE: the `handleInteraction` and `handleTrailingIconInteraction` handlers have been removed from the `MDCChipFoundation`. The `handleClick` handler has been added to the `MDCChipFoundation`

feat(chips): Consolidate interaction event handlers

---

packages/mdc-button/README.md
packages/mdc-button/_mixins.scss
packages/mdc-checkbox/README.md
packages/mdc-checkbox/_mixins.scss
packages/mdc-fab/README.md
packages/mdc-fab/_mixins.scss
packages/mdc-radio/README.md
packages/mdc-radio/_mixins.scss
packages/mdc-ripple/README.md
packages/mdc-ripple/_mixins.scss
packages/mdc-ripple/util.ts
packages/mdc-theme/README.md
packages/mdc-theme/_mixins.scss
test/unit/mdc-ripple/util.test.js

BREAKING CHANGE: Removed `$edgeOptOut` option from `mdc-theme-prop()` Sass mixin.
This is no longer requires since the references bug seems to be fixed. See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11495448/
cl/281379665

fix(theme): Remove edge detection for CSS custom properties

---

packages/mdc-checkbox/_mixins.scss
packages/mdc-theme/_variables.scss

Preview:
HC theme 1:
HC theme 2:

fix(checkbox): Disabled state colors in IE11 high contrast mode

---

packages/mdc-button/_mixins.scss
packages/mdc-button/_variables.scss
test/screenshot/golden.json

Closes #5170 
Enabled outline color: primary -----> 12% on-surface.
Disabled outline color: 38% on-surface -----> 12% on-surface.
Disabled ink color: 37% ---> 38% on-surface.
BREAKING CHANGE: Variable `$mdc-button-disabled-container-fill-color`
renamed to `$mdc-button-disabled-container-color`.

fix(button): Fix outline & ink color according to spec guidance

---

packages/mdc-chips/chip-set/foundation.ts
test/unit/mdc-chips/mdc-chip-set.foundation.test.js

fix(chips): Do not throw error if chip set becomes empty

---

packages/mdc-chips/README.md
packages/mdc-chips/chip/component.ts
packages/mdc-chips/chip/foundation.ts
test/unit/mdc-chips/mdc-chip.foundation.test.js
test/unit/mdc-chips/mdc-chip.test.js

Reverts material-components/material-components-web#5251

revert: feat(chips): Consolidate interaction event handlers

---

packages/mdc-chips/chip-set/foundation.ts
test/unit/mdc-chips/mdc-chip-set.foundation.test.js

Reverts material-components/material-components-web#5290

revert: fix(chips): Do not throw error if chip set becomes empty

---

packages/mdc-button/_mixins.scss
packages/mdc-chips/_mixins.scss
packages/mdc-dialog/_mixins.scss
packages/mdc-elevation/README.md
packages/mdc-elevation/_mixins.scss
packages/mdc-fab/_mixins.scss
packages/mdc-menu/_mixins.scss
test/scss/_feature-targeting-test.scss

Set overlay dimensions in one mixin instead of sizing and positioning in separate mixins

feat(elevation): Update elevation mixins

---

package.json
packages/mdc-fab/_mixins.scss
test/scss/_feature-targeting-test.scss

The `test:feature-targeting` check wasn't running on the CI and was failing as a result. Furthermore, since the check wasn't running, there were some `mdc-fab` styles that weren't under a feature target which will cause them to always be emitted.

chore: fix and run feature tageting checks

---

karma.conf.js
tsconfig-base.json
tsconfig.json

For some reason, test files in the tsconfig are causing `package/<component>/index.js` not to be generated when running `npm run build:esmodules`, leading to a failure in the canary release: https://github.com/material-components/material-components-web/runs/340549500

fix(core): Fix canary release by excluding test files from default tsconfig

---

scripts/travis-env-vars.sh

This is suspected to be preventing screenshot tests from running (e.g. #5323).

fix(testing): Revert change from #5299.

---

packages/mdc-list/_mixins.scss

fix(list): Ensure disabled colors apply to primary and secondary text

---

packages/mdc-elevation/_mixins.scss

Mixin previously always included the `.mdc-elevation-overlay` class, making it impossible to override the colors without a wrapping element. Now, a custom class can be applied to the overlay element and the colors can be overridden with no additional specificity or DOM changes.

fix(elevation): Restructure overlay color mixin

---

packages/mdc-select/foundation.ts

Need to call notch first to get width of label before it floats (and is consequentially shrunk). Same behavior as outlined textfield

fix(select): Fix notch outline width when floating

---

test/screenshot/diffing.json

- Skip invalid textarea on FF, as this is consistently flaking
- Increase animation delay for menu on FF

test(infra): Reduce screenshot test flakiness.

---

package.json

Currently, `npm run test:unit` will incorrectly exit with success code 0 even if the Jasmine tests fail. This fixes to exit with code 1 if either Jasmine or Mocha tests fail, while still running the Mocha tests even if Jasmine tests fail.

test(infra): Fix `npm run test:unit` to exit with code 1 if Jasmine or Mocha tests fail.

---

packages/mdc-line-ripple/_mixins.scss
packages/mdc-line-ripple/mdc-line-ripple.scss
packages/mdc-line-ripple/package.json
test/scss/_feature-targeting-test.scss

Adds support for feature targeting to the `mdc-line-ripple` styles.
Relates to #4227.

feat(line-ripple): add feature targeting for styles

---

packages/mdc-floating-label/_mixins.scss
packages/mdc-floating-label/mdc-floating-label.scss
packages/mdc-floating-label/package.json
test/scss/_feature-targeting-test.scss

Adds support for feature targeting to the `mdc-floating-label` styles.
Relates to #4227.

feat(floating-label): add feature targeting for styles

---

packages/mdc-checkbox/_functions.scss
packages/mdc-data-table/_variables.scss
packages/mdc-list/_variables.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/icon/_mixins.scss

Add missing dependencies to five files that previously didn't depend on all the stylesheets they reference (even indirectly). This caused issues with the module system migrator (#5220), so this fix is necessary for that.

fix: add missing dependencies

---

packages/mdc-checkbox/README.md
packages/mdc-checkbox/adapter.ts
packages/mdc-checkbox/component.ts
packages/mdc-checkbox/foundation.ts
packages/mdc-checkbox/test/component.test.ts
packages/mdc-checkbox/test/foundation.test.ts

Reverts material-components/material-components-web#5316
Breaks MWC - should update downstream clients and sync to internal first

revert: "fix(checkbox): change checkbox event type from change to click and add some logic for IE browser"

---

karma.conf.js
packages/mdc-tab-bar/test/foundation.test.ts
testing/helpers/setup.ts

Also fixes default mock adapter to actually return default adapter function values rather than the functions themselves (e.g. Adapter#isRtl, will now return `false` rather than `() => false`.

test(tabbar): Add tabbar Jasmine foundation test.

---

packages/mdc-checkbox/_mixins.scss
packages/mdc-theme/_functions.scss

fix(checkbox): Replace unique-id with custom color hash function to generate keyframes

---

packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/component.ts
packages/mdc-textfield/constants.ts
packages/mdc-textfield/icon/README.md
packages/mdc-textfield/icon/_mixins.scss
packages/mdc-textfield/icon/constants.ts
packages/mdc-textfield/icon/mdc-text-field-icon.scss
packages/mdc-textfield/icon/test/foundation.test.ts
packages/mdc-textfield/mdc-text-field.scss
packages/mdc-textfield/test/component.test.ts
test/screenshot/spec/mdc-textfield/classes/baseline-leading-icon.html
test/screenshot/spec/mdc-textfield/classes/baseline-leading-trailing-icons.html
test/screenshot/spec/mdc-textfield/classes/baseline-trailing-icon.html
test/screenshot/spec/mdc-textfield/classes/baseline-without-label-with-icon.html
test/screenshot/spec/mdc-textfield/classes/disabled-leading-icon.html
test/screenshot/spec/mdc-textfield/classes/disabled-leading-trailing-icons.html
test/screenshot/spec/mdc-textfield/classes/disabled-trailing-icon.html
test/screenshot/spec/mdc-textfield/classes/focused-leading-icon.html
test/screenshot/spec/mdc-textfield/classes/focused-leading-trailing-icons.html
test/screenshot/spec/mdc-textfield/classes/focused-trailing-icon.html
test/screenshot/spec/mdc-textfield/classes/invalid-focused-leading-icon.html
test/screenshot/spec/mdc-textfield/classes/invalid-focused-leading-trailing-icons.html
test/screenshot/spec/mdc-textfield/classes/invalid-focused-trailing-icon.html
test/screenshot/spec/mdc-textfield/classes/invalid-leading-icon.html
test/screenshot/spec/mdc-textfield/classes/invalid-leading-trailing-icons.html
test/screenshot/spec/mdc-textfield/classes/invalid-trailing-icon.html
test/screenshot/spec/mdc-textfield/mixins/density-leading-icon-invalid.html
test/screenshot/spec/mdc-textfield/mixins/density-leading-icon.html
test/screenshot/spec/mdc-textfield/mixins/disabled-1.html
test/unit/mdc-textfield/mdc-text-field-icon.test.js

BREAKING_CHANGE: icons must use `.mdc-text-field__leading-icon` or `.mdc-text-field__trailing-icon` classes. `mdc-text-field-icon-color()` mixin has been split into `mdc-text-field-leading-icon-color()` and `mdc-text-field-trailing-icon-color()`.

fix(textfield): add separate classes for leading/trailing icons

---

packages/mdc-button/_mixins.scss
packages/mdc-checkbox/_mixins.scss
packages/mdc-fab/_mixins.scss
packages/mdc-switch/_mixins.scss
packages/mdc-tab-scroller/_mixins.scss
packages/mdc-tab/_mixins.scss

This replaces `__` and `--` in certain mixin names with a single dash to
allow migrating to the module system without breaking downstream users
that use these pseudoprivate mixins.

refactor: avoid BEM naming for mixins

---

packages/mdc-dom/README.md
packages/mdc-dom/ponyfill.ts
packages/mdc-floating-label/component.ts
packages/mdc-floating-label/package.json
packages/mdc-textfield/test/component.test.ts
test/unit/mdc-dom/ponyfill.test.js

In some cases, the floating label needs to immediately know its width. This creates problems if the floating label is instantiated inside a `display: none;` parent element, like a hidden dialog. To resolve that, we provide a helper method that estimates the width of an element if hidden. If visible, it computes the true width.

fix(floatinglabel): Estimate hidden scroll width

---

packages/mdc-auto-init/index.ts

`mdc-auto-init/index.d.ts`:
**Before ([ref](https://unpkg.com/browse/@material/auto-init@4.0.0/index.d.ts)):**
```ts
export default mdcAutoInit;
export default mdcAutoInit;
```
**After:**
```ts
export default mdcAutoInit;
export { mdcAutoInit };
```
Closes #5158

fix(auto-init): Fixed issue with multiple default exports

---

.github/workflows/test.yml
.gitignore
jasmine-node.json
karma.conf.js
package.json
packages/mdc-button/test/feature-targeting-all.test.scss
packages/mdc-button/test/feature-targeting-any.test.scss
packages/mdc-button/test/mdc-button.scss.test.ts
test/scss/_feature-targeting-test.scss
testing/helpers/sass-test-compile.helper.ts
testing/helpers/ts-node.helper.js
tsconfig-node.json

* Moved button feature targeting tests from `test/scss/_feature-targeting-test.scss` to use Jasmine node test.
* `testing/helpers/sass-test-compile.helper.ts` helper is executed before tests to compile all Sass test files to CSS for Jasmine node test consumption.
* New tsconfig (`tsconfig-node.json`) for Node.js code written in TypeScript.
* Updated GitHub Actions `.github/workflows/test.yml` to run this on CI.

test(feature-targeting): Migrate feature targeting tests to jasmine

---

packages/mdc-slider/_mixins.scss

Overcomes css limitation of not being able to use a hex value inside of an rgba value by using the after pseudo class and applying opacity on it instead.  In this way, the container and track are left alone and only the track container has the opacity applied to it.

fix(slider): use secondary custom property color for slider container

---

packages/mdc-slider/_mixins.scss

Changes tab to spaces. This was already changed to spaces internally with [cl/290088778](http://cl/290088778), so we just need to update GitHub to match.

chore: update slider mixins indentation

---

packages/mdc-layout-grid/README.md

docs(layout-grid): fix incorrect variable name

---

README.md
docs/migrating-from-mdl.md
packages/mdc-auto-init/README.md
packages/mdc-floating-label/README.md
packages/mdc-notched-outline/README.md
packages/mdc-select/README.md
packages/mdc-textfield/README.md
packages/mdc-textfield/helper-text/README.md
packages/mdc-textfield/icon/README.md
packages/mdc-textfield/icon/foundation.ts
packages/mdc-textfield/test/component.test.ts
test/screenshot/spec/mdc-rtl/variables/include.html
test/screenshot/spec/mdc-shape/variables/override.html

BREAKING CHANGE: text field's root element has changed from a `<div>` to a `<label>`. Existing labels should be changed to `<span>` with an ID. `<input>` should use `aria-labelledby` and reference span's ID

fix(textfield): change root element to <label>

---

packages/mdc-slider/_mixins.scss

These changes fix the following issues which were introduced by #5132:
1. The background of track is now provided by `.mdc-slider__track-container::after`, however `::after` wasn't positioned correctly which made it invisible.
2. The `::after` structural styles were set inside the `color` feature target. This means that they'll end up being included multiple times and in the wrong place.
Screenshot for reference:

fix(slider): slider track not visible

---

packages/mdc-icon-button/README.md

Remove an aria-hidden="true" attribute from the <button> element in some of the HTML examples.
The attribute would hide the element from the accessibility tree, making it inaccessible.
Fix #5509.

docs(icon-button): remove stray aria-hidden

---

packages/mdc-chips/chip/foundation.ts
packages/mdc-chips/chip/test/foundation.test.ts

fix(chips): Fix browser back nav in FF when removing chip with backspace key.

---

packages/mdc-line-ripple/_mixins.scss
packages/mdc-line-ripple/test/feature-targeting-any.test.scss
packages/mdc-select/_mixins.scss
packages/mdc-textfield/_mixins.scss

BREAKING CHANGE: `mdc-line-ripple-color()` mixin has been renamed to `mdc-line-ripple-active-color()`

feat(line-ripple): add active/inactive states to line-ripple

---

packages/mdc-chips/README.md
packages/mdc-chips/chip-set/adapter.ts
packages/mdc-chips/chip-set/component.ts
packages/mdc-chips/chip-set/foundation.ts
packages/mdc-chips/chip-set/test/component.test.ts
packages/mdc-chips/chip-set/test/foundation.test.ts
packages/mdc-chips/chip/adapter.ts
packages/mdc-chips/chip/component.ts
packages/mdc-chips/chip/constants.ts
packages/mdc-chips/chip/foundation.ts
packages/mdc-chips/chip/test/foundation.test.ts
packages/mdc-chips/chip/types.ts
packages/mdc-chips/package.json

- Update MDCChipAdapter to include a `getAttribute` method
- Update MDCChipRemovalEventDetail to include a nullable `removedAnnouncement` property
- Update MDCChipsetAdapter to include a `announceMessage` method
BREAKING CHANGE: Both `MDCChipAdapter` and `MDCChipSetAdapter` have new methods. `MDCChipSetFoundation` event handlers now accept the corresponding chip event detail interface as the sole argument. The `root` property has been removed from the `MDCChipRemovalEventDetail` interface.

feat(chips): Announce when chips are removed

---

packages/mdc-textfield/_mixins.import.scss

Fixes an error that was due to a `@forward` which is pointing to an incorrect file path. Seems to have been introduced in https://github.com/material-components/material-components-web/commit/181486643532e2166dced95daff9da786af3bdd1.

fix(textfield): incorrect mixin forward path

---

packages/mdc-select/README.md

The `aria-selected="true"` attribute was given to the wrong element.
The "Vegetables" option is an example of a disabled item.
The "" option should be the example selected item and have the aria-selected attribute.

docs(select): fix aria attribute on select example

---

packages/mdc-textfield/_mixins.import.scss
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss

BREAKING CHANGE: Filled textfields will no longer show a floating label at certain densities. This can be overridden by setting `$mdc-text-field-minimum-height-for-filled-label: 40px`.

fix(textfield): hide filled-variant floating label at <52px

---

docs/migrating-from-mdl.md
packages/mdc-auto-init/README.md
packages/mdc-textfield/README.md
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss

BREAKING CHANGE: filled text fields must include a `<div class="mdc-text-field__ripple"></div>`

fix(textfield): move ripple to separate element

---

packages/mdc-chips/chip/foundation.ts

Due to the way a comment was formatted in the chip foundation the .d.ts bundler ended up generating a file with a syntax error.
For reference, here's what was being generated:

fix(chips): .d.ts file generated with syntax error

---

packages/mdc-typography/_mixins.scss

Was causing sass test to fail and blocking PR merging.

fix(typography): Separate @material/feature-targeting

---

scripts/check-pkg-for-release.js

This will unblock incremental PRs for the component from merging (i.e. #5636).

chore: Exclude WIP circular progress from dependency test

---

packages/mdc-checkbox/_variables.scss

Previously, the secondary color was by default used for the background
of the checkbox and on-primary was used for the color of the checkmark.
Fixes #5730

fix(checkbox): Use secondary and on-secondary as default colors

---

packages/mdc-list/README.md

closes #5738 
>note: I've previously signed the CLA with contributions to the now abandoned @material/react-* project.

docs(list): accurately notes vertical orientation as the default

---

packages/mdc-list/README.md

closes #5752 
`selectedIndex` is not a boolean, but a  `MDCListIndex` ( `number[] | number` )

docs(list): use MDCListIndex for selectedIndex type

---

packages/mdc-data-table/_mixins.scss

In Angular Material component themes are implemented using classes (e.g. `.dark-theme{ @include mdc-core-styles() }`), however the data table color styles were inside an `@at-root` which causes them to always be generated at the root, circumventing any parent classes. These changes move it outside the `@at-root` since the mixins already have their selectors baked in.

fix(data-table): unable to redefine colors in class-based theming

---

package.json

Tests are failing at `npm i` (`postinstall: lerna bootstrap`) step with following error message:
```
> undefined postinstall /home/runner/work/material-components-web/material-components-web
> lerna bootstrap
lerna notice cli v3.20.2
lerna info ci enabled
lerna info Bootstrapping 46 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in '@material/auto-init'
lerna ERR! npm ci stderr:
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-04-02T17_49_14_281Z-debug.log
lerna ERR! npm ci exited 1 in '@material/auto-init'
lerna WARN …
```

chore: possible fix for package-lock issue on npm i

---

packages/mdc-linear-progress/foundation.ts
packages/mdc-slider/foundation.ts

The linear progress and slider components were trying to access `window` as a global directly which will throw under Node environments. These changes add a `typeof` guard infront of it to avoid the error.
**Note:** ideally `getCorrectPropertyName` and `getCorrectEventName` would get the `window` themselves manually and would do the `typeof` check internally, but it seems like the `windowObj` parameter is used when unit testing and there's no nice way around it. Also changing the signature would be a breaking change.

fix: server-side rendering errors in linear progress and slider

---

packages/mdc-slider/foundation.ts

Recently with d10412cb24150639acc617caef1c7fac4fb6e4bd, support for pointer events has been
added to the `MdcSlider`. The feature detection for pointer events currently fails
on the server as it accesses `window` directly. We should not error if we are on the
server as these events are not having any effect anyway.

fix(mdc-slider): avoid server side rendering error

---

packages/mdc-dialog/_mixins.scss

fix(dialog): Only equalize paddings for scrollable dialogs with titles, since there is no added divider between title/content in this case.

fix(dialog): Only equalize paddings for scrollable dialogs with titles, since there is no added divider between title/content in this case.

---

packages/mdc-textfield/icon/README.md

Update the documentation for the three icon-color mixins to remove the  mdc-text-field prefix that was moved with the Sass upgrade. Add documentation for the size mixin.

docs(textfield): Update icon README new and renamed Sass mixins

---

packages/mdc-line-ripple/README.md

Change Sass mixin listing to include both active-color() and inactive-color(), instead of the deprecated color() mixin

docs(line-ripple): update README for active/inactive color change

---

.stylelintrc.yaml

Re-importing sasslint rules. Changes seems to have reverted with recent Copybara manual sync.

chore: import sasslint rules

---

.gitignore
.sassrc.js
docs/local-development.md

See [local development document](https://github.com/material-components/material-components-web/blob/891b5c03bd05586618c41768385ceb8b9bae4d9a/docs/local-development.md) for preview.

chore: Added support to run demos for local development

---

.stylelintrc.yaml

Syncs with internal Sass lint rules.

chore: Removed number-leading-zero from Sass lint rule

---

.stylelintrc.yaml

This was removed recently in internal sass/stylelint/stylelintrc.yaml, since we now use Prettier for formatting, which auto-adds leading zeros.

test(infra): Remove number-leading-zero rule.

---

packages/mdc-button/package.json
packages/mdc-card/package.json
packages/mdc-density/package.json
packages/mdc-elevation/package.json
packages/mdc-fab/package.json
packages/mdc-feature-targeting/package.json
packages/mdc-image-list/package.json
packages/mdc-layout-grid/package.json
packages/mdc-rtl/package.json
packages/mdc-shape/package.json
packages/mdc-theme/package.json
packages/mdc-touch-target/package.json
packages/mdc-typography/package.json

Currently some packages aren't marked with `sideEffects: false` which can have an effect on dead code elimination. These changes add the flag to all of the packages.

fix: mark all packages as side-effect-free

---

scripts/check-pkg-for-release.js

After this change material-components-web.scss file can import `/styles` Sass file.
Example:
```scss
@use "@material/segmented-button/styles";
```

chore: Fix CSS dependency test to accept new Sass style pattern

---

packages/mdc-snackbar/_mixins.scss

Same type of changes as https://github.com/material-components/material-components-web/pull/5751
The Angular Material styles add a dark-themed snackbar since the snackbar styles use at-root.

fix(snackbar): remove use of @at-root

---

packages/mdc-dialog/component.ts
packages/mdc-dialog/test/component.test.ts

This PR fix `data-mdc-dialog-initial-focus` to work in multiple dialogs.
Fixes #6142

fix(mdc-dialog): fix `data-mdc-dialog-initial-focus` to work in multiple dialogs

---

packages/mdc-circular-progress/README.md

The README for the circular-progress component looks very different, and is missing some of the information provided by all other MDC READMEs.
This PR tries to fix that.

docs(circular-progress): Make the README look more like other components

---

packages/mdc-circular-progress/_variables.scss

Every other package !default's all of their variables, giving consumers the ability to customize them.
Circular Progress for some reason only currently !default's one, not giving full flexibility to consumers.

fix(circular-progress): Default all variables

---

package-lock.json
package.json

This will be used with https://github.com/material-components/material-components-web/pull/6257 to add ES polyfills (Array.from, Object.assign, etc.) to our external tests.

test: Add core-js to dev deps.

---

packages/mdc-button/README.md

One class is missing in the example for the contained btn

docs: Add missing css class for contained btn example

---

packages/mdc-segmented-button/segment/_segment.scss

Remove use of segment-theme mixins with references to css classes inside of references to css classes.

fix(segmented-button): Move include statements to avoid nested classes

---

docs/integrating-into-frameworks.md

Pointed to the [MDC Web on other frameworks](https://github.com/material-components/material-components-web/blob/master/docs/framework-wrappers.md) document

[docs] Pointed directly to the document with the list of component libraries

---

packages/mdc-segmented-button/README.md

Hopefully cl/332515162 fixes the issue where Copybara reverts external README file that is not synced internally.

docs: Add Segmented Button README file.

---

packages/mdc-list/foundation.ts
packages/mdc-list/test/foundation.test.ts

Adds support for the ctrl + a shortcut in a checkbox-based list which will select all enabled deselected items, or deselect everything if all items are selected.
Fixes #6366.

feat(list): support ctrl + a keyboard shortcut

---

.github/workflows/test.yml

Our current build is failing on pushes with `conventional-commit-check` error: "Error: This action can only be invoked in `pull_request` events. Otherwise the pull request can't be inferred."
Workflow syntax: https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#if-at-the-job-level

test: Run conventional-commit-check only on PR's, not pushes.

---

.github/workflows/release-pull-request.yml

Current build is failing with error:
```
Run peter-evans/create-pull-request@v2
Error: Unable to process command '::set-env name=pythonLocation::/opt/hostedtoolcache/Python/3.9.0/x64' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

build: Update to create-pull-request@v3.

---

docs/getting-started.md

Changed "Webpack-dev-server" to "webpack serve" to work with Webpack 5.
Changed the material importer to be put under 'sassOptions' rather than just options. Similar with the autoprefixer; put it under postcssOptions under options. 
Don't have issues going through the Getting Started walkthrough now

docs: Update to work with Webpack 5

---

docs/importing-js.md

`mdc-foo` is not consistent with other path examples. It let me to believe to require 'switch', for example, I'd use `require('mdc-switch')`. However, what you need is `require('@material/switch'`

docs: fix require syntax for importing javascript

---

CONTRIBUTING.md

`build:demos` command no longer supported. See #4752 for more information.
Closes #6773

docs(all): Remove 'build:demos' command

---

package-lock.json
package.json

We need to bump our Sass dependency, since some of the newer internal features (like `map.set()`) are not available in our current version and causing [build failures](https://github.com/material-components/material-components-web/pull/6810/checks?check_run_id=1834195921).

chore: update sass

---

docs/getting-started.md

- Remove `webpackImporter: false`; https://github.com/webpack-contrib/sass-loader/issues/804 seems to be fixed.
- `query` => `options` for latest babel-loader version
Tested changes locally.

docs: Update getting-started.md. Fixes #6981

---

packages/mdc-list/_evolution-mixins.scss

In Angular Material we have several components that are based on simple, single-line lists. Currently if we were to go through the `without-ripple` mixin, we would end up with a lot of unused styles, because all we care about are the base structural styles, colors and typography.
These changes make the `list-base` and `item-base` mixins public so that we have more granular control over the included styles.

refactor(list): expose evolution base mixins

---

package.json
scripts/check-pkg-for-release.js

Adds support for using TS syntax in https://github.com/material-components/material-components-web/blob/master/packages/material-components-web/index.ts

chore: support ts parsing for dependency test

---

packages/mdc-list/_evolution-mixins.scss

**fix(list): density configuration mixins do not account for leading avatars**
Currently when someone uses the MDC list w/ evolution styles, it's possible to generate secondary
styles with a different density scale. This can be achieved by using the following mixins: 
`one-line-item-density`, `two-line-item-density` and `three-line-item-density`.
These mixins currently do not account for leading avatars, unlike they do for icons, checkboxes,
switches, radio's, images and videos. This commit adds code fo leading avatars.
**refactor(list): expose evolution base mixins**
In Angular Material we have several components that are based on simple, single-line lists.
Currently if we were to go through the `without-ripple` mixin, we would end up with a lot of
unused styles, because all we care …

fix(list): density configuration mixins do not account for leading avatars

---

package-lock.json
package.json
packages/mdc-banner/_banner.scss
packages/mdc-card/_mixins.scss
packages/mdc-checkbox/_checkbox-theme.scss
packages/mdc-checkbox/_checkbox.scss
packages/mdc-chips/_chip-set-theme.scss
packages/mdc-chips/_chip-theme.scss
packages/mdc-chips/deprecated/_mixins.scss
packages/mdc-circular-progress/_mixins.scss
packages/mdc-data-table/_data-table-theme.scss
packages/mdc-dialog/_mixins.scss
packages/mdc-drawer/_mixins.scss
packages/mdc-icon-button/_mixins.scss
packages/mdc-image-list/_mixins.scss
packages/mdc-layout-grid/_mixins.scss
packages/mdc-list/_evolution-mixins.scss
packages/mdc-ripple/_ripple.scss
packages/mdc-select/_select-theme.scss
packages/mdc-select/_select.scss
packages/mdc-shape/_shape.scss
packages/mdc-slider/_slider.scss
packages/mdc-switch/deprecated/_mixins.scss
packages/mdc-textfield/_mixins.scss
packages/mdc-textfield/_variables.scss
packages/mdc-textfield/icon/_mixins.scss
packages/mdc-theme/_theme-color.scss
packages/mdc-touch-target/_touch-target.scss
packages/mdc-typography/_typography.scss

The division operator is deprecated and it causes Sass to print a warning in the latest version. These changes migrate to the `math.div` helper.
See https://sass-lang.com/documentation/breaking-changes/slash-div.

refactor: fix up sass division deprecation warnings

---

packages/mdc-touch-target/_touch-target.scss

Currently the `touch-target` mixin produces styles that will set the touch target outside of the host node on RTL layouts (see https://github.com/angular/components/pull/22925). These changes adjust the styles so that the target is always centered.

fix(touch-target): incorrect position in rtl when width is set

---

packages/mdc-list/foundation.ts

An earlier commit added a doc string with an `@return` in it (5d060518804437aa1ae3152562f1bb78b1af4aa6). By itself this isn't wrong, but it seems to hit a buggy code path in `dts-bundle` which causes it not to close a comment and to produce an invalid .d.ts file.
These changes work around the issue by using `@returns` instead. A longer term solution would be to move away from `dts-bundle` since it doesn't appear to be maintained.
For reference, here's the generated .d.ts file before these changes:

fix(mdc-list): invalid syntax in generated .d.ts bundle

---

packages/material-components-web/package.json

`@material/tokens` as dependency to `material-components-web` package is required for [CSS bundle factory](https://github.com/material-components/material-components-web/blob/3e4c6dca1921caa57e1097c03135a7ddf614f003/scripts/webpack/css-bundle-factory.js#L221).

build: add @material/tokens as dependency to material-components-web

---

.github/workflows/release-nightly.yml

Closes #7110
Screenshot of GitHub Action results when nightly script is skipped:
Screenshot of GitHub Action results when nightly script is successful:
Sample nightly publish for testing purposes:
https://www.npmjs.com/package/@material/menu/v/12.0.0-nightly.778a0e8a.0

build: Add GitHub action to publish to nightly tag

---

docs/migrating-from-mdl.md
scripts/check-pkg-for-release.js
scripts/webpack/js-bundle-factory.js

Currently if the UMD bundles from `@material/<..>` NPM modules are
loaded in the browser, using RequireJS or other loaders, the
AMD modules would need to be named manually using a loader
configuration. e.g.
```js
require.config({
paths: {
'@material/animation': '/base/npm/node_modules/@material/animation/dist/mdc.animation',
...
}
}
```
This could be avoided if the AMD `define` invocations in the UMD file
would specify a module id, similar to how it's done in packages of the
Angular organization. This allows for easier consumption in tests as well.
Note that this change causes a breaking change for the UMD-case where
the exports are bound to a global variable. Previously the entry-point
would appear in camel-case, but now it's matching the actual package
name in dash-case. This is …

build: set AMD module module names within UMD bundles

---

packages/mdc-button/README.md

There is no reference in source code to this class, which makes me think that it's just a typo for mdc-button--icon-leading

docs(button): fix button with class mdc-button--leading

---

.github/workflows/release-canary.yml
.github/workflows/release-nightly.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml
.github/workflows/test.yml
.stylelintrc.yaml
package-lock.json
package.json
packages/mdc-dialog/_mixins.scss
scripts/build/clean.js
scripts/webpack/css-bundle-factory.js
scripts/webpack/js-bundle-factory.js

These changes make this repo compile cleanly for a user running a modern version of Node, and fixes a Sass syntax error that occurs after a minor version bump.
- Remove `fibers` dependency because it is not compatible with Node 16+. It causes `npm run build` to hard-crash Node. See https://github.com/webpack-contrib/sass-loader#string and https://github.com/laverdet/node-fibers#readme.
- Bump all workflows from Node 10/12 to 14. Node 10 is no longer supported. Node 12 is maintenance LTS. Node 14 is active LTS. See https://nodejs.org/en/about/releases/
- Bump Sass version so that the next fix is caught in CI...
- Use a quoted syntax for some more syntax-invalid `calc()` rules for compatibility with Sass 1.41, which checks them more thoroughly (see …

chore: Bump Node and Sass versions, and some misc housekeeping

---

packages/mdc-slider/test/foundation.test.ts

Relates to issue #7404
DO NOT MERGE THIS PR - IT IS MERELY TO TEST WORKFLOWS.
The new test in slider/foundation.test.ts ought to fail a unit test. I have no way to run tests locally and need this PR to run in order to review the test result (to confirm, the test should fail). This PR is to be deleted once PR #7458 is merged.
@joyzhong would you mind enabling this to run GitHub Actions for the unit test? Thank you.

test(slider): Test for rounding errors

---

karma.conf.js

Remove firefox testing for now because it is blocking GitHub actions.

chore: remove firefox testing
